Repository status-im/status-desktop, pull requests merged in 2020-11, with the labels that each got.

#1272 ci: install qtwebengine with Qt on windows
  scripts/windows_build_setup.ps1
Labels: ci, windows

#1260 [WIP] ci: provide INFURA_TOKEN to builds
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.windows
Labels: ci

#1294 set mailserverfleet on init
  src/status/mailservers.nim
Labels: do not merge
