Repository status-im/status-desktop, pull requests merged in 2021-07, with the labels that each got.

#2803 Fixed issues #2560, #2795, #2796.
  ui/app/AppLayouts/Browser/BrowserLayout.qml
  ui/app/AppLayouts/Profile/Sections/Ens/TermsAndConditions.qml
Labels: tested, ui

#2747 refactor: Profile
  src/app/profile/core.nim
  src/app/profile/view.nim
  src/app/profile/views/muted_chats.nim
  src/app/profile/views/profile_picture.nim
  src/app/profile/views/profile_settings.nim
  src/app/provider/view.nim
  ui/app/AppLayouts/Profile/Sections/ChangeProfilePicModal.qml
  ui/app/AppLayouts/Profile/Sections/MutedChatsModal.qml
  ui/app/AppLayouts/Profile/Sections/NotificationsContainer.qml
  ui/app/AppMain.qml
  ui/main.qml
Labels: tested

#2779 fix: typing in `<` in the input box deletes everything afterwards in
  ui/shared/status/StatusChatInput.qml
Labels: tested

#2787 fix(community): fix crash on going back to chats from community
  src/app/chat/views/channel.nim
Labels: tested

#2790 fix(communities): bug: "Invite successfully sent" shown prematurely on Community invite popup
  ui/shared/ContactsListAndSearch.qml
Labels: tested

#2801 fix: pin messages counter / load
  src/app/chat/view.nim
  src/app/chat/views/messages.nim
Labels: tested

#2802 fix: channel description width
  ui/shared/status/StatusChatInfo.qml
Labels: tested

#2815 fix(enhancement): Onboarding screen changes
  ui/onboarding/BeforeGetStartedModal.qml
Labels: tested

#2816 fix(wallet): Clicking Request Address when sending -1 STT crashes the app
  src/status/utils.nim
  ui/shared/AssetAndAmountInput.qml
Labels: tested

#2817 fix(wallet): Crash when enter -1 to Gas Selector
  src/app/wallet/views/gas.nim
  ui/shared/GasSelector.qml
Labels: tested

#2814 fix(activity_center): Mark as read does not clear @ symbol in chat
  src/app/chat/event_handling.nim
  src/app/chat/views/activity_notification_list.nim
  src/app/chat/views/channel.nim
  src/app/chat/views/channels_list.nim
  src/app/chat/views/chat_item.nim
  src/app/chat/views/communities.nim
  src/app/chat/views/community_list.nim
  src/status/chat.nim
  src/status/chat/chat.nim
  src/status/signals/messages.nim
  ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml
  ui/app/AppLayouts/Chat/ContactsColumn/ChannelList.qml
Labels: tested

#2834 fix(@desktop/wallet): app crash when signing token transaction with invalid password
  src/app/wallet/views/transactions.nim
Labels: tested

#2844 fix(@desktop/timeline): can't click the links and hashtags in timeline
  ui/app/AppLayouts/Chat/ChatColumn/Message.qml
  ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml
  ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/StatusUpdate.qml
  ui/app/AppLayouts/Timeline/TimelineLayout.qml
Labels: tested

#2848 fix(wallet): make it possible to send a 0 tx with a warning
  ui/imports/Themes/DarkTheme.qml
  ui/imports/Themes/LightTheme.qml
  ui/shared/AssetAndAmountInput.qml
  ui/shared/Input.qml
  ui/shared/SearchResults.qml
Labels: tested

#2866 fix(@desktop/chat): app crash when you accept contact request
  src/app/chat/views/channel.nim
  src/app/chat/views/channels_list.nim
  src/app/chat/views/chat_item.nim
  ui/app/AppLayouts/Chat/components/AcceptRejectOptionsButtons.qml
  ui/app/AppLayouts/Chat/components/ContactRequest.qml
Labels: tested

#2858 fix(@desktop/chat): app crash when you leave a chat
  src/app/chat/views/channel.nim
  src/status/chat.nim
  ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
  ui/app/AppLayouts/Chat/ChatColumn/Message.qml
Labels: tested

#2914 fix(@desktop/chat): sign and send appears for both recipient and sender when sharing the address
  src/app/chat/event_handling.nim
  src/app/chat/view.nim
  src/app/chat/views/message_list.nim
  src/app/chat/views/messages.nim
  src/app/chat/views/transactions.nim
  src/status/chat.nim
  src/status/chat/message.nim
  src/status/chat/utils.nim
  src/status/libstatus/chat.nim
  src/status/libstatus/chatCommands.nim
  src/status/signals/messages.nim
  ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/SignTransactionModal.qml
  ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/TransactionBubble.qml
Labels: tested

#2950 fix(@desktop/chat): cannot unpin last message in modal
  src/app/chat/event_handling.nim
  src/app/chat/view.nim
  src/app/chat/views/message_list.nim
  src/app/chat/views/messages.nim
Labels: tested

#2963 feat(link): handle group chat invite links
  src/app/chat/views/groups.nim
  src/status/chat.nim
  src/status/libstatus/chat.nim
  ui/imports/Utils.qml
Labels: tested

#3020 fix(CreateCategoryPopup): ensure delete button and name input stay in…
  ui/app/AppLayouts/Chat/CommunityComponents/CreateCategoryPopup.qml
Labels: tested

#3025 Limit to 3 pins and show how to unpin
  ui/app/AppLayouts/Chat/components/MessageContextMenu.qml
  ui/app/AppLayouts/Chat/components/PinnedMessagesPopup.qml
  ui/imports/Constants.qml
Labels: tested

#3090 fix(@desktop/onboarding): erase mnemonic when register with existing key
  ui/app/AppMain.qml
  ui/main.qml
Labels: beta.11, tested

#3107 fix(@desktop/chat): click on "Notification settings" doesn't take the user to that section
  ui/app/AppLayouts/Profile/LeftTab/Menu.qml
Labels: beta.11

#3109 fix(@desktop/communities): fix translation for members count
  ui/app/AppLayouts/Chat/CommunityComponents/CommunitiesPopup.qml
Labels: beta.11
