Repository status-im/status-desktop, pull requests merged in 2021-09, with the labels that each got.

#3362 fix(@desktop/windows): installer to include cacert.pem
  Makefile
  cacert.pem
Labels: tested

#3406 fix(@desktop/chat): do not crash when deleting a message
  src/status/chat.nim
Labels: tested

#3428 fix(@desktop/onboard): don't submit password creation form on enter w…
  ui/onboarding/CreatePasswordModal.qml
Labels: tested, 0.3.0

#3452 fix(dektop/profile) Back up seed was gone
  ui/app/AppLayouts/Profile/LeftTab/Menu.qml
  ui/app/AppLayouts/Profile/Sections/ChangePasswordSuccessModal.qml
Labels: tested, 0.3.0

#3453 fix(desktop/wallet2) Updated wallet2 warning text
  ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml
  ui/app/AppMain.qml
Labels: testing, 0.3.0

#3537 fix: set preferred username
  src/app/profile/views/ens_manager.nim
Labels: tested

#3454 fix(@desktop/profile): show ENS username in profile page if available
  src/app/profile/views/ens_manager.nim
  ui/app/AppLayouts/Profile/Sections/MyProfileContainer.qml
Labels: tested, QA

#3516 fix(@desktop/chat): Fix for Leave chat is shown instead of Delete con…
  ui/app/AppLayouts/Chat/ChatColumn.qml
  ui/app/AppLayouts/Chat/components/ChatContextMenu.qml
  ui/shared/ConfirmationDialog.qml
Labels: tested

#3513 feat(communities): re-enabled open membership communities
  ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/InvitationBubble.qml
  ui/app/AppLayouts/Chat/CommunityComponents/CreateCommunityPopup.qml
  ui/app/AppLayouts/Chat/CommunityComponents/MembershipRequirementPopup.qml
Labels: tested, QA

#3530 fix: in profile popup display Username instead of ENS Username if ENS is not verified
  ui/app/AppLayouts/Chat/components/ProfilePopup.qml
Labels: tested

#3534 feat(desktop/profile): add link in advanced settings so log directory can be opened directly
  src/app/profile/view.nim
  ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml
Labels: tested

#3555 fix(@desktop/chat): ensure replacement of mentions with pubkey works …
  src/app/chat/views/community_members_list.nim
  src/app/chat/views/messages.nim
  src/app/chat/views/user_list.nim
Labels: tested

#3644 fix(desktop/chatInput) mentions were misused
  ui/app/AppLayouts/Chat/ChatColumn/SuggestionBox.qml
Labels: bug

#3533 feat(wallet2) Implementing new architecture proposal
  package-lock.json
  ui/app/AppLayouts/WalletV2/WalletV2Layout.qml
  ui/app/AppLayouts/WalletV2/components/AddAccountPopup.qml
  ui/app/AppLayouts/WalletV2/components/network/qmldir
  ui/app/AppLayouts/WalletV2/components/qmldir
  ui/app/AppLayouts/WalletV2/controls/CollectibleDetailsHeader.qml
  ui/app/AppLayouts/WalletV2/controls/HeaderButton.qml
  ui/app/AppLayouts/WalletV2/controls/SavedAddressesError.qml
  ui/app/AppLayouts/WalletV2/controls/SeedAccountDetailsDelegate.qml
  ui/app/AppLayouts/WalletV2/controls/WalletButton.qml
  ui/app/AppLayouts/WalletV2/panels/AccountNotFoundPanel.qml
  ui/app/AppLayouts/WalletV2/panels/NetworkFilterPanel.qml
  ui/app/AppLayouts/WalletV2/panels/NetworkSelectPanel.qml
  ui/app/AppLayouts/WalletV2/panels/PKeyAccountDetailsPanel.qml
  ui/app/AppLayouts/WalletV2/panels/SeedPhraseBackupWarningPanel.qml
  ui/app/AppLayouts/WalletV2/panels/WalletFooterPanel.qml
  ui/app/AppLayouts/WalletV2/panels/WalletHeaderPanel.qml
  ui/app/AppLayouts/WalletV2/popups/AddAccountPopup.qml
  ui/app/AppLayouts/WalletV2/popups/AddEditSavedAddressPopup.qml
  ui/app/AppLayouts/WalletV2/popups/CollectibleModal.qml
  ui/app/AppLayouts/WalletV2/popups/CryptoServicesModal.qml
  ui/app/AppLayouts/WalletV2/popups/NetworkSelectPopup.qml
  ui/app/AppLayouts/WalletV2/popups/ShareModal.qml
  ui/app/AppLayouts/WalletV2/popups/SignPhraseModal.qml
  ui/app/AppLayouts/WalletV2/qmldir
  ui/app/AppLayouts/WalletV2/stores/CollectiblesStore.qml
  ui/app/AppLayouts/WalletV2/stores/RootStore.qml
  ui/app/AppLayouts/WalletV2/views/AddAccountView.qml
  ui/app/AppLayouts/WalletV2/views/CollectiblesView.qml
  ui/app/AppLayouts/WalletV2/views/LeftTabView.qml
  ui/app/AppLayouts/WalletV2/views/SavedAddressesView.qml
  ui/app/AppLayouts/WalletV2/views/SeedAddAccountView.qml
  ui/app/AppLayouts/WalletV2/views/SettingsTabView.qml
  ui/app/AppLayouts/WalletV2/views/collectibles/CollectibleCollectionView.qml
  ui/app/AppLayouts/WalletV2/views/collectibles/CollectibleDetailView.qml
Labels: wallet-redesign

#3691 fix(@desktop/chat): abnormal CPU usage and slowness
  ui/shared/ImageLoader.qml
Labels: tested

#3681 feat(desktop/searchMessage) Updating highlight animation
  ui/app/AppLayouts/Chat/ChatColumn.qml
  ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
  ui/app/AppLayouts/Chat/ChatColumn/Message.qml
  ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml
Labels: ui
