Repository status-im/status-desktop, pull requests merged in 2021-06, with the labels that each got.

#2600 ci: implement MacOS notarization using xcrun altool
  .gitignore
  Makefile
  ci/Jenkinsfile.macos
  docs/images/gatekeeper_warning.png
  docs/macos_notarization.md
  scripts/notarize-macos-pkg.sh
Labels: ci, macos

#2622 fix: Timeline view crash with SIGSEGV when loaded
  src/app/chat/view.nim
Labels: tested

#2656 ci: do no delete non-draft releases
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.windows
Labels: ci, release

#2620 fix: loading of wallet history, display of tx datetime
  devuser_guide/content/api/qml/wallet.md
  docs/qml_api.md
  src/app/utilsView/view.nim
  src/app/wallet/core.nim
  src/app/wallet/view.nim
  src/app/wallet/views/account_list.nim
  src/app/wallet/views/transaction_list.nim
  src/status/libstatus/conversions.nim
  src/status/libstatus/core.nim
  src/status/libstatus/types.nim
  src/status/libstatus/utils.nim
  src/status/libstatus/wallet.nim
  src/status/tasks/common.nim
  src/status/wallet.nim
  src/status/wallet/account.nim
  ui/app/AppLayouts/Browser/BrowserWalletMenu.qml
  ui/app/AppLayouts/Wallet/HistoryTab.qml
  ui/app/AppLayouts/Wallet/WalletLayout.qml
  ui/app/AppLayouts/Wallet/components/AddAccount.qml
  ui/app/AppLayouts/Wallet/components/AddAccountWithPrivateKey.qml
  ui/app/AppLayouts/Wallet/components/AddAccountWithSeed.qml
  ui/app/AppLayouts/Wallet/components/AddWatchOnlyAccount.qml
  ui/app/AppLayouts/Wallet/components/GenerateAccountModal.qml
Labels: tested

#2630 fix: display "View" on already joined community invites
  ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/InvitationBubble.qml
Labels: tested

#2631 Remove community from list after being kicked/banned from it
  src/app/chat/event_handling.nim
Labels: tested

#2684 fix: kick and re-invite user to group chat
  src/app/chat/view.nim
  src/app/chat/views/chat_item.nim
  src/status/chat/chat.nim
  src/status/chat/utils.nim
  ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChannelIdentifier.qml
  ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml
  ui/app/AppLayouts/Chat/components/ChannelContextMenu.qml
  ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml
Labels: tested

#2697 fix: remove actions from community member when self
  ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupMembersList.qml
Labels: tested

#2704 fix: invalid variable being used for identicons in transaction commands
  ui/app/AppLayouts/Chat/ChatColumn.qml
Labels: tested-issues

#2736 fix: edit channel modal header
  ui/app/AppLayouts/Chat/CommunityComponents/CreateChannelPopup.qml
Labels: tested

#2706 fix(communities): hide edit category menu for non-admins
  ui/app/AppLayouts/Chat/CommunityComponents/CategoryList.qml
Labels: tested

#2705 feat(act-center): add community badge with link to community and channel
  src/app/chat/view.nim
  src/app/chat/views/activity_notification_list.nim
  src/app/chat/views/community_list.nim
  src/status/chat.nim
  ui/app/AppLayouts/Chat/ChatColumn/ActivityCenter.qml
  ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/ActivityChannelBadge.qml
Labels: tested

#2713 fix(communities): re-joining of left communities
  src/app/chat/views/communities.nim
  src/app/chat/views/community_list.nim
  src/status/libstatus/chat.nim
  ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/InvitationBubble.qml
Labels: tested

#2748 fix(wallet): fix gas price being 0 and add back validation
  ui/shared/GasSelector.qml
  ui/shared/GasValidator.qml
Labels: tested

#2763 fix(Communities) Long community names should be truncated
  ui/app/AppLayouts/Chat/CommunityColumn.qml
  ui/app/AppLayouts/Chat/CommunityComponents/CommunityHeaderButton.qml
  ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopup.qml
Labels: tested

#2766 fix: chat view shown after community creation
  src/app/chat/views/channel.nim
Labels: tested

#2767 fix(communities): Right click inside the community pane does not open context menu
  ui/app/AppLayouts/Chat/CommunityColumn.qml
  ui/app/AppLayouts/Chat/CommunityComponents/BackUpCommuntyBanner.qml
  ui/app/AppLayouts/Chat/CommunityComponents/CategoryList.qml
  ui/app/AppLayouts/Chat/CommunityComponents/CommunityWelcomeBanner.qml
Labels: tested

#2770 fix(onboarding): Mobile onboarding slider is shown on desktop
  ui/main.qml
  ui/nim-status-client.pro
  ui/onboarding/BeforeGetStartedModal.qml
  ui/onboarding/Intro.qml
  ui/onboarding/KeysMain.qml
  ui/onboarding/Slide.qml
  ui/onboarding/qmldir
  ui/shared/ModalPopup.qml
Labels: tested
