Repository status-im/status-desktop, pull requests merged in 2021-11, with the labels that each got.

#4022 fix(@desktop/onboarding): All chat names are not displayed on the popup
  ui/app/AppLayouts/Onboarding/panels/AccountListPanel.qml
Labels: tested

#4020 fix(desktop/profileSettings) fixed sliders in appearance
  ui/app/AppLayouts/Profile/views/AppearanceView.qml
Labels: testing

#4034 fix(desktop/chat) image was not displayed in message
  ui/app/AppLayouts/Chat/views/CompactMessageView.qml
Labels: refactor_base_01

#4012 fix(@refactoring/base_01): crash on recovering account
  src/app_service/service/contacts/service.nim
Labels: refactor_base_01

#4031 Fix context menu losing data and group info being empty sometimes
  src/app/chat/views/channel.nim
  ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
  ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
Labels: refactor_base_01

#4033 refactor(desktop/chat) fixed sticker disappears when replying
  ui/app/AppLayouts/Chat/views/CompactMessageView.qml
Labels: don't merge yet, testing, refactor_base_01

#3965 fix: make user profile images work again
  ui/app/AppLayouts/Chat/popups/GroupChatPopup.qml
  ui/app/AppLayouts/Chat/popups/PrivateChatPopup.qml
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/ChatColumnView.qml
  ui/app/AppMain.qml
  ui/imports/shared/popups/UserStatusContextMenu.qml
  ui/imports/shared/status/StatusChatInput.qml
Labels: tested, refactor_base_01

#4076 fix(desktop/chatInput) sticker was not shown in reply area
  ui/imports/shared/status/StatusChatInput.qml
  ui/imports/shared/status/StatusChatInputReplyArea.qml
Labels: tested

#4021 fix(@desktop/chat): Modal on the Pinned Messages Popup isnt seen
  ui/app/AppLayouts/Chat/panels/ChatButtonsPanel.qml
  ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml
  ui/app/AppLayouts/Chat/views/CompactMessageView.qml
  ui/app/AppLayouts/Chat/views/MessageView.qml
Labels: tested, refactor_base_01

#3941 refactor: replace `Select` with `StatusSelect`
  ui/imports/shared/controls/AddressSourceSelector.qml
  ui/imports/shared/controls/AssetSelector.qml
  ui/imports/shared/controls/ContactSelector.qml
  ui/imports/shared/controls/Select.qml
  ui/imports/shared/controls/qmldir
Labels: needs-rebase

#4081 fix(@desktop/communities): Fix for can't import community
  ui/app/AppLayouts/Chat/popups/community/AccessExistingCommunityPopup.qml
Labels: tested

#4070 fix(@desktop/browser): Fix for custom homepage not launched in dapp browser
  ui/app/AppLayouts/Browser/panels/BrowserTabView.qml
Labels: tested

#4077 Fix adding custom tokens
  src/app/boot/app_controller.nim
  src/app/modules/main/wallet_section/all_tokens/controller.nim
  src/app/modules/main/wallet_section/all_tokens/controller_interface.nim
  src/app/modules/main/wallet_section/all_tokens/io_interface.nim
  src/app/modules/main/wallet_section/all_tokens/module.nim
  src/app/modules/main/wallet_section/all_tokens/view.nim
  src/app/modules/main/wallet_section/module.nim
  src/app_service/service/token/async_tasks.nim
  src/app_service/service/token/service.nim
  src/app_service/service/token/service_interface.nim
  ui/app/AppLayouts/Wallet/popups/AddCustomTokenModal.qml
  ui/app/AppLayouts/Wallet/stores/RootStore.qml
Labels: tested

#4117 fix: Fix missing setup url for new opened tab
  ui/app/AppLayouts/Browser/BrowserLayout.qml
Labels: tested

#4124 fix(desktop/version) version updated to 0.4.0
  VERSION
Labels: tested

#4098 fix(dekstop/wallet) wrong account color displayed
  ui/app/AppLayouts/Wallet/panels/WalletHeader.qml
  ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml
  ui/app/AppLayouts/Wallet/stores/RootStore.qml
Labels: tested

#4146 ci: manually fix expired LetsEncrypt X3 root cert
  ci/Dockerfile
  ci/Jenkinsfile.linux
Labels: ci, linux, dependencies

#4142 fix(@desktop/startUpPage): Fix for footer shown when clicking - share your chat key
  ui/app/AppMain.qml
Labels: tested

#4135 fix(desktop/chat) Can't select emoji from the list
  src/app/core/local_account_sensitive_settings.nim
Labels: tested

#4153 fix(@desktop/browser): Wallet permissions and enter password modals are stretched
  ui/app/AppLayouts/Browser/BrowserLayout.qml
  ui/app/AppLayouts/Browser/popups/BrowserConnectionModal.qml
Labels: tested

#4156 fix(@desktop/browser): Sign message to dapp is broken
  ui/app/AppLayouts/Browser/stores/WalletStore.qml
  ui/app/AppLayouts/Browser/views/WebProviderObj.qml
Labels: tested

#4159 uiux: inform user early when there's no stickers installed
  ui/imports/shared/status/StatusStickersPopup.qml
Labels: tested

#4163 fix(@desktop/chat): ensure emoji selection works
  ui/main.qml
Labels: tested

#4193 ci: specify macos host architecture in labels
  ci/Jenkinsfile.macos
Labels: macos, ci

#4190 fix(reply): fix reply image displaying the current user
  ui/app/AppLayouts/stores/MessageStore.qml
  ui/imports/shared/controls/chat/UserImage.qml
  ui/imports/shared/panels/chat/ChatReplyPanel.qml
  ui/imports/shared/views/chat/CompactMessageView.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: tested
