Repository status-im/status-desktop, pull requests merged in 2021-04, with the labels that each got.

#2250 CI: Add a combined Jenkinsfile for releases
  ci/Jenkinsfile
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.windows
Labels: ci

#2244 build: fetch macOS Homebrew bottles from GitHub Packages instead of bintray
  Makefile
  config.nims
Labels: macos

#2251 uiux: fix sticker message border color
  ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml
Labels: tested

#2258 build: use GitHub credentials when downloading bottles for macOS
  Makefile
  ci/Jenkinsfile.macos
  scripts/fetch-brew-bottle.sh
Labels: don't merge yet, macos

#2168 fix: create community and channel name validation
  ui/app/AppLayouts/Chat/CommunityComponents/CreateChannelPopup.qml
  ui/app/AppLayouts/Chat/CommunityComponents/CreateCommunityPopup.qml
  ui/shared/ImageCropper.qml
  ui/shared/ImageCropperModal.qml
Labels: tested

#2265 feat: store appearance settings globally across accounts
  ui/app/AppLayouts/Profile/Sections/AppearanceContainer.qml
  ui/app/AppMain.qml
  ui/imports/Style.qml
  ui/main.qml
Labels: tested

#2270 CI: add ability to create draft GitHub releases
  VERSION
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.windows
Labels: ci

#2319 fix: Add close button to seed backup warning
  ui/app/AppLayouts/Wallet/SeedPhraseBackupWarning.qml
  ui/app/img/close-white.svg
Labels: tested

#1966 uiux(StatusChatInput): toggle markdown from selection
  ui/shared/status/StatusChatInput.qml
Labels: tested

#2289 feat: process activeFocusChange event and select all in address line …
  ui/app/AppLayouts/Browser/BrowserHeader.qml
Labels: tested

#2361 ci: bump jenkins lib to make release filenames nicer
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.windows
Labels: ci

#2428 feat: show ENS name in notifications
  src/app/chat/view.nim
Labels: tested

#2397 build: use same container as Jenkins CI for local packaged builds on Linux
  AppRun
  Makefile
  build-linux.sh
  ci/Dockerfile
  ci/Jenkinsfile.linux
  docker-linux-app-image.sh
  nim-status.desktop
Labels: linux

#2459 build: launch nim_status_client directly in packaged builds for macOS
  Info.runner.plist
  Makefile
  nim_status_client.sh
  src/nim_status_client.nim
Labels: macos

#2457 ci: scripts/sign-windows-bin.sh for signing Windows binaries
  Makefile
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.windows
  docs/windows_signing.md
  scripts/sign-windows-bin.sh
  scripts/windows_build_setup.ps1
Labels: ci, windows

#2466 fix(TextArea): fix selecting text in a TextArea and placeholder color
  ui/app/AppLayouts/Chat/CommunityComponents/CreateCommunityPopup.qml
  ui/shared/StyledTextArea.qml
Labels: tested

#2461 feat: introduce StatusNavBarTabButton
  ui/app/AppLayouts/Chat/CommunityComponents/CommunityButton.qml
  ui/app/AppLayouts/Chat/CommunityComponents/CommunityList.qml
  ui/app/AppLayouts/Chat/components/LeftTabBottomButtons.qml
  ui/app/AppMain.qml
  ui/shared/status/buttons/StatusNavBarTabButton.qml
Labels: Component Library

#2424 Implement redesign of message replies
  src/app/chat/views/message_list.nim
  ui/app/AppLayouts/Chat/ChatColumn/Message.qml
  ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatReply.qml
  ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml
  ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ImageLoader.qml
  ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/Sticker.qml
  ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/UserImage.qml
  ui/app/img/reply-corner.svg
Labels: QA, tested

#2357 fix: do not show watch-only accounts as “from address”
  ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/ChatCommandModal.qml
  ui/app/AppLayouts/Profile/Sections/Ens/RegisterENSModal.qml
  ui/app/AppLayouts/Profile/Sections/Ens/SetPubKeyModal.qml
  ui/app/AppLayouts/Wallet/SendModal.qml
  ui/shared/AccountSelector.qml
  ui/shared/status/StatusStickerPackPurchaseModal.qml
Labels: tested

#2426 fix: Send Message button not working in profile popup
  src/app/chat/view.nim
  src/status/signals/messages.nim
  ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml
  ui/app/AppLayouts/Chat/components/ProfilePopup.qml
  ui/app/AppMain.qml
Labels: tested
