Repository status-im/status-desktop, pull requests merged in 2021-08, with the labels that each got.

#3125 fix: translations
  ui/app/AppLayouts/Chat/ChatColumn.qml
  ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/LinksMessage.qml
  ui/app/AppLayouts/Chat/ChatColumn/UserList.qml
  ui/app/AppLayouts/Chat/CommunityComponents/CommunitiesPopup.qml
  ui/app/AppLayouts/Chat/CommunityComponents/CommunityUserList.qml
  ui/app/AppLayouts/Chat/ContactsColumn.qml
  ui/app/AppLayouts/Chat/components/MessageContextMenu.qml
  ui/app/AppLayouts/Chat/components/PinnedMessagesPopup.qml
  ui/app/AppLayouts/Chat/components/PrivateChatPopup.qml
  ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml
  ui/app/AppLayouts/Profile/Sections/NotificationsContainer.qml
  ui/i18n/base.qm
  ui/i18n/base.ts
  ui/i18n/qml_ar.qm
  ui/i18n/qml_ar.ts
  ui/i18n/qml_de.qm
  ui/i18n/qml_de.ts
  ui/i18n/qml_en.qm
  ui/i18n/qml_en.ts
  ui/i18n/qml_es.qm
  ui/i18n/qml_es.ts
  ui/i18n/qml_fil.qm
  ui/i18n/qml_fil.ts
  ui/i18n/qml_fr.qm
  ui/i18n/qml_fr.ts
  ui/i18n/qml_id.qm
  ui/i18n/qml_id.ts
  ui/i18n/qml_it.qm
  ui/i18n/qml_it.ts
  ui/i18n/qml_ko.qm
  ui/i18n/qml_ko.ts
  ui/i18n/qml_pt_BR.qm
  ui/i18n/qml_pt_BR.ts
  ui/i18n/qml_ru.qm
  ui/i18n/qml_ru.ts
  ui/i18n/qml_tr.qm
  ui/i18n/qml_tr.ts
  ui/i18n/qml_ur.qm
  ui/i18n/qml_ur.ts
  ui/i18n/qml_zh.qm
  ui/i18n/qml_zh.ts
  ui/i18n/qml_zh_TW.qm
  ui/i18n/qml_zh_TW.ts
  ui/imports/Utils.qml
  ui/onboarding/Login.qml
  ui/shared/ConfirmationDialog.qml
Labels: beta.11, tested

#3120 [#3119] Fixiing profile picture not correct in add new chat popup
  ui/app/AppLayouts/Chat/components/PrivateChatPopup.qml
Labels: beta.11, tested

#3076 chores(@desktop/chat): add guard when buying stickers
  src/app/chat/views/stickers.nim
  src/status/utils.nim
Labels: tested

#3132 fix(@desktop/wallet): load collectible on initial account set
  src/app/wallet/view.nim
Labels: beta.11, tested

#3186 fix(@desktop/settings): Enable stickers/ens on ropsten
  ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml
  ui/app/AppLayouts/Profile/Sections/Ens/Welcome.qml
  ui/app/AppLayouts/Profile/Sections/EnsContainer.qml
  ui/app/AppMain.qml
  ui/shared/status/StatusChatInput.qml
Labels: tested

#3151 fix(@desktop/wallet): Total balance reflect real total
  src/status/wallet/balance_manager.nim
Labels: tested

#3194 fix(@desktop/onboarding): fix crash when restoring keys
  src/app/profile/core.nim
Labels: tested

#3193 fix(@desktop/installer): InnoSetup script fixes
  status.iss
Labels: tested

#3200 fix(@desktop): crash when transitioning to the app state
  src/app/login/core.nim
  src/app/login/view.nim
  src/app/onboarding/core.nim
  src/app/onboarding/view.nim
  src/nim_status_client.nim
  ui/main.qml
Labels: tested

#3207 fix(@desktop): crash on shutdown path
  src/app/wallet/view.nim
  src/nim_status_client.nim
Labels: tested

#3215 fix(@desktop/installer): further improving of Inno Setup script
  status.iss
Labels: tested

#3220 fix(@desktop/onboarding): display the app, then init the profile
  src/nim_status_client.nim
Labels: tested

#3222 fix(@desktop/chat): fix replying to message at early chat
  ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
Labels: tested

#3185 ci: add scripts/sign-linux-tarball.sh for GPG signing
  Makefile
  ci/Dockerfile
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.windows
  scripts/sign-linux-file.sh
  scripts/sign-macos-pkg.sh
Labels: ci, security, release

#3322 fix(@desktop/chatInput) Pasting text with emoji was invisible
  ui/shared/status/StatusChatInput.qml
Labels: tested
