Repository status-im/status-desktop, pull requests merged in 2022-07, with the labels that each got.

#6242 feat(@desktop/wallet): Using Floating Buttons in the Send Modal
  ui/app/mainui/AppMain.qml
  ui/imports/shared/controls/AmountInputWithCursor.qml
  ui/imports/shared/popups/SendModal.qml
  ui/imports/shared/views/SendModalHeader.qml
Labels: tested

#5713 fix(1-1): fix contact label not updating when mutual contact changes
  src/app/modules/main/chat_section/chat_content/chat_details.nim
  src/app/modules/main/chat_section/chat_content/controller.nim
  src/app/modules/main/chat_section/chat_content/io_interface.nim
  src/app/modules/main/chat_section/chat_content/module.nim
  src/app/modules/main/chat_section/chat_content/view.nim
  src/app_service/service/contacts/dto/contacts.nim
  src/app_service/service/contacts/service.nim
Labels: bug, tested

#6317 fix(chat): Fix chat screen for empty state visibility
  ui/app/AppLayouts/Chat/views/ChatColumnView.qml
Labels: tested

#6058 feat(@desktop/general): Change user statuses
  src/app/boot/app_controller.nim
  src/app/global/user_profile.nim
  src/app/modules/main/chat_section/chat_content/users/module.nim
  src/app/modules/main/communities/controller.nim
  src/app/modules/main/communities/module.nim
  src/app/modules/main/controller.nim
  src/app/modules/main/io_interface.nim
  src/app/modules/main/module.nim
  src/app/modules/main/view.nim
  src/app/modules/shared_models/member_item.nim
  src/app/modules/shared_models/member_model.nim
  src/app/modules/shared_models/user_item.nim
  src/app/modules/shared_models/user_model.nim
  src/app_service/common/conversion.nim
  src/app_service/common/types.nim
  src/app_service/service/contacts/dto/status_update.nim
  src/app_service/service/contacts/service.nim
  src/app_service/service/settings/dto/settings.nim
  src/app_service/service/settings/service.nim
  ui/app/AppLayouts/Chat/panels/UserListPanel.qml
  ui/app/AppLayouts/Chat/panels/communities/CommunityMembersSettingsPanel.qml
  ui/app/mainui/AppMain.qml
  ui/imports/shared/popups/UserStatusContextMenu.qml
  ui/imports/utils/Constants.qml
Labels: tested

#6231 fix(@node): set bloom filter to normal
  src/app_service/service/node_configuration/service.nim
Labels: tested

#6342 Fix slow chat switching because of height recalculation
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: tested

#6384 fix(CreateChatView): hide the Contacts label when no contacts
  ui/app/AppLayouts/Chat/panels/GroupChatPanel.qml
  ui/app/AppLayouts/Chat/views/CreateChatView.qml
Labels: tested

#6376 fix(profile): the profile image is blurred in different places
  ui/app/AppLayouts/Profile/views/profile/MyProfileSettingsView.qml
  ui/imports/shared/controls/chat/ProfileHeader.qml
  ui/imports/shared/popups/ProfilePopup.qml
  ui/imports/shared/views/ProfileView.qml
Labels: tested

#6341 fix(CommunitySettings): Process statuses for members model
  src/app/modules/main/controller.nim
  src/app/modules/main/io_interface.nim
  src/app/modules/main/module.nim
  src/app/modules/shared_models/active_section.nim
  src/app/modules/shared_models/section_item.nim
Labels: tested

#6308 fix(Community): Add check for admin permissions for context menu
  ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Labels: tested

#6372 Fix(Chat): Reset MessageContextMenuView state on close
  src/app_service/service/contacts/service.nim
  ui/imports/shared/views/chat/MessageContextMenuView.qml
Labels: tested

#6367 feat(chat): Message display several images
  src/app_service/service/chat/service.nim
  ui/imports/shared/views/chat/CompactMessageView.qml
Labels: tested

#6329 fix: logs on node tab
  Makefile
  src/nim_status_client.nim
Labels: tested

#6402 fix(Chat/ReactionDialog): The reaction dialog is shown in different places
  ui/imports/shared/views/chat/CompactMessageView.qml
  ui/imports/shared/views/chat/MessageContextMenuView.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: Chat, tested, E:Bugfixes

#6424 fix(@desktop/wallet): Fix for Wallet icon background color seems off in wallet settings under dark mode
  ui/app/AppLayouts/Profile/controls/WalletAccountDelegate.qml
  ui/app/AppLayouts/Wallet/views/LeftTabView.qml
Labels: tested

#6370 fix(@desktop): correct spelling of you-r
  ui/app/AppLayouts/Onboarding/views/ConfirmPasswordView.qml
Labels: testing

#6425 fix(CreateChatView): fixed no contacts text alignment
  ui/app/AppLayouts/Chat/views/CreateChatView.qml
Labels: tested

#6447 fix(AppMain): put dropRectangle in a Loader, active when dragging
  ui/app/mainui/AppMain.qml
Labels: tested

#6457 fix(CommunitPortal): Scroll doesn't work correctly on the Community Portal page
  ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml
Labels: ui, Communities, tested, E:Bugfixes, E:Communities, ui-improvements

#5290 fix(chat): removing dynamic scoping from chat section
  ui/app/AppLayouts/Chat/ChatLayout.qml
  ui/app/AppLayouts/Chat/controls/activityCenter/ReplyComponent.qml
  ui/app/AppLayouts/Chat/panels/ActivityCenterPopupTopBarPanel.qml
  ui/app/AppLayouts/Chat/panels/ActivityChannelBadgePanel.qml
  ui/app/AppLayouts/Chat/panels/communities/CommunityChannelsAndCategoriesBannerPanel.qml
  ui/app/AppLayouts/Chat/panels/communities/CommunityWelcomeBannerPanel.qml
  ui/app/AppLayouts/Chat/popups/ActivityCenterPopup.qml
  ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml
  ui/app/AppLayouts/Chat/popups/community/CommunitiesPopup.qml
  ui/app/AppLayouts/Chat/popups/community/CommunityDetailPopup.qml
  ui/app/AppLayouts/Chat/popups/community/MembershipRequestsPopup.qml
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/ActivityCenterGroupRequest.qml
  ui/app/AppLayouts/Chat/views/ActivityCenterMessageComponentView.qml
  ui/app/AppLayouts/Chat/views/ChatColumnView.qml
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/app/AppLayouts/Chat/views/ChatView.qml
  ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
  ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
  ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
  ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml
  ui/app/mainui/AppMain.qml
  ui/imports/utils/Global.qml
Labels: tested

#6178 fix(@desktop/notifications): nothing happens after clicking on any notification
  src/app/core/notifications/details.nim
  src/app/core/notifications/notifications_manager.nim
  src/app/modules/main/ephemeral_notification_item.nim
  src/app/modules/main/ephemeral_notification_model.nim
  src/app/modules/main/io_interface.nim
  src/app/modules/main/module.nim
  src/app/modules/main/view.nim
  ui/app/mainui/AppMain.qml
Labels: tested

#6465 fix(StatusChatInput): 'Unblock' is not vertically aligned in 1-1 chat
  ui/imports/shared/status/StatusChatInput.qml
Labels: bug, tested, E:Bugfixes

#6463 fix(@desktop/onboarding): Align LoginView incorrect pass msg with design
  ui/app/AppLayouts/Onboarding/views/LoginView.qml
  ui/i18n/qml_en.ts
Labels: tested

#6462 fix(@desktop/onboarding): Remove EmptyViewPanel component
  ui/app/AppLayouts/Chat/panels/EmptyViewPanel.qml
  ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
  ui/i18n/qml_en.ts
Labels: tested

#6111 fix: handle sync currency settings
  src/app/modules/main/wallet_section/module.nim
  src/app/modules/main/wallet_section/view.nim
  src/app_service/service/settings/service.nim
  src/app_service/service/wallet_account/service.nim
  ui/app/AppLayouts/Wallet/stores/CurrenciesStore.qml
Labels: tested

#6560 fix(@desktop/chat): remove invalid argument from `showReplyArea`
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
Labels: tested

#6529 fix(@desktop/chat): endless search when user has no chats or communities
  src/app/modules/main/app_search/controller.nim
  src/app_service/service/message/service.nim
Labels: tested

#6461 fix(@desktop/wallet): Send Popup - Can't scroll outside the list of accounts after selecting one
  ui/imports/shared/controls/AmountInputWithCursor.qml
  ui/imports/shared/popups/SendModal.qml
  ui/imports/shared/views/TabAddressSelectorView.qml
Labels: tested

#6588 fix(@desktop/settings) contacts search doesn't work by compressed pk
  ui/app/AppLayouts/Profile/panels/ContactsListPanel.qml
Labels: tested

#6150 fix(@community): Fix community join bubble
  src/app_service/service/community/async_tasks.nim
  src/app_service/service/community/service.nim
  src/backend/communities.nim
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/imports/shared/views/chat/InvitationBubbleView.qml
Labels: tested

#6611 fix(CompactMessageView): disable hovering while scrolling
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/imports/shared/views/chat/CompactMessageView.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: tested

#6322 fix(contacts): Showing letters for contacts without profile picture
  ui/app/AppLayouts/Profile/panels/ContactPanel.qml
Labels: tested

#6664 fix(InsertDetailsView): UI fixes
  ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
Labels: tested

#6672 fix(ContactsListPanel/ContactsView): clipped width and action fixes
  ui/app/AppLayouts/Profile/panels/ContactsListPanel.qml
  ui/app/AppLayouts/Profile/views/ContactsView.qml
Labels: tested

#6663 fix(@desktop/onboarding): make account name area clickable
  ui/app/AppLayouts/Onboarding/views/LoginView.qml
Labels: tested

#6699 fix(@desktop/onboarding): add password fields autofocus
  ui/app/AppLayouts/Onboarding/views/ConfirmPasswordView.qml
  ui/app/AppLayouts/Onboarding/views/CreatePasswordView.qml
Labels: tested

#6631 fix(communities): Cannot leave community, invite, mute from Settings/Communities
  ui/app/AppLayouts/Profile/panels/CommunitiesListPanel.qml
  ui/app/AppLayouts/Profile/views/CommunitiesView.qml
  ui/app/AppLayouts/stores/RootStore.qml
Labels: tested
