Repository status-im/status-desktop, pull requests merged in 2022-08, with the labels that each got.

#6605 fix(Settings/ProfileLayout): TestNet banner overlaps left panel
  ui/app/AppLayouts/Profile/ProfileLayout.qml
Labels: tested

#6715 fix(@wallet): total balance wallet
  src/app_service/service/wallet_account/dto.nim
Labels: tested

#6718 fix(@wallet): do not display balance with scientific format
  ui/imports/shared/controls/AssetDelegate.qml
Labels: tested

#6713 fix(community): Send community invitation fixed
  ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
Labels: tested

#6674 fix(chat_section): reset activeItem when the last channel is removed
  src/app/modules/main/chat_section/active_item.nim
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/chat_section/view.nim
Labels: tested

#6280 feat(@desktop/chat): Add sections to members tab of the community management
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/io_interface.nim
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/chat_section/view.nim
  src/app/modules/main/communities/module.nim
  src/app/modules/main/module.nim
  src/app/modules/shared_models/active_section.nim
  src/app/modules/shared_models/section_item.nim
  src/app/modules/shared_models/section_model.nim
  src/app_service/service/chat/dto/chat.nim
  src/app_service/service/community/dto/community.nim
  src/app_service/service/community/service.nim
  src/backend/communities.nim
  ui/app/AppLayouts/Chat/panels/communities/CommunityMembersSettingsPanel.qml
  ui/app/AppLayouts/Chat/panels/communities/CommunityMembersTabPanel.qml
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
Labels: tested, needs-status-go

#6759 fix(@desktop/chat) keep message hover effect while context menu open
  ui/imports/shared/views/chat/CompactMessageView.qml
  ui/imports/shared/views/chat/MessageContextMenuView.qml
Labels: tested

#6795 fix(@desktop/community) adjust color picker
  ui/app/AppLayouts/CommunitiesPortal/panels/CommunityColorPanel.qml
Labels: tested

#6824 fix(@desktop/community) add delete button to edit channel popup
  ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml
  ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml
Labels: tested

#6779 fix(message-service): ignore new messages in 1-1 when not a contact
  src/app_service/service/message/service.nim
Labels: tested

#6839 fix(@desktop/onboarding): startup stuck when entering wrong password
  src/app/modules/startup/controller.nim
  src/app/modules/startup/module.nim
  ui/main.qml
Labels: tested

#6654 fix(CreateChatView): Move `ActivityCenterPopup` to appmain
  ui/app/AppLayouts/Chat/popups/ActivityCenterPopup.qml
  ui/app/AppLayouts/Chat/popups/qmldir
  ui/app/AppLayouts/Chat/views/ChatColumnView.qml
  ui/app/AppLayouts/Chat/views/CreateChatView.qml
  ui/app/mainui/AppMain.qml
  ui/imports/utils/Global.qml
Labels: tested

#6842 fix(community): Remove " You" suffix from the current user name
  src/app/modules/main/chat_section/chat_content/users/module.nim
Labels: testing

#6840 fix(Communities/ChatsList): chats order updates handled correctly, subitems reordering fixed
  src/app/modules/main/chat_section/item.nim
  src/app/modules/main/chat_section/model.nim
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/chat_section/sub_model.nim
  src/app_service/service/community/service.nim
Labels: tested

#6863 fix(@desktop/wallet) adjust network dropdown
  ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml
  ui/app/AppLayouts/Wallet/popups/NetworkSelectPopup.qml
Labels: tested

#6924 fix(@desktop/keycard): keycard images have white background on dark mode
  ui/imports/assets/icons/keycard/card-error3@2x.svg
  ui/imports/assets/icons/keycard/card-error3@3x.svg
  ui/imports/assets/icons/keycard/card-success3@2x.svg
  ui/imports/assets/icons/keycard/card-success3@3x.svg
  ui/imports/assets/icons/keycard/card0@2x.svg
  ui/imports/assets/icons/keycard/card0@3x.svg
  ui/imports/assets/icons/keycard/card1@2x.svg
  ui/imports/assets/icons/keycard/card1@3x.svg
  ui/imports/assets/icons/keycard/card2@2x.svg
  ui/imports/assets/icons/keycard/card2@3x.svg
  ui/imports/assets/icons/keycard/card3@2x.svg
  ui/imports/assets/icons/keycard/card3@3x.svg
Labels: tested

#6977 fix(nim_status_client): Increased JS engine stack size
  src/nim_status_client.nim
Labels: tested

#6917 fix(@desktop/community): Add tags row on communities portal page
  ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml
  ui/app/AppLayouts/CommunitiesPortal/controls/CommunityTagsRow.qml
  ui/app/AppLayouts/CommunitiesPortal/controls/CommunityTagsRowButton.qml
  ui/imports/assets/icons/arrow-next.svg
  ui/imports/assets/icons/arrow-previous.svg
Labels: tested, needs-statusq

#6955 fix(@desktop/onboarding) update logo size
  ui/app/AppLayouts/Onboarding/views/LoginView.qml
Labels: tested

#6764 fix(@desktop/wallet): Crash when staying on Advanced screen for ~30 minutes
  ui/app/AppLayouts/stores/RootStore.qml
  ui/imports/shared/popups/SendModal.qml
  ui/imports/shared/views/SendModalHeader.qml
Labels: tested

#6870 fix(CreateChatView): Move `ActivityCenterPopup` to appmain
  ui/app/AppLayouts/Chat/popups/ActivityCenterPopup.qml
  ui/app/AppLayouts/Chat/popups/qmldir
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/ChatColumnView.qml
  ui/app/AppLayouts/Chat/views/ChatView.qml
  ui/app/AppLayouts/Chat/views/CreateChatView.qml
  ui/app/mainui/AppMain.qml
  ui/imports/utils/Global.qml
Labels: tested

#6845 fix(ActivityCenter): Close activity center on click outside (via MouseArea)
  ui/app/AppLayouts/Chat/popups/ActivityCenterPopup.qml
Labels: tested

#6746 fix(AppSearch): Fix `forceActiveFocus` in StatusSearchPopup
  ui/app/mainui/AppSearch.qml
Labels: tested

#6847 fix(Communities): Fix membership requests popup
  ui/app/AppLayouts/Chat/popups/community/MembershipRequestsPopup.qml
Labels: tested

#6621 ci: Discord notification for master build failrues
  ci/Jenkinsfile.combined
Labels: ci

#6110 feat(CommunitySettings/Permissions): Community Permissions Settings UI - `Welcome` and `How holds` dropdown part
  src/app/global/local_account_sensitive_settings.nim
  ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml
  ui/app/AppLayouts/Chat/controls/community/TokensListDropdownContent.qml
  ui/app/AppLayouts/Chat/layouts/SettingsPageLayout.qml
  ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
  ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
  ui/app/AppLayouts/Chat/views/communities/CommunityWelcomePermissionsView.qml
  ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
  ui/app/AppLayouts/Profile/views/AdvancedView.qml
  ui/imports/assets/icons/add.svg
  ui/imports/assets/icons/condition-Or.svg
  ui/imports/assets/icons/contact_verified.svg
  ui/imports/assets/png/community/permissions21_3_1.png
  ui/imports/shared/panels/CurveSeparatorWithText.qml
  ui/imports/shared/panels/qmldir
Labels: Communities, tested, feature, priority F2: important, E:Communities

#6961 test(chat): Can do a mention in a chat
  .gitignore
  test/ui-test/src/drivers/SquishDriver.py
  test/ui-test/src/drivers/SquishDriverVerification.py
  test/ui-test/src/screens/SettingsScreen.py
  test/ui-test/src/screens/StatusChatScreen.py
  test/ui-test/testSuites/suite_status/shared/scripts/sections/chat_names.py
  test/ui-test/testSuites/suite_status/shared/steps/chatSteps.py
  test/ui-test/testSuites/suite_status/tst_ChatFlow/test.feature
  ui/app/AppLayouts/Chat/panels/SuggestionBoxPanel.qml
  ui/imports/shared/status/StatusChatInput.qml
  ui/imports/shared/views/ProfileView.qml
Labels: Chat, squish

#6992 fix(@desktop/wallet): add account - password checking adjusted
  ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml
  ui/app/AppLayouts/Wallet/stores/RootStore.qml
Labels: tested

#7010 test(community): add a test that creates a community category
  test/ui-test/src/screens/StatusCommunityScreen.py
  test/ui-test/testSuites/suite_status/shared/scripts/sections/community_names.py
  test/ui-test/testSuites/suite_status/shared/steps/communitySteps.py
  test/ui-test/testSuites/suite_status/tst_communityFlows/test.feature
  ui/app/AppLayouts/Chat/popups/community/CreateCategoryPopup.qml
Labels: needs-statusq

#7006 test(Settings/Language): Can change language
  test/ui-test/src/drivers/SquishDriver.py
  test/ui-test/src/drivers/SquishDriverVerification.py
  test/ui-test/src/screens/SettingsScreen.py
  test/ui-test/src/screens/StatusLanguageScreen.py
  test/ui-test/testSuites/suite_status/shared/scripts/sections/settings_names.py
  test/ui-test/testSuites/suite_status/shared/steps/settingsSteps.py
  test/ui-test/testSuites/suite_status/suite.conf
  test/ui-test/testSuites/suite_status/tst_languageSettings/test.feature
  test/ui-test/testSuites/suite_status/tst_languageSettings/test.py
  ui/app/AppLayouts/Profile/panels/MenuPanel.qml
  ui/app/AppLayouts/Profile/views/LanguageView.qml
Labels: squish, Settings

#6707 feat: add store nodes
  src/app/modules/main/profile_section/sync/view.nim
  ui/app/AppLayouts/Profile/ProfileLayout.qml
  ui/app/AppLayouts/Profile/popups/AddWakuNodeModal.qml
  ui/app/AppLayouts/Profile/popups/WakuNodesModal.qml
  ui/app/AppLayouts/Profile/views/MessagingView.qml
Labels: tested

#7043 fix(@desktop/chat): GIF selector UI adjustments
  ui/imports/assets/icons/gifs-dark.svg
  ui/imports/assets/icons/gifs-light.svg
  ui/imports/shared/status/StatusChatInput.qml
  ui/imports/shared/status/StatusGifPopup.qml
Labels: tested

#7079 fix(@desktop/chat): adjust search member input
  ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml
Labels: tested

#7090 fix(StatusChatInput): infinite loop when pasting mention
  ui/imports/shared/status/StatusChatInput.qml
Labels: tested

#7082 fix(@desktop/wallet): adjust receive modal adress
  ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml
Labels: tested

#7113 fix(ContactRequests): Fix `sensor.onClicked` to `onClicked`
  ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
  ui/app/AppLayouts/Profile/views/MessagingView.qml
Labels: tested

#7039 feat(@desktop/keycard): initial UI for the keycard settings
  src/app/boot/app_controller.nim
  src/app/modules/main/module.nim
  src/app/modules/main/profile_section/io_interface.nim
  src/app/modules/main/profile_section/keycard/controller.nim
  src/app/modules/main/profile_section/keycard/io_interface.nim
  src/app/modules/main/profile_section/keycard/module.nim
  src/app/modules/main/profile_section/keycard/view.nim
  src/app/modules/main/profile_section/module.nim
  src/app/modules/main/profile_section/view.nim
  ui/app/AppLayouts/Profile/ProfileLayout.qml
  ui/app/AppLayouts/Profile/stores/KeycardStore.qml
  ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml
  ui/app/AppLayouts/Profile/views/KeycardView.qml
  ui/imports/assets/icons/keycard/security-keycard@2x.svg
  ui/imports/assets/png/keycard/security-keycard@2x.png
  ui/imports/utils/Constants.qml
Labels: tested

#7136 fix(StatusListItem): fix `sensor.onClicked` to `onClicked`
  ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupOverviewPanel.qml
  ui/app/AppLayouts/Chat/popups/community/CommunitiesPopup.qml
  ui/app/AppLayouts/Chat/popups/community/CreateCategoryPopup.qml
  ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
  ui/app/AppLayouts/Profile/popups/ExemptionNotificationsModal.qml
  ui/app/AppLayouts/Profile/popups/WakuNodesModal.qml
  ui/app/AppLayouts/Profile/views/MessagingView.qml
  ui/app/AppLayouts/Profile/views/NotificationsView.qml
  ui/app/AppLayouts/Profile/views/profile/MyProfileSettingsView.qml
  ui/imports/shared/controls/RadioButtonSelector.qml
Labels: tested

#6313 feat: output messages to csv
  .gitignore
  Makefile
  src/app_service/service/accounts/service.nim
Labels: tested

#7089 fix(@desktop/wallet): Search Bar missing in token selection popup
  src/app/modules/main/wallet_section/current_account/controller.nim
  src/app/modules/main/wallet_section/current_account/io_interface.nim
  src/app/modules/main/wallet_section/current_account/module.nim
  src/app/modules/main/wallet_section/current_account/view.nim
  src/app_service/service/token/service.nim
  src/app_service/service/wallet_account/service.nim
  ui/imports/shared/controls/AssetAndAmountInput.qml
  ui/imports/shared/panels/StatusAssetSelector.qml
  ui/imports/shared/popups/SendModal.qml
Labels: tested

#7111 fix(toast-notifications): Fix notifcations listview sizes
  ui/app/mainui/AppMain.qml
Labels: tested

#7056 fix(EmojiPopup): Fix emoji suggestions and add tests for it
  test/ui-test/src/screens/StatusChatScreen.py
  test/ui-test/testSuites/suite_status/shared/scripts/sections/chat_names.py
  test/ui-test/testSuites/suite_status/shared/steps/chatSteps.py
  test/ui-test/testSuites/suite_status/tst_ChatFlow/test.feature
  ui/imports/shared/status/StatusInputListPopup.qml
Labels: tested

#7149 fix(wallet-test): fix balance test
  test/ui-test/src/screens/SettingsScreen.py
  test/ui-test/src/screens/StatusMainScreen.py
  test/ui-test/src/screens/StatusWalletScreen.py
  ui/imports/shared/views/AssetsView.qml
Labels: tested

#6965 fix: change gateway
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.linux-cpp
  ci/Jenkinsfile.mac-cpp.todo
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.uitests
  ci/Jenkinsfile.windows
  ci/Jenkinsfile.windows-cpp.todo
  src/app/modules/main/activity_center/controller.nim
  src/app/modules/main/activity_center/module.nim
  src/app/modules/main/chat_section/chat_content/controller.nim
  src/app/modules/main/chat_section/chat_content/messages/controller.nim
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/main/chat_section/chat_content/module.nim
  src/app/modules/main/stickers/controller.nim
  src/app/modules/main/stickers/io_interface.nim
  src/app/modules/main/stickers/module.nim
  src/app/modules/main/stickers/view.nim
  src/app_service/service/eth/utils.nim
  src/app_service/service/message/dto/message.nim
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/ChatColumnView.qml
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/app/AppLayouts/Chat/views/CreateChatView.qml
  ui/imports/shared/status/StatusChatInput.qml
  ui/imports/shared/status/StatusStickerList.qml
  ui/imports/shared/status/StatusStickersPopup.qml
Labels: tested, waiting-for-status-go-merge

#7116 fix(@desktop/onboarding): Hide current account from accounts list
  ui/app/AppLayouts/Onboarding/panels/AccountMenuItemPanel.qml
  ui/app/AppLayouts/Onboarding/views/LoginView.qml
Labels: tested

#7125 fix(@desktop/community): add online status to invite modal
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/profile_section/contacts/controller.nim
  src/app/modules/main/profile_section/contacts/module.nim
  src/app/modules/shared_models/user_item.nim
  ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupInviteFriendsPanel.qml
  ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupInviteMessagePanel.qml
  ui/app/AppLayouts/Chat/popups/community/InviteFriendsToCommunityPopup.qml
  ui/imports/shared/views/ExistingContacts.qml
  ui/imports/shared/views/PickedContacts.qml
Labels: tested

#7199 fix(ChooseBrowserPopup): 'Choose browser' modal doesn't look good
  ui/app/AppLayouts/Chat/popups/ChooseBrowserPopup.qml
  ui/imports/assets/png/browser/chooseBrowserImage.png
  ui/imports/assets/png/browser/chooseBrowserImage@2x.png
Labels: tested
