Repository status-im/status-desktop, pull requests merged in 2022-01, with the labels that each got.

#4278 chore: use TrustedMailServers from NodeConfig in mailserver cycle for Waku V1
  src/app_service/tasks/marathon/mailserver/model.nim
Labels: tested

#4357 fix: Cannot download uploaded or embed images in private chat
  ui/imports/shared/views/chat/CompactMessageView.qml
Labels: tested

#4333 fix: make changing local nicknames of contacts work again
  src/app/chat/event_handling.nim
  src/app/chat/views/message_list.nim
  src/app/modules/main/profile_section/contacts/controller_interface.nim
  src/app/modules/main/profile_section/contacts/models/contact_list.nim
  src/app/modules/main/profile_section/contacts/module.nim
  src/app_service/service/contacts/service_interface.nim
Labels: tested

#4362 fix(@wallet): Collection without assets
  ui/app/AppLayouts/Wallet/views/collectibles/CollectibleCollectionView.qml
Labels: tested

#4378 fix(@onboarding): Add more height to the textarea
  ui/app/AppLayouts/Onboarding/popups/EnterSeedPhraseModal.qml
  ui/imports/shared/controls/SeedPhraseTextArea.qml
Labels: tested

#4402 fetch-brew-bottle.sh: don't hardcode macOS Mojave
  scripts/fetch-brew-bottle.sh
Labels: macos, ci, dependencies

#4398 fix(@desktop/wallet): Fix for - Recipient of the transaction message is not notified that transaction is completed
  ui/imports/shared/popups/SignTransactionModal.qml
  ui/imports/shared/views/chat/TransactionBubbleView.qml
Labels: testing

#4433 refactor(@desktop/chat): reading a channel message does not mark it as read
  src/app/modules/main/chat_section/chat_content/module.nim
  src/app/modules/main/chat_section/chat_content/private_interfaces/module_access_interface.nim
  src/app/modules/main/chat_section/chat_content/view.nim
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/model.nim
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim
  src/app/modules/main/chat_section/sub_model.nim
  src/app/modules/main/chat_section/view.nim
  src/app/modules/main/module.nim
  src/app/modules/main/private_interfaces/module_chat_section_delegate_interface.nim
  src/app/modules/shared_models/section_model.nim
  src/app_service/service/message/service.nim
Labels: tested

#4356 fix: The text entry box shouldn't highlight invalid @mentions
  ui/imports/shared/status/StatusChatInput.qml
Labels: tested

#4432 fix(chat): fix sticker button not showing + stickers not showing in chat
  src/app/modules/main/activity_center/controller.nim
  src/app/modules/main/activity_center/controller_interface.nim
  src/app/modules/main/activity_center/module.nim
  src/app/modules/main/chat_section/chat_content/controller.nim
  src/app/modules/main/chat_section/chat_content/controller_interface.nim
  src/app/modules/main/chat_section/chat_content/messages/controller.nim
  src/app/modules/main/chat_section/chat_content/messages/controller_interface.nim
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/main/chat_section/chat_content/module.nim
  src/app/modules/shared_models/message_item.nim
  src/app/modules/shared_models/message_item_qobject.nim
  src/app/modules/shared_models/message_model.nim
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
  ui/imports/shared/views/chat/CompactMessageView.qml
  ui/imports/shared/views/chat/MessageView.qml
  ui/imports/utils/Global.qml
Labels: tested

#4463 refactor(@desktop/chat): username is misplaced when sending messages in the channel
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/imports/shared/views/chat/CompactMessageView.qml
Labels: tested

#4461 fix(@desktop/chat): Group members list must show only 5
  ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml
Labels: bug, ui, Chat, low-priority

#4241 fix(PrivacyView): Fix relations between switches and line sensor and local settins
  src/app/chat/view.nim
  ui/app/AppLayouts/Profile/views/PrivacyView.qml
  ui/app/AppMain.qml
Labels: tested-issues

#4438 fix: restore community private key field content in dialog
  ui/app/AppLayouts/Chat/popups/community/CommunityProfilePopup.qml
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
  ui/app/AppLayouts/stores/RootStore.qml
Labels: tested

#4466 Fix/import communities modal
  ui/app/AppLayouts/Chat/popups/community/AccessExistingCommunityPopup.qml
Labels: tested

#4427 fix(chat): fix starting 1-1 chat because of ContactList signal bug
  ui/app/AppLayouts/Chat/popups/PrivateChatPopup.qml
  ui/imports/shared/controls/AddressInput.qml
  ui/imports/shared/controls/ContactsListAndSearch.qml
  ui/imports/shared/views/SearchResults.qml
Labels: tested

#4491 fix(@chat): Guarantee message uniqueness in list
  src/app/modules/shared_models/message_model.nim
Labels: tested

#4472 fix(@desktop/ProfilePopup): [base_bc] share profile url in profile modal is incorrect
  ui/app/AppMain.qml
  ui/imports/shared/popups/ProfilePopup.qml
Labels: bug, Profile, tested, branch: base_bc

#4496 fix(chat): fix copy and download image
  src/app/global/utils.nim
  ui/app/AppLayouts/Chat/ChatLayout.qml
  ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml
  ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/ChatColumnView.qml
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
  ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
  ui/imports/shared/views/chat/MessageContextMenuView.qml
Labels: tested

#4457 fix:activity center view is empty
  src/app/modules/shared_models/message_item_qobject.nim
  src/app_service/service/activity_center/dto/notification.nim
  ui/app/AppLayouts/Chat/ChatLayout.qml
  ui/app/AppLayouts/Chat/popups/ActivityCenterPopup.qml
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/ActivityCenterGroupRequest.qml
  ui/app/AppLayouts/Chat/views/ActivityCenterMessageComponentView.qml
  ui/app/AppLayouts/Chat/views/ChatColumnView.qml
Labels: testing

#4500 fix(chat): set 1-1 chat as active when already created
  src/app/modules/main/chat_section/module.nim
Labels: tested

#4480 fix(@communities/InviteFriends): [base_bc] invite friends button is misplaced
  ui/imports/shared/controls/ContactsListAndSearch.qml
Labels: bug, ui, Communities, branch: base_bc

#4487 fix(@desktop/community): added option to delete community channel
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/controller_interface.nim
  src/app/modules/main/chat_section/model.nim
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim
  src/app/modules/main/chat_section/sub_model.nim
  src/app/modules/main/chat_section/view.nim
  src/app_service/service/community/service.nim
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Labels: tested

#4513 fix(@communities): Disable create button on invalid form
  ui/app/AppLayouts/Chat/popups/community/CreateCommunityPopup.qml
Labels: tested

#3825 feat(ProfilePopup): Add avatar change functionality
  ui/app/AppLayouts/Chat/popups/ProfilePopup.qml
  ui/app/AppLayouts/Profile/ProfileLayout.qml
  ui/app/AppLayouts/stores/RootStore.qml
  ui/app/AppMain.qml
Labels: tested-issues

#4520 fix(@wallet): hide signing phrase accept
  ui/app/AppLayouts/Wallet/WalletLayout.qml
  ui/app/AppLayouts/Wallet/stores/RootStore.qml
Labels: tested

#4560 fix(@chat): react to on clear history
  src/app/modules/main/chat_section/chat_content/messages/controller.nim
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_view_delegate_interface.nim
  src/app/modules/shared_models/message_model.nim
Labels: tested

#4498 fix: display loading indicator depending on mailserver request status
  src/app/chat/event_handling.nim
  src/app/chat/signal_handling.nim
  src/app/chat/view.nim
  ui/app/AppLayouts/Chat/views/ChatColumnView.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: tested

#4554 fix(userlist): member added to userlist on approve and duplicate member
  src/app/modules/main/chat_section/chat_content/users/controller.nim
  src/app/modules/main/chat_section/chat_content/users/module.nim
  src/app_service/service/community/service.nim
Labels: tested

#4562 fix(@desktop/chat-messages): [base_bc] emojis alignment is wrong
  ui/imports/shared/views/chat/CompactMessageView.qml
Labels: tested

#4558 fix(@desktop/chat-messages): [base_bc] adding emoji to a message does not reflect on desktop
  src/app/modules/main/chat_section/chat_content/controller.nim
  src/app/modules/main/chat_section/chat_content/messages/controller.nim
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_controller_delegate_interface.nim
  src/app/modules/main/chat_section/chat_content/module.nim
  src/app/modules/main/chat_section/chat_content/private_interfaces/module_controller_delegate_interface.nim
  src/app/modules/shared_models/message_item.nim
  src/app/modules/shared_models/message_model.nim
  src/app/modules/shared_models/message_reaction_item.nim
  src/app/modules/shared_models/message_reaction_model.nim
  src/app_service/service/message/service.nim
Labels: tested

#4563 fix(@chat): react to on left chat
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/controller_interface.nim
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim
  src/app/modules/main/chat_section/private_interfaces/module_view_delegate_interface.nim
  src/app/modules/main/chat_section/view.nim
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml
  ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
  ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
Labels: tested

#4536 fix(@wallet): receive modal
  ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml
  ui/app/AppLayouts/Wallet/stores/RootStore.qml
  ui/imports/shared/controls/Input.qml
  ui/imports/shared/stores/RootStore.qml
Labels: tested

#4580 fix(community/section): fix new community order in the sections
  src/app/modules/main/module.nim
  src/app/modules/main/view.nim
  src/app/modules/shared_models/section_model.nim
Labels: tested

#4581 fix(communities): fix icon, members and color + set observed and active
  ui/app/AppLayouts/Chat/popups/community/CommunitiesPopup.qml
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
  ui/app/AppLayouts/stores/RootStore.qml
Labels: tested

#4582 fix(groups): Hide unchecked users in group creation popup
  ui/app/AppLayouts/Chat/panels/ContactListPanel.qml
Labels: tested

#4583 fix(groups): Update group info user list
  ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml
Labels: tested

#4584 fix(@desktop/chat-content): [base_bc] can't select a community channel
  src/app/modules/main/chat_section/chat_content/controller.nim
  src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_access_interface.nim
  src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_controller_delegate_interface.nim
  src/app/modules/main/chat_section/controller.nim
  src/app_service/service/community/service.nim
Labels: tested

#4594 fix(image-modal): fix having to click multiple times to close the image
  ui/app/AppLayouts/Chat/views/ChatColumnView.qml
  ui/app/AppMain.qml
Labels: testing

#4603 Fix/issue 4524: [base_bc] selecting a channel does not auto-focus on the text input field
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/imports/shared/status/StatusChatInput.qml
Labels: bug, Chat, branch: base_bc

#4624 fix(@chat): display message with link
  src/app_service/service/message/dto/message.nim
  src/app_service/service/message/service.nim
Labels: tested

#4625 fix(@desktop/browser): [base_bc] permissions modal looks off in dark mode
  ui/app/AppLayouts/Browser/popups/BrowserConnectionModal.qml
Labels: bug, Browser, tested, branch: base_bc

#4618 fix(@desktop/CopyToClipboard): [base_bc] can't copy from Invite friends as well as App Version and Node Version
  ui/app/AppLayouts/Chat/panels/EmptyChatPanel.qml
  ui/app/AppLayouts/Chat/panels/EmptyViewPanel.qml
  ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupInviteFriendsPanel.qml
  ui/app/AppLayouts/Chat/popups/PrivateChatPopup.qml
  ui/app/AppLayouts/Chat/views/ChatColumnView.qml
  ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
  ui/app/AppLayouts/Profile/ProfileLayout.qml
  ui/app/AppLayouts/Profile/views/AboutView.qml
  ui/imports/shared/controls/ContactsListAndSearch.qml
  ui/imports/shared/controls/CopyToClipBoardButton.qml
  ui/imports/shared/popups/InviteFriendsPopup.qml
  ui/imports/shared/status/StatusSectionDescItem.qml
  ui/imports/shared/views/NoFriendsRectangle.qml
  ui/imports/utils/Constants.qml
Labels: bug, tested, branch: base_bc

#4633 fix(@wallet): Show token modal
  ui/app/AppLayouts/Wallet/panels/TokenSettingsModalContent.qml
  ui/app/AppLayouts/Wallet/panels/WalletHeader.qml
  ui/app/AppLayouts/Wallet/popups/AddShowTokenModal.qml
  ui/app/AppLayouts/Wallet/popups/TokenSettingsModal.qml
Labels: tested

#4637 fix(groups): Add popup to view group context menu action
  ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
  ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
Labels: tested

#4638 fix(@desktop/wallet): [base_bc] can't copy wallet address
  ui/app/AppLayouts/Wallet/WalletLayout.qml
  ui/app/AppLayouts/Wallet/panels/WalletHeader.qml
  ui/app/AppLayouts/Wallet/views/RightTabView.qml
  ui/app/AppLayouts/WalletV2/WalletV2Layout.qml
  ui/app/AppLayouts/WalletV2/panels/WalletHeaderPanel.qml
  ui/app/AppMain.qml
  ui/imports/shared/status/StatusExpandableAddress.qml
Labels: bug, Wallet, tested, branch: base_bc

#4632 fix(@desktop/browser): [base_bc] renaming bookmark is not persistent
  src/app_service/service/bookmarks/service.nim
  ui/app/AppLayouts/Browser/popups/FavoriteMenu.qml
Labels: bug, Browser, tested, branch: base_bc
