Repository status-im/status-desktop, pull requests merged in 2022-10, with the labels that each got.

#7720 fix(StatusSearchPopup): images in search results are broken
  ui/StatusQ/src/StatusQ/Popups/StatusSearchPopup.qml
Labels: tested, 0.7.0.rc

#7721 fix(ChatMessageView): delayed binding for proper msg height calculation
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
Labels: tested, 0.7.0, 0.7.0.rc

#7722 fix(Community): big space in invite friends popup
  ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupInviteFriendsPanel.qml
Labels: tested, 0.7.0.rc

#7725 fix: Reply to sticker adds message advising user to upgrade
  ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageReply.qml
Labels: tested, 0.7.0.rc

#7693 test(suite_communities): Create new test suite `suite_communities` and reorganize existing test cases
  test/ui-test/testSuites/suite_communities/shared/scripts/community_names.py
  test/ui-test/testSuites/suite_communities/shared/scripts/community_portal_names.py
  test/ui-test/testSuites/suite_communities/shared/scripts/names.py
  test/ui-test/testSuites/suite_communities/shared/scripts/search_names.py
  test/ui-test/testSuites/suite_communities/shared/steps/communitySteps.py
  test/ui-test/testSuites/suite_communities/shared/steps/searchSteps.py
  test/ui-test/testSuites/suite_communities/suite.conf
  test/ui-test/testSuites/suite_communities/tst_communityFlows/test.feature
  test/ui-test/testSuites/suite_communities/tst_communityFlows/test.py
  test/ui-test/testSuites/suite_communities/tst_communityMessageFlows/test.feature
  test/ui-test/testSuites/suite_communities/tst_communityMessageFlows/test.py
  test/ui-test/testSuites/suite_communities/tst_searchFlows/test.feature
  test/ui-test/testSuites/suite_communities/tst_searchFlows/test.py
  test/ui-test/testSuites/suite_onboarding/suite.conf
  test/ui-test/testSuites/suite_status/shared/scripts/names.py
  test/ui-test/testSuites/suite_status/shared/steps/walletSteps.py
  test/ui-test/testSuites/suite_status/suite.conf
Labels: refactor, priority F2: important, squish

#7694 test(suite_settings): Create new test suite `suite_settings` and reorganize existing test cases
  test/ui-test/testSuites/suite_settings/shared/scripts/names.py
  test/ui-test/testSuites/suite_settings/suite.conf
  test/ui-test/testSuites/suite_settings/tst_languageSettings/test.feature
  test/ui-test/testSuites/suite_settings/tst_languageSettings/test.py
  test/ui-test/testSuites/suite_settings/tst_settingsMenu/test.feature
  test/ui-test/testSuites/suite_settings/tst_settingsMenu/test.py
  test/ui-test/testSuites/suite_settings/tst_userIdentity/test.feature
  test/ui-test/testSuites/suite_settings/tst_userIdentity/test.py
  test/ui-test/testSuites/suite_status/suite.conf
Labels: refactor, priority F2: important, squish

#7695 test(suite_wallet): Create new test suite suite_wallet and reorganize existing test cases
  test/ui-test/testSuites/global_shared/scripts/debug_helpers.py
  test/ui-test/testSuites/suite_wallet/data/wallet-user1.png
  test/ui-test/testSuites/suite_wallet/shared/scripts/names.py
  test/ui-test/testSuites/suite_wallet/shared/scripts/wallet_names.py
  test/ui-test/testSuites/suite_wallet/shared/steps/walletSteps.py
  test/ui-test/testSuites/suite_wallet/suite.conf
  test/ui-test/testSuites/suite_wallet/tst_transaction/test.feature
  test/ui-test/testSuites/suite_wallet/tst_transaction/test.py
  test/ui-test/testSuites/suite_wallet/tst_wallet/config.xml
  test/ui-test/testSuites/suite_wallet/tst_wallet/test.feature
  test/ui-test/testSuites/suite_wallet/tst_wallet/test.py
  test/ui-test/testSuites/suite_wallet/tst_wallet/verificationPoints/can_see_collectibles_for_an_account/when_the_user_accepts_the_signing_phrase_YugaLabs_0xA858DDc0445d8131daC4d1DE01f834ffcbA52Ef1
  test/ui-test/testSuites/suite_wallet/tst_wallet/verificationPoints/user_adds_a_watch_only_account/when_the_user_accepts_the_signing_phrase_one_0x8397bc3c5a60a1883174f722403d63a8833312b7
  test/ui-test/testSuites/suite_wallet/tst_wallet/verificationPoints/user_adds_a_watch_only_account/when_the_user_accepts_the_signing_phrase_two_0xf51ba8631618b9b3521ff4eb9adfd8a837455226
  test/ui-test/testSuites/suite_wallet/tst_wallet/verificationPoints/user_can_toggle_network_and_see_balances/and_the_user_opens_wallet_screen_one_0x5fFa75CE51c3a7ebE23BdE37b5E3A0143DfBceE0
Labels: refactor, priority F2: important, squish

#7716 fix(@desktop/chat): Fix sending request to ens account - MASTER
  ui/app/AppLayouts/Profile/popups/SendContactRequestModal.qml
Labels: 0.7.0.rc

#7746 fix(Fleet): Change default fleet to status.prod
  src/app_service/service/accounts/service.nim
  src/app_service/service/settings/service.nim
Labels: 0.7.0.rc

#7719 fix(ChatMessagesView): Loading spinner and scroll to bottom button overlap
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/imports/shared/status/StatusChatInput.qml
  ui/imports/shared/status/StatusChatInputReplyArea.qml
Labels: tested, 0.7.0.rc

#7758 fix(StatusChatInput): Move formatting menu from scroll
  ui/imports/shared/status/StatusChatInput.qml
Labels: 0.7.0.rc

#7095 feat(CreateCommunityPopup): add discord import progress panel and discord message handling
  src/app/core/signals/remote_signals/community.nim
  src/app/core/signals/remote_signals/signal_type.nim
  src/app/core/signals/signals_manager.nim
  src/app/modules/main/activity_center/module.nim
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/main/chat_section/chat_content/module.nim
  src/app/modules/main/communities/controller.nim
  src/app/modules/main/communities/io_interface.nim
  src/app/modules/main/communities/models/discord_import_error_item.nim
  src/app/modules/main/communities/models/discord_import_errors_model.nim
  src/app/modules/main/communities/models/discord_import_progress_item.nim
  src/app/modules/main/communities/models/discord_import_task_item.nim
  src/app/modules/main/communities/models/discord_import_tasks_model.nim
  src/app/modules/main/communities/module.nim
  src/app/modules/main/communities/view.nim
  src/app/modules/shared_models/discord_message_item.nim
  src/app/modules/shared_models/message_item.nim
  src/app/modules/shared_models/message_model.nim
  src/app_service/common/types.nim
  src/app_service/service/community/dto/community.nim
  src/app_service/service/community/service.nim
  src/app_service/service/message/dto/message.nim
  src/app_service/service/message/service.nim
  src/backend/communities.nim
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml
  ui/app/AppLayouts/CommunitiesPortal/popups/CreateCommunityPopup.qml
  ui/app/AppLayouts/CommunitiesPortal/popups/DiscordImportProgressContents.qml
  ui/app/AppLayouts/CommunitiesPortal/popups/DiscordImportProgressDialog.qml
  ui/app/AppLayouts/CommunitiesPortal/stores/CommunitiesStore.qml
  ui/app/mainui/AppMain.qml
  ui/imports/shared/controls/chat/UserImage.qml
  ui/imports/shared/controls/chat/UsernameLabel.qml
  ui/imports/shared/panels/CommunityBanner.qml
  ui/imports/shared/panels/ModuleWarning.qml
  ui/imports/shared/popups/ConfirmationDialog.qml
  ui/imports/shared/views/chat/MessageView.qml
  ui/imports/utils/Constants.qml
Labels: tested, waiting-for-status-go-merge

#7762 fix(Community/Settings): Second Nav of community differs from the Design
  ui/StatusQ/src/StatusQ/Layout/StatusSectionLayout.qml
  ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
  ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
Labels: ui, Communities, E:Bugfixes, pixel-perfect-issues

#7669 fix(@desktop/chat): update toast message logic
  src/app/modules/main/ephemeral_notification_item.nim
  src/app/modules/main/ephemeral_notification_model.nim
  ui/app/mainui/AppMain.qml
Labels: tested

#7761 fix(SearchPopup): displaying community channel's emojis
  src/app/modules/main/app_search/module.nim
  ui/StatusQ/sandbox/controls/ListItems.qml
  ui/StatusQ/src/StatusQ/Components/StatusEmoji.qml
  ui/StatusQ/src/StatusQ/Components/StatusSmartIdenticon.qml
  ui/StatusQ/src/StatusQ/Popups/StatusMenuItemDelegate.qml
  ui/StatusQ/src/StatusQ/Popups/StatusSearchLocationMenu.qml
  ui/StatusQ/src/StatusQ/Popups/StatusSearchPopupMenuItem.qml
Labels: tested

#7640 fix(Invitation+LinksBubble): fixed button radius corners
  ui/imports/shared/views/chat/InvitationBubbleView.qml
  ui/imports/shared/views/chat/LinksMessageView.qml
Labels: tested

#7794 Fix(Communities): Change cursor shape on hovering ColorPicker
  ui/StatusQ/src/StatusQ/Components/StatusColorSpace.qml
  ui/StatusQ/src/StatusQ/Controls/StatusColorRadioButton.qml
Labels: tested

#7822 fix(Language): App crashes when language is changed
  src/app_service/service/language/service.nim
  ui/app/AppLayouts/Profile/views/LanguageView.qml
Labels: waiting-for-status-lib-merge, E:Bugfixes

#7824 Fix(Communities): Fix cropped list in invite users to community popup
  ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupInviteFriendsPanel.qml
Labels: tested

#7773 fix(Wallet): allow to edit name and color for a new account without authentication
  src/app/modules/main/wallet_section/accounts/module.nim
  src/app/modules/main/wallet_section/accounts/view.nim
  ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml
Labels: tested

#7835 fix(Chat/CommunityColumn): Create new chat button looks inconsistent across views
  ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
  ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
Labels: Chat, Communities, E:Bugfixes, pixel-perfect-issues

#7764 fix(StatusChatListItem): fix online status badge hover color
  ui/StatusQ/src/StatusQ/Components/StatusChatListItem.qml
Labels: tested

#7821 fix(replies): Fire dataChanged when contact changed in reply
  src/app/modules/shared_models/message_model.nim
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/imports/shared/views/chat/MessageView.qml
  ui/imports/utils/Constants.qml
Labels: testing

#7888 fix(signals_manager): ensure `savedAddresses` event has `JNull` check
  src/app/core/signals/remote_signals/messages.nim
Labels: tested

#7860 fix(Onboarding): Give consistency to Create / Confirm password view font-size
  test/ui-test/src/screens/SettingsScreen.py
  test/ui-test/src/screens/StatusMainScreen.py
  test/ui-test/testSuites/global_shared/scripts/onboarding_names.py
  test/ui-test/testSuites/global_shared/scripts/settings_names.py
  test/ui-test/testSuites/suite_communities/tst_communityFlows/test.feature
  test/ui-test/testSuites/suite_messaging/tst_groupChat/test.feature
  test/ui-test/testSuites/suite_onboarding/shared/verificationPoints/VP-PWStrength-lower_very_weak
  test/ui-test/testSuites/suite_onboarding/shared/verificationPoints/VP-PWStrength-numbers_symbols_lower_so-so
  test/ui-test/testSuites/suite_onboarding/shared/verificationPoints/VP-PWStrength-numbers_symbols_lower_upper_good
  test/ui-test/testSuites/suite_onboarding/shared/verificationPoints/VP-PWStrength-numbers_symbols_lower_upper_great
  test/ui-test/testSuites/suite_onboarding/shared/verificationPoints/VP-PWStrength-numbers_symbols_weak
  test/ui-test/testSuites/suite_onboarding/shared/verificationPoints/VP-PWStrength-numbers_very_weak
  test/ui-test/testSuites/suite_onboarding/shared/verificationPoints/VP-PWStrength-symbols_very_weak
  test/ui-test/testSuites/suite_onboarding/shared/verificationPoints/VP-PWStrength-upper_very_weak
  ui/app/AppLayouts/Onboarding/views/ConfirmPasswordView.qml
  ui/app/AppLayouts/Onboarding/views/CreatePasswordView.qml
  ui/app/AppLayouts/Profile/popups/ChangePasswordModal.qml
  ui/imports/shared/views/PasswordView.qml
Labels: ui, onboarding, E:Bugfixes, pixel-perfect-issues

#7863 feat(@desktop/keycard): rename keycard
  src/app/modules/main/profile_section/keycard/controller.nim
  src/app/modules/main/profile_section/keycard/io_interface.nim
  src/app/modules/main/profile_section/keycard/module.nim
  src/app/modules/main/profile_section/keycard/view.nim
  src/app/modules/shared_modules/keycard_popup/controller.nim
  src/app/modules/shared_modules/keycard_popup/internal/enter_keycard_name_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/enter_pin_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/keycard_empty_metadata_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/keycard_empty_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/keycard_inserted_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/keycard_metadata_display_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/keycard_rename_failure_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/keycard_rename_success_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/max_pairing_slots_reached_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/max_pin_retries_reached_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/max_puk_retries_reached_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/not_keycard_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/pin_verified_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/plugin_reader_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/reading_keycard_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/recognized_keycard_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/renaming_keycard_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/state.nim
  src/app/modules/shared_modules/keycard_popup/internal/state_factory.nim
  src/app/modules/shared_modules/keycard_popup/internal/wrong_keycard_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/wrong_pin_state.nim
  src/app/modules/shared_modules/keycard_popup/io_interface.nim
  src/app/modules/shared_modules/keycard_popup/models/key_pair_selected_item.nim
  src/app/modules/shared_modules/keycard_popup/models/keycard_model.nim
  src/app/modules/shared_modules/keycard_popup/module.nim
  src/app/modules/shared_modules/keycard_popup/view.nim
  src/app_service/service/keycard/service.nim
  src/app_service/service/wallet_account/service.nim
  ui/app/AppLayouts/Profile/stores/KeycardStore.qml
  ui/app/AppLayouts/Profile/views/keycard/DetailsView.qml
  ui/imports/shared/popups/keycard/KeycardPopup.qml
  ui/imports/shared/popups/keycard/helpers/KeyPairItem.qml
  ui/imports/shared/popups/keycard/helpers/KeycardItem.qml
  ui/imports/shared/popups/keycard/states/EnterName.qml
  ui/imports/shared/popups/keycard/states/KeycardInit.qml
  ui/imports/utils/Constants.qml
Labels: tested

#7599 feat(@desktop/wallet): Create API to retrieve historical price for a token
  src/app/modules/main/wallet_section/all_tokens/controller.nim
  src/app/modules/main/wallet_section/all_tokens/io_interface.nim
  src/app/modules/main/wallet_section/all_tokens/module.nim
  src/app/modules/main/wallet_section/all_tokens/view.nim
  src/app_service/service/token/async_tasks.nim
  src/app_service/service/token/dto.nim
  src/app_service/service/token/service.nim
  src/backend/backend.nim
  ui/StatusQ/src/StatusQ/Components/StatusChartPanel.qml
  ui/app/AppLayouts/Wallet/views/RightTabView.qml
  ui/imports/shared/stores/RootStore.qml
  ui/imports/shared/stores/TokenMarketValuesStore.qml
  ui/imports/shared/views/AssetsDetailView.qml
  ui/imports/shared/views/AssetsView.qml
  ui/imports/shared/views/TransactionDetailView.qml
  ui/imports/utils/Utils.qml
Labels: tested, needs-status-go

#7902 fix(@desktop/keycard): clicking `Get Keycard` button should direct to purchase page
  ui/app/AppLayouts/Profile/views/KeycardView.qml
  ui/imports/utils/Constants.qml
Labels: tested

#7900 fix(@desktop/keycard): keypair is not registered for newly created keycard users
  src/app/boot/app_controller.nim
  src/app/modules/startup/controller.nim
  src/app/modules/startup/io_interface.nim
  src/app/modules/startup/module.nim
  ui/imports/shared/popups/keycard/helpers/KeyPairItem.qml
  ui/imports/shared/popups/keycard/helpers/KeyPairUnknownItem.qml
  ui/imports/shared/popups/keycard/helpers/KeycardItem.qml
Labels: tested

#7817 fix(MessageView): Changed visual borders of message
  ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: tested

#7925 fix(@desktop/general): Fix community deep links
  src/app/core/custom_urls/urls_manager.nim
  src/app/global/app_signals.nim
  src/app/modules/main/controller.nim
  src/app/modules/main/io_interface.nim
  src/app/modules/main/module.nim
Labels: tested

#7958 fix(BackUpSeed): Confirm # word input had no focus
  ui/app/AppLayouts/Profile/popups/BackupSeedModal.qml
  ui/app/AppLayouts/Profile/popups/backupseed/BackupSeedStepBase.qml
Labels: bug

#7979 fix(@desktop/general): Fix clicking deep links in chat
  src/app/boot/app_controller.nim
  src/app/core/custom_urls/urls_manager.nim
  src/app/core/main.nim
  src/app/modules/main/io_interface.nim
  src/app/modules/main/module.nim
  src/app/modules/main/view.nim
  src/nim_status_client.nim
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/imports/shared/views/chat/LinksMessageView.qml
  ui/imports/shared/views/chat/MessageView.qml
  ui/imports/utils/Constants.qml
Labels: tested

#7748 fix(AppMain): only show banner when disconnected
  ui/app/mainui/AppMain.qml
Labels: tested, 0.8.0

#7281 feat(Communities): Add checking access type in Welcome modal
  ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
  ui/imports/shared/popups/CommunityIntroDialog.qml
Labels: 0.8.0

#7264 feat(Communities): Add ephemerial notification when request to join was accepted
  src/app/modules/main/module.nim
Labels: 0.8.0
