Repository status-im/status-desktop, pull requests merged in 2022-04, with the labels that each got.

#5058 feat(onboarding): Adding import seed screens for old&new users
  ui/app/AppLayouts/Onboarding/OnboardingLayout.qml
  ui/app/AppLayouts/Onboarding/controls/OnboardingBasePage.qml
  ui/app/AppLayouts/Onboarding/popups/ConfirmAddExistingKeyModal.qml
  ui/app/AppLayouts/Onboarding/popups/EnterSeedPhraseModal.qml
  ui/app/AppLayouts/Onboarding/popups/GenKeyModal.qml
  ui/app/AppLayouts/Onboarding/popups/InvalidSeedPhraseModal.qml
  ui/app/AppLayouts/Onboarding/popups/MnemonicRecoverySuccessModal.qml
  ui/app/AppLayouts/Onboarding/popups/SelectAnotherAccountModal.qml
  ui/app/AppLayouts/Onboarding/stores/BIP39_en.qml
  ui/app/AppLayouts/Onboarding/stores/OnboardingStore.qml
  ui/app/AppLayouts/Onboarding/stores/english.txt
  ui/app/AppLayouts/Onboarding/views/ConfirmPasswordView.qml
  ui/app/AppLayouts/Onboarding/views/CreatePasswordView.qml
  ui/app/AppLayouts/Onboarding/views/ExistingKeyView.qml
  ui/app/AppLayouts/Onboarding/views/GenKeyView.qml
  ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
  ui/app/AppLayouts/Onboarding/views/KeysMainView.qml
  ui/app/AppLayouts/Onboarding/views/LoginView.qml
  ui/app/AppLayouts/Onboarding/views/SeedPhraseInputView.qml
  ui/generate-rcc.go
Labels: onboarding, testing, tested-issues

#5248 fix(@browser): move post message async
  src/app/boot/app_controller.nim
  src/app/modules/main/browser_section/module.nim
  src/app/modules/main/browser_section/provider/controller.nim
  src/app/modules/main/browser_section/provider/io_interface.nim
  src/app/modules/main/browser_section/provider/module.nim
  src/app/modules/main/browser_section/provider/view.nim
  src/app_service/service/about/async_tasks.nim
  src/app_service/service/provider/async_tasks.nim
  src/app_service/service/provider/service.nim
  ui/app/AppLayouts/Browser/popups/BrowserConnectionModal.qml
  ui/app/AppLayouts/Browser/views/WebProviderObj.qml
Labels: tested

#5250 fix(change_pasword): Add error message to change password popup
  src/app/modules/main/profile_section/privacy/controller.nim
  src/app/modules/main/profile_section/privacy/io_interface.nim
  src/app/modules/main/profile_section/privacy/module.nim
  src/app/modules/main/profile_section/privacy/view.nim
  src/app_service/service/privacy/service.nim
  ui/app/AppLayouts/Profile/popups/ChangePasswordModal.qml
Labels: tested

#5367 fix(@wallet): Show error message when token is not found
  ui/imports/shared/views/chat/TransactionBubbleView.qml
Labels: tested

#5366 fix(@wallet): estimate gas fail when not enough fund
  src/app/modules/main/wallet_section/transactions/view.nim
  src/app_service/service/transaction/service.nim
Labels: tested

#5373 fix(Profile): Bringing back theme assets
  ui/imports/assets/icons/appearance-normal-dark.svg
  ui/imports/assets/icons/appearance-normal-light.svg
  ui/imports/assets/icons/appearance-normal-system.svg
Labels: tested

#5371 fix(@desktop/settings): copy correct chat key in profile view
  ui/app/AppLayouts/Profile/views/MyProfileView.qml
Labels: tested

#5370 fix(@desktop/browser): Unable to sign message from simepledapp.eth
  src/app_service/service/provider/async_tasks.nim
  ui/app/AppLayouts/Browser/views/WebProviderObj.qml
  ui/imports/utils/Utils.qml
Labels: tested

#5389 fix(@onboarding): Allow to enter last word in seed phrase import
  ui/app/AppLayouts/Onboarding/views/SeedPhraseInputView.qml
Labels: tested

#5372 fix(@desktop/communities): Remove sending invites when user select members for inviting to community
  ui/app/AppLayouts/Chat/popups/community/InviteFriendsToCommunityPopup.qml
Labels: tested

#5395 fix(@desktop/chat): search triggered from within community doesn't seem to preset the right search location
  ui/app/AppLayouts/stores/AppSearchStore.qml
Labels: tested

#5412 fix(@desktop/wallet): Allow entering private keys with and without 0x prefix
  ui/app/AppLayouts/Wallet/views/AdvancedAddAccountView.qml
Labels: tested

#5448 fix(@desktop/wallet): To field is not showing address in wallet
  ui/imports/shared/views/SendModalHeader.qml
Labels: tested

#5450 fix(@wallet): hide use 24 word button
  ui/app/AppLayouts/Wallet/views/AdvancedAddAccountView.qml
Labels: tested

#5483 fix(onboarding): Image missing in some onboarding screens
  ui/app/AppLayouts/Onboarding/views/KeysMainView.qml
  ui/imports/assets/png/onboarding/keys.png
Labels: bug, E:Onboarding, E:Bugfixes

#5489 fix(Chat/Stickers): Recent stickers icon is missing
  ui/imports/shared/status/StatusStickersPopup.qml
Labels: bug, Chat, E:Bugfixes

#5480 feat(@desktop/wallet): re-add adding watch only address to wallet
  ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml
  ui/app/AppLayouts/Wallet/views/AdvancedAddAccountView.qml
Labels: tested-issues

#5428 fix(Onboarding): display name clear button was always visible
  ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
Labels: testing

#5411 fix(@desktop/activity-center): mentions and replies in the activity centre does not display community icon
  src/app/modules/main/activity_center/controller.nim
  src/app/modules/main/activity_center/io_interface.nim
  src/app/modules/main/activity_center/module.nim
  src/app/modules/main/activity_center/view.nim
  ui/app/AppLayouts/Chat/controls/activityCenter/ChannelBadge.qml
  ui/app/AppLayouts/Chat/controls/activityCenter/CommunityBadge.qml
  ui/app/AppLayouts/Chat/panels/ActivityChannelBadgePanel.qml
  ui/app/AppLayouts/Chat/popups/ActivityCenterPopup.qml
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/ActivityCenterMessageComponentView.qml
  ui/imports/shared/views/chat/CompactMessageView.qml
Labels: tested

#5499 re-disable wallet & browser by default
  src/app/global/local_account_sensitive_settings.nim
Labels: tested

#5479 fix(@desktop/groups): view group modal member list is missing identicon for self
  ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml
Labels: testing

#5341 fix(wallet-emoji): fix wallet emoji save by only saving the utf char
  ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml
  ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml
Labels: tested

#5500 fix(Chat/ActivityCenter): Activity center context menu keeps moving position
  ui/app/AppLayouts/Chat/panels/ActivityCenterPopupTopBarPanel.qml
Labels: bug, tested, Activity_center, E:Bugfixes

#5537 fix(@desktop/wallet): Can't add an address to saved addresses
  ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml
  ui/imports/shared/controls/AddressInput.qml
  ui/imports/shared/controls/ContactsListAndSearch.qml
  ui/imports/shared/controls/RecipientSelector.qml
  ui/imports/utils/Utils.qml
Labels: tested

#5509 fix(@wallet): hide password from add watch only
  ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml
Labels: tested

#5506 fix(@wallet): loading collectibles
  src/app/modules/main/wallet_section/collectibles/collectibles/view.nim
  ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
  ui/app/AppLayouts/Wallet/views/collectibles/CollectibleCollectionView.qml
Labels: tested

#5516 fix(act-center): fix changing section when clicking go to settings
  ui/app/AppLayouts/Chat/popups/ActivityCenterPopup.qml
Labels: tested

#5560 ci: remove caching of dependencies
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.windows
Labels: ci

#5538 fix(ImportCommunity): Fix menu width
  ui/app/AppLayouts/Chat/popups/community/CommunitiesPopup.qml
Labels: tested

#5536 fix(Settings): Fix wallet scroll sizes
  ui/app/AppLayouts/Profile/views/WalletView.qml
Labels: tested

#5535 fix(Chat): Add emoji popup to edit message input
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/imports/shared/views/chat/CompactMessageView.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: tested

#5576 fix(@wallet): Token not displayed after upgrade
  src/app_service/common/network_constants.nim
  src/app_service/service/accounts/service.nim
Labels: tested

#5578 fix(CommunityPopup): Fix copy to clipboard
  ui/app/AppLayouts/Chat/popups/community/CommunityProfilePopup.qml
Labels: tested

#5580 feat(@wallet): prevent to duplicate token
  src/app/modules/main/wallet_section/all_tokens/controller.nim
  src/app/modules/main/wallet_section/all_tokens/io_interface.nim
  src/app/modules/main/wallet_section/all_tokens/module.nim
  src/app/modules/main/wallet_section/all_tokens/view.nim
  src/app_service/service/token/service.nim
Labels: tested

#5481 feat(@chat): disable tx in chat when no wallet
  ui/imports/shared/popups/ChatCommandsPopup.qml
  ui/imports/shared/status/StatusChatInput.qml
Labels: tested

#5579 fix(@settings): fix Gas selector for snt
  src/app_service/service/ens/service.nim
  ui/app/AppLayouts/Chat/stores/qmldir
  ui/app/AppLayouts/Profile/ProfileLayout.qml
  ui/app/AppLayouts/Profile/stores/EnsUsernamesStore.qml
  ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml
  ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml
  ui/app/AppLayouts/Profile/views/EnsView.qml
  ui/imports/shared/status/StatusETHTransactionModal.qml
Labels: tested

#5581 fix(@wallet): Hide ens settings section if no wallet
  ui/app/AppLayouts/Profile/panels/MenuPanel.qml
  ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml
Labels: tested
