Repository status-im/status-desktop, pull requests merged in 2022-11, with the labels that each got.

#8134 ci: lock windows Go version at 1.18.8
  scripts/windows_build_setup.ps1
Labels: ci

#8159 Makefile: move QT dir check to separate target
  Makefile
Labels: ci

#7749 fix: display "Resend" for expired messages
  src/app/modules/main/chat_section/chat_content/messages/controller.nim
  src/app/modules/main/chat_section/chat_content/messages/io_interface.nim
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/shared_models/message_model.nim
  src/app_service/service/message/dto/message.nim
  src/app_service/service/message/service.nim
  ui/imports/shared/views/chat/MessageView.qml
Labels: tested

#7999 feat(communities): User is able to cancel membership request
  src/app/modules/main/communities/controller.nim
  src/app/modules/main/communities/io_interface.nim
  src/app/modules/main/communities/module.nim
  src/app/modules/main/communities/view.nim
  src/app_service/service/community/dto/community.nim
  src/app_service/service/community/service.nim
  src/backend/communities.nim
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
  ui/imports/shared/popups/CommunityIntroDialog.qml
Labels: waiting-for-status-go-merge, 0.8.0

#8168 fix(edit-message): Add content-type to edit message request
  src/app/modules/main/chat_section/chat_content/messages/controller.nim
  src/app/modules/main/chat_section/chat_content/messages/io_interface.nim
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/main/chat_section/chat_content/messages/view.nim
  src/app_service/service/message/service.nim
  src/backend/messages.nim
  ui/app/AppLayouts/Chat/stores/MessageStore.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: tested

#8041 fix(contacts): retract the contact request when removing a contact
  src/app_service/service/contacts/service.nim
  src/backend/contacts.nim
Labels: tested

#8169 fix(profile-settings): Add usage dirty values for preview and load image profile on save
  src/app/modules/main/profile_section/profile/view.nim
  ui/StatusQ/src/StatusQ/Components/StatusSmartIdenticon.qml
  ui/StatusQ/src/StatusQ/Core/StatusAssetSettings.qml
  ui/app/AppLayouts/Profile/views/MyProfileView.qml
  ui/app/AppLayouts/Profile/views/profile/MyProfilePreview.qml
  ui/app/AppLayouts/Profile/views/profile/MyProfileSettingsView.qml
  ui/app/mainui/AppMain.qml
  ui/imports/shared/controls/chat/ProfileHeader.qml
  ui/imports/shared/controls/chat/UserImage.qml
  ui/imports/shared/popups/ImageCropWorkflow.qml
  ui/imports/shared/views/ProfileDialogView.qml
  ui/imports/utils/Global.qml
Labels: testing

#7668 fix(CreateChatView): fixed tagselector various issues
  ui/app/AppLayouts/Chat/panels/InlineSelectorPanel.qml
  ui/app/AppLayouts/Chat/views/CreateChatView.qml
  ui/app/AppLayouts/Chat/views/MembersEditSelectorView.qml
  ui/app/AppLayouts/Chat/views/MembersSelectorView.qml
  ui/app/AppLayouts/Chat/views/private/MembersSelectorBase.qml
Labels: bug, tested-issues

#8228 makefile: avoid rebuilds by using order-only deps
  Makefile
Labels: tested

#7747 fix(@desktop/chat): Fix moving channels between categories
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/io_interface.nim
  src/app/modules/main/chat_section/model.nim
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/chat_section/sub_item.nim
  src/app_service/service/community/service.nim
Labels: tested

#8208 fix:(@desktop/Profile): Preview Bio length and scroll area fix #7922
  ui/app/AppLayouts/Profile/views/MyProfileView.qml
  ui/imports/shared/panels/ProfileBioSocialsPanel.qml
Labels: tested

#8367 ci: improve clean-git by reseting submodules
  Makefile
Labels: ci

#8355 test(doc): Renamed file and added files flow diagram
  test/ui-test/README.md
  test/ui-test/doc/status_ui_test_app_architecture.drawio
  test/ui-test/doc/status_ui_test_app_architecture.jpg
  test/ui-test/doc/status_ui_test_app_files_diagram.drawio
  test/ui-test/doc/status_ui_test_app_files_diagram.jpg
  test/ui-test/src/processes/StatusLoginProcess.py
  test/ui-test/src/processes/StatusProcess.py
  test/ui-test/src/processes/__init__.py
  test/ui-test/testSuites/global_shared/scripts/bdd_hooks.py
  test/ui-test/testSuites/global_shared/steps/commonInitSteps.py
  test/ui-test/testSuites/global_shared/steps/settingsSteps.py
  test/ui-test/testSuites/global_shared/steps/steps.py
  test/ui-test/testSuites/suite_communities/shared/steps/communitySteps.py
  test/ui-test/testSuites/suite_communities/tst_communityFlows/bdd_hooks.py
  test/ui-test/testSuites/suite_communities/tst_communityMessageFlows/bdd_hooks.py
  test/ui-test/testSuites/suite_communities/tst_searchFlows/bdd_hooks.py
  test/ui-test/testSuites/suite_messaging/config.xml
  test/ui-test/testSuites/suite_messaging/shared/steps/chatSteps.py
  test/ui-test/testSuites/suite_messaging/tst_OneToOneChatFlow/bdd_hooks.py
  test/ui-test/testSuites/suite_onboarding/shared/steps/signUpSteps.py
  test/ui-test/testSuites/suite_onboarding/tst_passwordStrength/bdd_hooks.py
  test/ui-test/testSuites/suite_onboarding/tst_signUpNegativeCases/bdd_hooks.py
  test/ui-test/testSuites/suite_settings/tst_mainSettingsSection/bdd_hooks.py
  test/ui-test/testSuites/suite_settings/tst_userIdentity/bdd_hooks.py
  test/ui-test/testSuites/suite_wallet/shared/steps/walletInitSteps.py
  test/ui-test/testSuites/suite_wallet/shared/steps/walletSteps.py
  test/ui-test/testSuites/suite_wallet/tst_transaction/bdd_hooks.py
  test/ui-test/testSuites/suite_wallet/tst_wallet/bdd_hooks.py
Labels: squish

#8389 ci: separate buckets for mobile and desktop builds
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.imports
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.linux-cpp
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.macos-cpp.todo
  ci/Jenkinsfile.uitests
  ci/Jenkinsfile.windows
  ci/Jenkinsfile.windows-cpp.todo
Labels: ci

#8404 ci: clarify why we ignore UNSTABLE squish state
  ci/Jenkinsfile.e2e
Labels: ci

#8397 feat(ActivityCenter): Click on reply message jumps to message in chat log
  ui/app/mainui/activitycenter/views/ActivityNotificationMention.qml
  ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml
  ui/app/mainui/activitycenter/views/ActivityNotificationReply.qml
Labels: tested

#6155 feat(Settings): Enable Community History Archive by default and remove toggle
  src/app/modules/main/profile_section/advanced/controller.nim
  src/app/modules/main/profile_section/advanced/io_interface.nim
  src/app/modules/main/profile_section/advanced/module.nim
  src/app/modules/main/profile_section/advanced/view.nim
  src/app_service/common/network_constants.nim
  src/app_service/service/community/service.nim
  src/app_service/service/node_configuration/service.nim
  src/backend/general.nim
  src/backend/node_config.nim
  ui/app/AppLayouts/Chat/controls/community/CommunityOptions.qml
  ui/app/AppLayouts/Chat/panels/communities/CommunityOverviewSettingsPanel.qml
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
  ui/app/AppLayouts/CommunitiesPortal/popups/CreateCommunityPopup.qml
  ui/app/AppLayouts/CommunitiesPortal/stores/CommunitiesStore.qml
  ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
  ui/app/AppLayouts/Profile/views/AdvancedView.qml
Labels: tested, 0.9.0
