Repository status-im/status-desktop, pull requests merged in 2022-09, with the labels that each got.

#7152 fix(@desktop): Fixing setting contacts statuses
  src/app/core/signals/remote_signals/signal_type.nim
  src/app/core/signals/remote_signals/status_updates.nim
  src/app/core/signals/signals_manager.nim
  src/app/core/signals/types.nim
  src/app_service/service/contacts/service.nim
Labels: tested

#7200 fix(@desktop/onboarding): use system theme while onboarding
  ui/main.qml
Labels: tested

#7210 fix(@desktop/chat): adjust emoji popup behaviour
  ui/imports/shared/status/StatusChatInput.qml
Labels: tested

#7150 fix(@desktop/wallet): Entering ENS name in SendModal doesnt work
  src/app_service/common/conversion.nim
  ui/app/AppLayouts/stores/RootStore.qml
  ui/imports/shared/popups/SendModal.qml
  ui/imports/utils/Utils.qml
Labels: tested

#7270 fix(@desktop/settings): update display name validation to unblock saveability
  ui/app/AppLayouts/Profile/views/profile/MyProfileSettingsView.qml
Labels: tested

#7245 fix(@desktop/chat): adjust mentions handing logic
  ui/imports/shared/status/StatusChatInput.qml
Labels: tested

#7289 fix(@desktop/chat): adjust message length check condition
  ui/imports/shared/status/StatusChatInput.qml
Labels: tested

#7326 fix(@desktop/settings): adjust contacts settings
  ui/app/AppLayouts/Profile/views/ContactsView.qml
  ui/app/AppLayouts/Profile/views/SettingsContentBase.qml
Labels: tested

#6564 ci: fix upload speeds on Windows
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.linux-cpp
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.macos-cpp.todo
  ci/Jenkinsfile.windows
  ci/Jenkinsfile.windows-cpp.todo
Labels: ci, windows

#7385 fix(@wallet): asset formatting
  src/app/modules/shared_models/balance_model.nim
  src/app_service/service/wallet_account/async_tasks.nim
  src/app_service/service/wallet_account/dto.nim
  ui/imports/shared/controls/AssetsDetailsHeader.qml
  ui/imports/shared/views/AssetsDetailView.qml
  ui/imports/shared/views/AssetsView.qml
Labels: tested

#4502 feat: set default sync period to 9d days for new accounts
  src/app/modules/main/controller.nim
  src/app_service/service/settings/service.nim
Labels: do not merge, tested, experimental

#7423 fix broken contact/chat images in StatusSearchListPopup
  ui/app/mainui/AppMain.qml
  ui/imports/shared/status/StatusSearchListPopup.qml
Labels: tested

#7407 fix(@chat/members): display member's picture according to settings
  ui/app/AppLayouts/Chat/panels/UserListPanel.qml
Labels: tested

#7391 fix: contact status not reflected in list
  src/app/modules/main/profile_section/contacts/controller.nim
  src/app/modules/main/profile_section/contacts/io_interface.nim
  src/app/modules/main/profile_section/contacts/module.nim
Labels: tested

#7426 fix(PinnedMessagesPopup): “Jump to” button doesn’t work in pinned messages popup
  src/app/modules/main/chat_section/chat_content/messages/view.nim
  ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: tested

#7325 feat(@desktop/communities) Permissions - 'is allowed to' dropdown
  ui/app/AppLayouts/Chat/controls/community/EnsPanel.qml
  ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml
  ui/app/AppLayouts/Chat/controls/community/PermissionListItem.qml
  ui/app/AppLayouts/Chat/controls/community/PermissionTypes.qml
  ui/app/AppLayouts/Chat/controls/community/PermissionsDropdown.qml
  ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
Labels: tested

#7080 fix(Profile/ContactsView): updated contacts layout
  ui/app/AppLayouts/Profile/panels/ContactsListPanel.qml
  ui/app/AppLayouts/Profile/views/ContactsView.qml
  ui/app/AppLayouts/Profile/views/SettingsContentBase.qml
Labels: tested

#7444 feat(PinnedMessagesPopup): enable Unpin context menu entry
  ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml
  ui/imports/shared/views/chat/MessageContextMenuView.qml
Labels: tested

#7449 fix(TransferOwnershipPopup): copy button right margin
  ui/app/AppLayouts/Chat/popups/community/TransferOwnershipPopup.qml
Labels: tested

#7445 fix(Createchat/EditGroupChat view): fixed spacing all over
  ui/app/AppLayouts/Chat/panels/InlineSelectorPanel.qml
  ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml
  ui/app/AppLayouts/Chat/views/CreateChatView.qml
  ui/app/AppLayouts/Chat/views/MembersSelectorView.qml
Labels: tested

#7485 fix(ChatMessagesView): unbreak closing reply bubble
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
Labels: tested

#7421 fix(@desktop/community): update new category handling
  src/app_service/service/community/service.nim
Labels: tested

#7431 fix(@desktop/community): add member verified model value
  src/app/modules/main/chat_section/chat_content/users/module.nim
  src/app/modules/main/chat_section/chat_content/users/view.nim
  src/app/modules/main/communities/module.nim
  src/app/modules/main/module.nim
  src/app/modules/shared_models/active_section.nim
  src/app/modules/shared_models/member_item.nim
  src/app/modules/shared_models/member_model.nim
  src/app/modules/shared_models/section_item.nim
Labels: tested

#7456 fix(@desktop/chat): handle same name mentions
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/imports/shared/status/StatusChatInput.qml
Labels: tested

#7513 fix(@wallet): Send tx popup
  ci/Jenkinsfile.uitests
  src/app_service/service/transaction/service.nim
Labels: tested

#7490 fix(@desktop/community): community tags close button adjust
  ui/StatusQ/src/StatusQ/Popups/statusModal/StatusModalHeader.qml
Labels: tested

#7460 fix(@desktop/chat): adjust chat name placement
  ui/imports/shared/views/chat/ChannelIdentifierView.qml
Labels: tested

#7593 fix(CreateChatView): disable confirm button if no tags added
  ui/app/AppLayouts/Chat/panels/InlineSelectorPanel.qml
Labels: tested

#7610 fix(Communities/Settings): Cropped bottom panel in Community Overview
  ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
Labels: Communities, E:Bugfixes

#7619 fix(ProfilePopup): fixed display name on block popup
  ui/imports/shared/popups/ProfilePopup.qml
Labels: tested

#7543 fix(@desktop/chat): add message sent and delivered handler
  src/app/core/signals/remote_signals/messages.nim
  src/app/core/signals/remote_signals/signal_type.nim
  src/app/core/signals/signals_manager.nim
  src/app/modules/main/chat_section/chat_content/messages/controller.nim
  src/app/modules/main/chat_section/chat_content/messages/io_interface.nim
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/shared_models/message_item.nim
  src/app/modules/shared_models/message_model.nim
  src/app_service/service/message/dto/message.nim
  src/app_service/service/message/service.nim
Labels: tested

#7631 fix(@desktop/general): Fix sections switching shortcuts
  src/app/modules/main/module.nim
  src/app/modules/main/view.nim
  src/app/modules/shared_models/section_model.nim
  ui/app/mainui/AppMain.qml
  ui/imports/utils/Global.qml
Labels: tested, 0.7.0

#7420 feat(CreateChatView): Support pasting chat key
  src/app/modules/main/module.nim
  src/app_service/service/contacts/service.nim
  ui/app/AppLayouts/Chat/panels/InlineSelectorPanel.qml
  ui/app/AppLayouts/Chat/views/CreateChatView.qml
  ui/app/AppLayouts/Chat/views/MembersSelectorView.qml
  ui/imports/shared/popups/ProfilePopup.qml
  ui/imports/shared/popups/SendContactRequestModal.qml
  ui/imports/shared/popups/qmldir
  ui/imports/utils/Global.qml
Labels: tested, 0.7.0

#7451 fix(@desktop/wallet): Added squish tests for transactions and transaction details
  test/ui-test/src/screens/StatusWalletScreen.py
  test/ui-test/testSuites/global_shared/scripts/decorators.py
  test/ui-test/testSuites/suite_status/shared/scripts/sections/wallet_names.py
  test/ui-test/testSuites/suite_status/shared/steps/walletSteps.py
  test/ui-test/testSuites/suite_status/tst_wallet/test.feature
  ui/imports/shared/views/HistoryView.qml
  ui/imports/shared/views/TransactionDetailView.qml
Labels: 0.7.0

#7638 fix(StatusChatInfoButton): space between # and channel name
  ui/StatusQ/src/StatusQ/Controls/StatusChatInfoButton.qml
Labels: 0.7.0

#7602 fix(Chat/Verify Identity): Identity verification typo
  ui/imports/shared/views/ProfileView.qml
Labels: E:Bugfixes, 0.7.0

#7542 fix(@desktop/contacts): Do not show pending identity request when use…
  ui/imports/shared/views/chat/MessageContextMenuView.qml
Labels: 0.7.0

#7544 fix(@desktop/communities): Show only not community members
  ui/imports/shared/views/ExistingContacts.qml
  ui/imports/shared/views/PickedContacts.qml
Labels: 0.7.0

#7527 fix(wallet): fix never fetching transactions
  ui/app/AppLayouts/Wallet/stores/RootStore.qml
Labels: tested-issues

#7601 fix(Popups): clipping area fixed in various popups
  ui/StatusQ/src/StatusQ/Popups/StatusStackModal.qml
  ui/app/AppLayouts/Chat/ChatLayout.qml
  ui/app/AppLayouts/Chat/popups/PublicChatPopup.qml
  ui/app/AppLayouts/Chat/popups/community/CreateCategoryPopup.qml
  ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
  ui/app/AppLayouts/CommunitiesPortal/panels/CommunityColorPanel.qml
  ui/app/AppLayouts/CommunitiesPortal/panels/CommunityTagsPanel.qml
  ui/app/AppLayouts/CommunitiesPortal/popups/CreateCommunityPopup.qml
  ui/app/AppLayouts/Profile/popups/BackupSeedModal.qml
  ui/app/AppLayouts/Profile/popups/backupseed/Acknowledgements.qml
  ui/app/AppLayouts/Profile/popups/backupseed/BackupSeedStepBase.qml
Labels: tested-issues, 0.7.0

#7623 feat(@desktop/keycard): sign transaction using `Authenticate` flow
  src/app/modules/main/wallet_section/transactions/controller.nim
  src/app/modules/main/wallet_section/transactions/io_interface.nim
  src/app/modules/main/wallet_section/transactions/module.nim
  src/app/modules/main/wallet_section/transactions/view.nim
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/stores/RootStore.qml
  ui/imports/shared/popups/SendModal.qml
Labels: tested
