Repository status-im/status-desktop, pull requests merged in 2022-03, with the labels that each got.

#4940 feat(@settings): Build layout for settings wallet
  ui/app/AppLayouts/Profile/views/wallet/MainView.qml
Labels: tested

#4901 fix(notifications): fix windows tray icon and notifications
  src/app/boot/app_controller.nim
  src/app/core/main.nim
  src/app/core/notifications/notifications_manager.nim
  src/app/modules/main/chat_section/module.nim
Labels: tested-issues

#4924 refactor: add back eip1559
  src/app/modules/main/module.nim
  src/app/modules/main/wallet_section/controller.nim
  src/app/modules/main/wallet_section/controller_interface.nim
  src/app/modules/main/wallet_section/io_interface.nim
  src/app/modules/main/wallet_section/module.nim
  src/app/modules/main/wallet_section/transactions/controller.nim
  src/app/modules/main/wallet_section/transactions/controller_interface.nim
  src/app/modules/main/wallet_section/transactions/io_interface.nim
  src/app/modules/main/wallet_section/transactions/module.nim
  src/app/modules/main/wallet_section/transactions/view.nim
  src/app/modules/main/wallet_section/view.nim
  src/app_service/service/ens/service.nim
  src/app_service/service/eth/utils.nim
  src/app_service/service/network/service.nim
  src/app_service/service/network/service_interface.nim
  src/app_service/service/settings/service.nim
  src/app_service/service/settings/service_interface.nim
  src/app_service/service/stickers/service.nim
  src/app_service/service/transaction/service.nim
  src/backend/eth.nim
  ui/app/AppLayouts/Browser/stores/WalletStore.qml
  ui/app/AppLayouts/Browser/views/WebProviderObj.qml
  ui/app/AppLayouts/stores/RootStore.qml
  ui/imports/shared/controls/GasSelector.qml
  ui/imports/shared/popups/SendModal.qml
  ui/imports/shared/popups/SignTransactionModal.qml
  ui/imports/shared/status/StatusETHTransactionModal.qml
  ui/imports/shared/status/StatusSNTTransactionModal.qml
Labels: tested

#4895 refactor: re-hook disconnected and re-connected signals and banner
  src/app/modules/main/controller.nim
  src/app/modules/main/controller_interface.nim
  src/app/modules/main/module.nim
  src/app/modules/main/private_interfaces/module_controller_delegate_interface.nim
  src/app/modules/main/private_interfaces/module_view_delegate_interface.nim
  src/app/modules/main/view.nim
  src/app_service/service/node/service.nim
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/imports/shared/panels/ImageLoader.qml
  ui/imports/shared/status/StatusStickersPopup.qml
Labels: tested

#4942 fix(@desktop/wallet): add/re-add buy crypto feature
  src/app/modules/main/wallet_section/buy_sell_crypto/controller.nim
  src/app/modules/main/wallet_section/buy_sell_crypto/controller_interface.nim
  src/app/modules/main/wallet_section/buy_sell_crypto/io_interface.nim
  src/app/modules/main/wallet_section/buy_sell_crypto/item.nim
  src/app/modules/main/wallet_section/buy_sell_crypto/model.nim
  src/app/modules/main/wallet_section/buy_sell_crypto/module.nim
  src/app/modules/main/wallet_section/buy_sell_crypto/view.nim
  src/app/modules/main/wallet_section/io_interface.nim
  src/app/modules/main/wallet_section/module.nim
  src/app_service/service/transaction/cryptoRampDto.nim
  src/app_service/service/transaction/service.nim
  src/backend/transactions.nim
  ui/app/AppLayouts/Wallet/panels/WalletHeader.qml
  ui/app/AppLayouts/Wallet/popups/CryptoServicesModal.qml
  ui/app/AppLayouts/Wallet/stores/RootStore.qml
Labels: tested

#4941 fix(@desktop/wallet): Re-add saved addresses view from Wallet V2
  src/app/modules/main/wallet_section/saved_addresses/controller.nim
  src/app/modules/main/wallet_section/saved_addresses/controller_interface.nim
  src/app/modules/main/wallet_section/saved_addresses/io_interface.nim
  src/app/modules/main/wallet_section/saved_addresses/module.nim
  src/app/modules/main/wallet_section/saved_addresses/view.nim
  src/app_service/service/saved_address/service.nim
  src/app_service/service/saved_address/service_interface.nim
  ui/app/AppLayouts/Wallet/WalletLayout.qml
  ui/app/AppLayouts/Wallet/controls/SavedAddressesError.qml
  ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml
  ui/app/AppLayouts/Wallet/stores/RootStore.qml
  ui/app/AppLayouts/Wallet/views/LeftTabView.qml
  ui/app/AppLayouts/Wallet/views/SavedAddressesView.qml
  ui/app/AppMain.qml
  ui/imports/shared/controls/AddressInput.qml
  ui/imports/shared/controls/ContactsListAndSearch.qml
  ui/imports/shared/controls/RecipientSelector.qml
Labels: tested

#4929 fix(drag-zone): make drag zone only work in correct chats
  ui/app/AppLayouts/Chat/views/ChatColumnView.qml
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/app/AppMain.qml
  ui/imports/shared/status/StatusChatInput.qml
  ui/imports/utils/Global.qml
  ui/main.qml
Labels: tested

#4967 fix(group-chats): wrong group name in a subsequent edit attempt
  ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml
Labels: tested

#4963 Improve ChatContentView loading and duplication
  ui/app/AppLayouts/Chat/views/ChatColumnView.qml
Labels: tested

#4970 fix(chat/textInput): prevent break mentions when ctrl+left is pressed
  ui/imports/shared/status/StatusChatInput.qml
Labels: bug, Chat, tested

#4915 fix(chatMessages): line breaks in message were not respected when pasting text
  ui/imports/utils/Utils.qml
Labels: bug, Chat

#4972 feat(privacy): reimplement show only contact pfp using status-go setting
  src/app/global/local_account_sensitive_settings.nim
  src/app/modules/main/activity_center/module.nim
  src/app/modules/main/chat_section/chat_content/messages/controller.nim
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/main/chat_section/chat_content/module.nim
  src/app/modules/main/chat_section/chat_content/users/controller.nim
  src/app/modules/main/chat_section/chat_content/users/module.nim
  src/app/modules/main/communities/module.nim
  src/app/modules/main/module.nim
  src/app/modules/main/profile_section/privacy/controller.nim
  src/app/modules/main/profile_section/privacy/controller_interface.nim
  src/app/modules/main/profile_section/privacy/io_interface.nim
  src/app/modules/main/profile_section/privacy/module.nim
  src/app/modules/main/profile_section/privacy/view.nim
  src/app/modules/shared_models/message_item.nim
  src/app/modules/shared_models/message_model.nim
  src/app/modules/shared_models/user_item.nim
  src/app/modules/shared_models/user_model.nim
  src/app_service/service/contacts/service.nim
  src/app_service/service/settings/dto/settings.nim
  src/app_service/service/settings/service.nim
  ui/app/AppLayouts/Chat/controls/UserDelegate.qml
  ui/app/AppLayouts/Chat/panels/UserListPanel.qml
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/app/AppLayouts/Profile/ProfileLayout.qml
  ui/app/AppLayouts/Profile/stores/PrivacyStore.qml
  ui/app/AppLayouts/Profile/views/PrivacyView.qml
  ui/imports/shared/popups/ProfilePopup.qml
  ui/imports/shared/views/chat/CompactMessageView.qml
  ui/imports/shared/views/chat/MessageView.qml
  ui/imports/utils/Constants.qml
  ui/imports/utils/Global.qml
Labels: tested

#4978 feat(@settings): Display account information
  src/app/modules/main/wallet_section/controller.nim
  src/app/modules/main/wallet_section/controller_interface.nim
  src/app/modules/main/wallet_section/io_interface.nim
  src/app/modules/main/wallet_section/module.nim
  src/app/modules/main/wallet_section/view.nim
  src/app_service/service/wallet_account/service.nim
  src/app_service/service/wallet_account/service_interface.nim
  ui/app/AppLayouts/Profile/controls/WalletAccountDelegate.qml
  ui/app/AppLayouts/Profile/stores/WalletStore.qml
  ui/app/AppLayouts/Profile/views/WalletView.qml
  ui/app/AppLayouts/Profile/views/wallet/AccountView.qml
  ui/app/AppLayouts/Profile/views/wallet/MainView.qml
Labels: tested

#4999 fix(splashScreen): removed lottie related code
  ui/app/mainui/SplashScreen.qml
Labels: tested

#4994 fix(desktop/chat): Do not display "Send message" to logged-in user
  ui/imports/shared/views/chat/MessageContextMenuView.qml
Labels: tested

#5008 fix(@wallet): Correctly load token at boot
  src/app/boot/app_controller.nim
Labels: tested

#5006 clean(@wallet): remove old manage assets
  ui/app/AppLayouts/Wallet/panels/TokenSettingsModalContent.qml
  ui/app/AppLayouts/Wallet/panels/WalletHeader.qml
  ui/app/AppLayouts/Wallet/popups/AddShowTokenModal.qml
  ui/app/AppLayouts/Wallet/popups/TokenSettingsModal.qml
  ui/app/AppLayouts/Wallet/stores/RootStore.qml
Labels: tested

#4996 feat(@settings): adjust feature flags for app settings
  ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml
  ui/app/AppLayouts/Profile/stores/WalletStore.qml
  ui/app/AppLayouts/Profile/views/wallet/MainView.qml
Labels: tested

#4986 fix(@dekstop/chat): mentioning oneself display the full key instead of username
  src/app/modules/main/chat_section/chat_content/users/module.nim
  ui/imports/shared/status/StatusChatInput.qml
Labels: tested

#4992 fix(@dekstop/chat): editing a message does not update the reply
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/main/chat_section/chat_content/messages/view.nim
  src/app/modules/shared_models/message_model.nim
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/imports/shared/views/chat/CompactMessageView.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: tested

#5030 fix(Contacts): Exclude myself from contacts
  src/app/modules/main/profile_section/contacts/module.nim
Labels: tested

#4820 feat(desktop/chat): Updated create new chat/group flow
  src/app/modules/main/chat_section/chat_content/messages/controller.nim
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/controller_interface.nim
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/chat_section/private_interfaces/module_view_delegate_interface.nim
  src/app/modules/main/chat_section/view.nim
  src/app_service/service/chat/service.nim
  src/backend/chat.nim
  src/backend/group_chat.nim
  ui/app/AppLayouts/Chat/ChatLayout.qml
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/ChatColumnView.qml
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml
  ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
  ui/app/AppLayouts/Chat/views/CreateChatView.qml
  ui/app/AppLayouts/Profile/stores/ContactsStore.qml
  ui/imports/shared/status/StatusChatInput.qml
  ui/imports/shared/views/chat/MessageContextMenuView.qml
Labels: Chat, tested, feature

#5028 fix(@wallet): pre-populate token details
  src/app_service/service/token/async_tasks.nim
  ui/app/AppLayouts/Profile/popups/AddShowTokenModal.qml
Labels: tested

#4993 feat(Desktop/Password): New password view design
  ui/app/AppLayouts/Onboarding/OnboardingLayout.qml
  ui/app/AppLayouts/Onboarding/views/ConfirmPasswordView.qml
  ui/app/AppLayouts/Onboarding/views/CreatePasswordView.qml
  ui/app/AppLayouts/Onboarding/views/ExistingKeyView.qml
  ui/app/AppLayouts/Onboarding/views/GenKeyView.qml
  ui/app/AppLayouts/Profile/popups/ChangePasswordModal.qml
  ui/app/AppLayouts/Profile/popups/StoreToKeychainSelectionModal.qml
  ui/app/AppLayouts/Profile/views/PasswordView.qml
Labels: onboarding, tested, priority F2: important, E:Onboarding

#5016 fix(community): join community when request is accepted
  src/app_service/service/community/service.nim
Labels: tested

#4983 fix(chat): only add active chats (fixes chats reappearing after leaving)
  src/app_service/service/chat/service.nim
  src/app_service/service/message/service.nim
Labels: tested

#5051 fix(@browser): Fix etherscan link
  src/app/modules/main/browser_section/provider/view.nim
  ui/app/AppLayouts/Browser/BrowserLayout.qml
  ui/app/AppLayouts/Browser/stores/WalletStore.qml
Labels: tested

#5036 fix(@desktop/wallet): Disconnect button doesnt disconnect Wallet from Browser
  src/app/modules/main/browser_section/provider/controller.nim
  src/app/modules/main/browser_section/provider/controller_interface.nim
  src/app/modules/main/browser_section/provider/module.nim
  src/app/modules/main/browser_section/provider/view.nim
  ui/app/AppLayouts/Browser/BrowserLayout.qml
  ui/app/AppLayouts/Browser/popups/BrowserWalletMenu.qml
  ui/app/AppLayouts/Browser/stores/RootStore.qml
  ui/app/AppLayouts/Browser/stores/Web3ProviderStore.qml
  ui/app/AppLayouts/Browser/views/WebProviderObj.qml
Labels: tested

#5055 feat(@desktop/wallet): adapt receive modal design
  ui/app/AppLayouts/Browser/popups/BrowserWalletMenu.qml
  ui/app/AppLayouts/Browser/stores/RootStore.qml
  ui/app/AppLayouts/Wallet/panels/WalletHeader.qml
  ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml
  ui/app/AppLayouts/Wallet/stores/RootStore.qml
  ui/imports/shared/controls/CopyToClipBoardButton.qml
  ui/imports/shared/panels/TextWithLabel.qml
  ui/imports/shared/status/StatusExpandableAddress.qml
  ui/imports/shared/status/StatusSectionDescItem.qml
Labels: tested

#5068 fix(@browser): Fix disconnect when url is resolved by ens
  ui/app/AppLayouts/Browser/BrowserLayout.qml
Labels: tested

#5061 fix(@browser): unlink wallet account and browser account
  src/app/modules/main/browser_section/current_account/controller.nim
  src/app/modules/main/browser_section/current_account/controller_interface.nim
  src/app/modules/main/browser_section/current_account/io_interface.nim
  src/app/modules/main/browser_section/current_account/module.nim
  src/app/modules/main/browser_section/current_account/view.nim
  src/app/modules/main/browser_section/module.nim
  ui/app/AppLayouts/Browser/popups/BrowserConnectionModal.qml
  ui/app/AppLayouts/Browser/popups/BrowserWalletMenu.qml
  ui/app/AppLayouts/Browser/stores/WalletStore.qml
Labels: tested

#5111 fix(@desktop/chat): cannot create a group chat by hitting `Confirm`
  ui/app/AppLayouts/Chat/ChatLayout.qml
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/ChatColumnView.qml
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
  ui/app/AppLayouts/Chat/views/CreateChatView.qml
  ui/imports/shared/status/StatusChatInput.qml
Labels: tested

#5019 chore: add qtlottie to aqtinstall parameters
  scripts/windows_build_setup.ps1
Labels: tested-issues

#5120 fix(onboarding): create pwd view was white in dark mode
  ui/app/AppLayouts/Onboarding/views/ConfirmPasswordView.qml
  ui/app/AppLayouts/Onboarding/views/CreatePasswordView.qml
Labels: tested

#5100 fix(GenKeyModal): Add maximum length to input
  ui/app/AppLayouts/Onboarding/popups/GenKeyModal.qml
Labels: tested

#5091 fix(desktop/chat): Notifies when the user is mentioned in edited message #4475
  src/app/modules/main/activity_center/module.nim
  src/app/modules/main/chat_section/chat_content/messages/controller.nim
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/main/chat_section/chat_content/module.nim
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/io_interface.nim
  src/app/modules/main/chat_section/module.nim
  src/app/modules/shared_models/message_item.nim
  src/app/modules/shared_models/message_model.nim
  src/app_service/service/message/dto/message.nim
  src/app_service/service/message/service.nim
Labels: testing

#5133 wip idea(Profile): workaround to increase emoji sharpness in Profile
  ui/app/AppLayouts/Profile/views/MyProfileView.qml
  ui/imports/shared/controls/chat/ProfileHeader.qml
  ui/imports/shared/popups/ProfilePopup.qml
Labels: tested

#5157 fix(@desktop/wallet): User stays on removed account view in wallet after account removal from settings
  src/app/modules/main/browser_section/current_account/module.nim
  src/app/modules/main/browser_section/current_account/view.nim
  src/app/modules/main/browser_section/module.nim
  src/app/modules/main/module.nim
  src/app/modules/main/wallet_section/module.nim
  src/app_service/service/wallet_account/service.nim
  ui/app/AppLayouts/Browser/popups/BrowserWalletMenu.qml
  ui/app/AppLayouts/Wallet/WalletLayout.qml
  ui/app/AppLayouts/Wallet/views/LeftTabView.qml
Labels: tested

#5072 feat(updates): implement new download update page
  src/app/modules/main/profile_section/about/view.nim
  ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml
  ui/app/AppLayouts/Profile/views/AboutView.qml
  ui/app/mainui/AppMain.qml
  ui/imports/assets/images/status-logo-dark.svg
  ui/imports/assets/images/status-logo-light.svg
  ui/imports/shared/panels/ModuleWarning.qml
  ui/imports/shared/popups/DownloadModal.qml
  ui/imports/shared/popups/DownloadPage.qml
  ui/imports/shared/popups/qmldir
Labels: tested

#5178 fix(GenKeyModal): Add trim to username
  ui/app/AppLayouts/Onboarding/popups/GenKeyModal.qml
Labels: tested

#5214 fix(Settings/Profile/Edit): The form for editing Display name looks incorrect
  ui/app/AppLayouts/Profile/views/DisplayNamePopup.qml
  ui/app/AppLayouts/Profile/views/MyProfileView.qml
Labels: bug, Profile, qml

#5103 feat(SearchBox): use StatusInput for SearchBox and add clear button
  ui/app/AppLayouts/Profile/panels/TokenSettingsModalContent.qml
  ui/app/AppLayouts/Profile/views/ContactsView.qml
  ui/imports/shared/controls/SearchBox.qml
  ui/imports/shared/status/StatusGifPopup.qml
Labels: testing

#4985 feat(onboarding): adding create new keys screens
  src/app/modules/startup/onboarding/item.nim
  src/app/modules/startup/onboarding/model.nim
  src/app/modules/startup/onboarding/module.nim
  src/app/modules/startup/onboarding/view.nim
  ui/app/AppLayouts/Onboarding/OnboardingLayout.qml
  ui/app/AppLayouts/Onboarding/controls/OnboardingBasePage.qml
  ui/app/AppLayouts/Onboarding/popups/MnemonicRecoverySuccessModal.qml
  ui/app/AppLayouts/Onboarding/popups/UploadProfilePicModal.qml
  ui/app/AppLayouts/Onboarding/shared/CreatePasswordModal.qml
  ui/app/AppLayouts/Onboarding/stores/OnboardingStore.qml
  ui/app/AppLayouts/Onboarding/views/ConfirmPasswordView.qml
  ui/app/AppLayouts/Onboarding/views/CreatePasswordView.qml
  ui/app/AppLayouts/Onboarding/views/GenKeyView.qml
  ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
  ui/app/AppLayouts/Onboarding/views/KeysMainView.qml
  ui/app/AppLayouts/Onboarding/views/LoginView.qml
  ui/app/AppLayouts/Onboarding/views/TouchIDAuthView.qml
  ui/app/AppLayouts/Onboarding/views/WelcomeView.qml
  ui/app/AppLayouts/Profile/popups/ChangePasswordModal.qml
  ui/app/AppLayouts/Profile/popups/StoreToKeychainSelectionModal.qml
  ui/app/AppLayouts/Profile/stores/PrivacyStore.qml
  ui/imports/assets/images/onboarding/chains.png
  ui/imports/assets/images/onboarding/fingerprint.png
  ui/imports/assets/images/onboarding/welcome.png
  ui/imports/shared/controls/EmojiHash.qml
  ui/imports/shared/controls/chat/ProfileHeader.qml
  ui/imports/shared/controls/qmldir
  ui/imports/shared/panels/ImageLoader.qml
  ui/imports/shared/stores/RootStore.qml
  ui/imports/shared/views/PasswordView.qml
  ui/imports/shared/views/qmldir
  ui/main.qml
Labels: onboarding, tested

#5131 fix(onboarding): show warning when trying to re-encrypt existing account
  src/app/modules/startup/onboarding/controller.nim
  src/app/modules/startup/onboarding/io_interface.nim
  src/app/modules/startup/onboarding/module.nim
  src/app/modules/startup/onboarding/view.nim
  src/app_service/service/accounts/dto/accounts.nim
  src/app_service/service/accounts/service.nim
  ui/app/AppLayouts/Onboarding/views/ConfirmPasswordView.qml
  ui/app/AppLayouts/Onboarding/views/ExistingKeyView.qml
  ui/imports/utils/Constants.qml
Labels: tested

#5231 fix(create/join chat): icon buttons were highlighted always
  ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
Labels: tested

#5255 fix(onboarding): fix importing seed phrase importing different accounts
  ui/app/AppLayouts/Onboarding/OnboardingLayout.qml
  ui/app/AppLayouts/Onboarding/popups/MnemonicRecoverySuccessModal.qml
  ui/app/AppLayouts/Onboarding/stores/OnboardingStore.qml
  ui/app/AppLayouts/Onboarding/views/ConfirmPasswordView.qml
  ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
  ui/app/AppLayouts/Onboarding/views/KeysMainView.qml
  ui/app/AppLayouts/Onboarding/views/LoginView.qml
Labels: tested

#5227 refactor(user-list): implement getMembers to populate user list
  src/app/modules/main/chat_section/chat_content/users/controller.nim
  src/app/modules/main/chat_section/chat_content/users/module.nim
  src/app_service/service/chat/dto/chat.nim
  src/app_service/service/chat/service.nim
  src/backend/chat.nim
Labels: tested
