Repository status-im/status-desktop, pull requests merged in 2022-02, with the labels that each got.

#4645 fix(community): hook edit community channel
  src/app/modules/main/chat_section/base_item.nim
  src/app/modules/main/chat_section/chat_content/chat_details.nim
  src/app/modules/main/chat_section/chat_content/module.nim
  src/app/modules/main/chat_section/chat_content/view.nim
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/controller_interface.nim
  src/app/modules/main/chat_section/item.nim
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/chat_section/private_interfaces/module_view_delegate_interface.nim
  src/app/modules/main/chat_section/view.nim
  src/app/modules/main/communities/controller.nim
  src/app/modules/main/communities/module.nim
  src/app/modules/main/communities/private_interfaces/module_controller_delegate_interface.nim
  ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml
  ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Labels: tested

#4630 refactor: removing mailserver controller and model
  src/app/boot/app_controller.nim
  src/app/core/main.nim
  src/app/core/tasks/marathon/mailserver/controller.nim
  src/app/core/tasks/marathon/mailserver/model.nim
  src/app/core/tasks/marathon/mailserver/worker.nim
  src/app/modules/main/chat_section/chat_content/messages/controller.nim
  src/app/modules/main/chat_section/chat_content/messages/controller_interface.nim
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_controller_delegate_interface.nim
  src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_view_delegate_interface.nim
  src/app/modules/main/chat_section/chat_content/messages/view.nim
  src/app/modules/main/chat_section/chat_content/module.nim
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/chat_section/private_interfaces/module_access_interface.nim
  src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim
  src/app/modules/main/chat_section/view.nim
  src/app/modules/main/controller.nim
  src/app/modules/main/module.nim
  src/app/modules/main/private_interfaces/module_access_interface.nim
  src/app/modules/main/private_interfaces/module_controller_delegate_interface.nim
  src/app_service/service/mailservers/service.nim
  src/nim_status_client.nim
  ui/app/AppLayouts/Chat/stores/MessageStore.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: QA

#4654 fix(@desktop/wallet): send transaction to address UI is broken
  src/app_service/service/contacts/async_tasks.nim
Labels: tested

#4652 chore(community): remove pinned messages button in Edit community popup
  ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml
  ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
  ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
Labels: tested

#4662 fix(@desktop/chat): [restore after rebase] Group members list must show only 5
  ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml
Labels: bug, tested

#4714 fix(@desktop/communities): community import has some issues
  src/app/modules/main/communities/controller.nim
  src/app/modules/main/communities/module.nim
  src/app/modules/main/communities/private_interfaces/module_access_interface.nim
  src/app/modules/main/communities/private_interfaces/module_controller_delegate_interface.nim
  src/app/modules/main/communities/view.nim
  src/app/modules/main/controller.nim
  src/app_service/service/community/service.nim
  src/app_service/service/message/service.nim
  ui/app/AppLayouts/Chat/popups/community/AccessExistingCommunityPopup.qml
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
Labels: tested

#4716 feat(@desktop/settings): [re-add] Add developer mode toggle
  src/app/modules/main/profile_section/advanced/controller.nim
  src/app/modules/main/profile_section/advanced/controller_interface.nim
  src/app/modules/main/profile_section/advanced/module.nim
  src/app/modules/main/profile_section/advanced/private_interfaces/module_view_delegate_interface.nim
  src/app/modules/main/profile_section/advanced/view.nim
  ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
  ui/app/AppLayouts/Profile/views/AdvancedView.qml
Labels: tested

#4712 Fix Wallet send of ETH and tokens
  src/app/modules/main/wallet_section/transactions/controller.nim
  src/app/modules/main/wallet_section/transactions/controller_interface.nim
  src/app/modules/main/wallet_section/transactions/io_interface.nim
  src/app/modules/main/wallet_section/transactions/module.nim
  src/app/modules/main/wallet_section/transactions/view.nim
  src/app_service/service/eth/dto/contract.nim
  src/app_service/service/eth/dto/method_dto.nim
  src/app_service/service/transaction/service.nim
  src/app_service/service/wallet_account/service.nim
  ui/app/AppLayouts/stores/RootStore.qml
  ui/imports/shared/popups/SendModal.qml
  ui/imports/shared/stores/RootStore.qml
Labels: tested

#4665 refactor(@activity_center): Add switch to section/chat
  src/app/modules/main/activity_center/controller.nim
  src/app/modules/main/activity_center/controller_interface.nim
  src/app/modules/main/activity_center/io_interface.nim
  src/app/modules/main/activity_center/module.nim
  src/app/modules/main/activity_center/view.nim
  ui/app/AppLayouts/Chat/views/ActivityCenterMessageComponentView.qml
Labels: tested

#4655 fix(pins): only enable jump to and unpin buttons from the pinned popup
  ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml
  ui/imports/shared/panels/chat/ChatButtonsPanel.qml
  ui/imports/shared/views/chat/CompactMessageView.qml
  ui/imports/shared/views/chat/MessageContextMenuView.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: tested

#4651 fix(pins): fix max 3 pins and unpining pins the new message
  src/app_service/service/message/service.nim
  ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml
Labels: tested

#4722 fix(browser-provider): fix browser provider not asking for authorization
  src/app/modules/main/browser_section/provider/controller.nim
  src/app_service/service/provider/dto.nim
  src/app_service/service/provider/service.nim
  src/app_service/service/provider/service_interface.nim
  ui/app/AppLayouts/Browser/popups/BrowserConnectionModal.qml
  ui/app/AppLayouts/Browser/views/WebProviderObj.qml
Labels: tested

#4723 fix: [re-add] add upper limit to initialised app window size
  ui/main.qml
Labels: tested

#4724 chore(@desktop/general): add avatar change functionality
  ui/app/AppLayouts/Profile/popups/ChangeProfilePicModal.qml
  ui/app/AppLayouts/Profile/views/MyProfileView.qml
  ui/app/AppMain.qml
  ui/imports/shared/popups/ProfilePopup.qml
  ui/imports/utils/Global.qml
Labels: tested

#4738 fix(@desktop/communities): Newly created Community remains highlighted
  src/app/modules/main/module.nim
Labels: bug, Communities, testing

#4647 fix(@activity_center): fix dup messages
  src/app/modules/main/activity_center/controller.nim
Labels: tested

#4741 feat(@desktop/general): move token balance retrieval to status go
  src/app_service/service/token/service.nim
  src/app_service/service/token/static_token.nim
  src/app_service/service/wallet_account/service.nim
  src/backend/eth.nim
  src/backend/tokens.nim
Labels: tested

#4745 fix(@desktop/wallet): send transaction to address UI is broken
  src/app_service/service/contacts/async_tasks.nim
  ui/imports/shared/controls/ContactsListAndSearch.qml
Labels: tested

#4715 fix(notifications): [re-add] fix notification setup called too soon
  src/app/boot/app_controller.nim
  src/app_service/service/os_notification/service.nim
Labels: testing

#4646 refactor(communities): delete categories
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/controller_interface.nim
  src/app/modules/main/chat_section/model.nim
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim
  src/app/modules/main/chat_section/private_interfaces/module_view_delegate_interface.nim
  src/app/modules/main/chat_section/sub_model.nim
  src/app/modules/main/chat_section/view.nim
  src/app_service/service/community/service.nim
  ui/app/AppLayouts/Chat/popups/community/CreateCategoryPopup.qml
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Labels: tested

#4731 fix(@wallet): [re-add] tx history view
  ui/app/AppLayouts/Wallet/controls/TransactionDelegate.qml
  ui/app/AppLayouts/Wallet/stores/RootStore.qml
Labels: tested

#4758 fix(@desktop/chat): mention suggestion list fixed
  src/app_service/common/message.nim
  src/app_service/service/chat/service.nim
  src/app_service/service/message/service.nim
  ui/app/AppLayouts/Chat/panels/SuggestionBoxPanel.qml
  ui/app/AppLayouts/Chat/panels/SuggestionFilterPanel.qml
  ui/app/AppLayouts/Chat/stores/UsersStore.qml
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/imports/shared/status/StatusChatInput.qml
  ui/imports/shared/views/chat/ChatTextView.qml
  ui/imports/shared/views/chat/CompactMessageView.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: tested

#4757 feat(@settings): Add feature flag for multi network
  src/app/global/local_account_sensitive_settings.nim
  ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
  ui/app/AppLayouts/Profile/views/AdvancedView.qml
Labels: tested

#4730 feat(ens): [re-add] new backend
  src/app/boot/app_controller.nim
  src/app/modules/main/module.nim
  src/app/modules/main/profile_section/ens_usernames/module.nim
  src/app/modules/main/wallet_section/transactions/controller.nim
  src/app/modules/main/wallet_section/transactions/controller_interface.nim
  src/app/modules/main/wallet_section/transactions/module.nim
  src/app_service/common/network_constants.nim
  src/app_service/service/about/update.nim
  src/app_service/service/contacts/async_tasks.nim
  src/app_service/service/contacts/service.nim
  src/app_service/service/ens/async_tasks.nim
  src/app_service/service/ens/service.nim
  src/app_service/service/ens/service_interface.nim
  src/app_service/service/ens/utils.nim
  src/app_service/service/provider/service.nim
  src/app_service/service/stickers/service.nim
  src/app_service/service/transaction/service.nim
  src/backend/ens.nim
  src/backend/transactions.nim
  ui/app/AppLayouts/Browser/BrowserLayout.qml
  ui/app/AppLayouts/Profile/stores/EnsUsernamesStore.qml
  ui/app/AppLayouts/Profile/views/EnsDetailsView.qml
  ui/app/AppLayouts/Profile/views/EnsListView.qml
  ui/app/AppLayouts/Profile/views/EnsSearchView.qml
  ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml
  ui/imports/shared/status/StatusETHTransactionModal.qml
Labels: tested

#4772 fix(ChatInput): fix clicking on emoji suggestion
  ui/imports/shared/status/StatusChatInput.qml
  ui/imports/shared/status/StatusEmojiSuggestionPopup.qml
Labels: tested

#4779 fix(link-message): fix link unfurling display and height
  ui/app/AppLayouts/stores/RootStore.qml
  ui/app/AppMain.qml
  ui/imports/shared/status/StatusChatImageLoader.qml
  ui/imports/shared/views/chat/LinksMessageView.qml
Labels: tested

#4770 fix: [re-add] The text entry box shouldn't highlight invalid @mentions
  ui/imports/shared/status/StatusChatInput.qml
Labels: tested

#4771 fix(@desktop/settings): [re-add] ensure new password is confirmed
  ui/app/AppLayouts/Profile/popups/ChangePasswordModal.qml
  ui/app/AppLayouts/Profile/views/PrivacyView.qml
Labels: tested

#4780 fix(browser-sign): show signing phrase in the sign tx modal
  ui/imports/shared/popups/SignTransactionModal.qml
Labels: tested

#4792 fix(Browser) Transaction Popup was misaligned
  ui/app/AppLayouts/Browser/BrowserLayout.qml
  ui/imports/shared/popups/ModalPopup.qml
Labels: tested

#4774 feat(@wallet): Enable multi network for wallet account
  src/app/boot/app_controller.nim
  src/app/modules/main/wallet_section/all_tokens/controller.nim
  src/app_service/common/network_constants.nim
  src/app_service/service/ens/service.nim
  src/app_service/service/network/service.nim
  src/app_service/service/token/service.nim
  src/app_service/service/wallet_account/service.nim
  src/backend/eth.nim
  src/backend/tokens.nim
Labels: tested

#4777 fix(mentions): fix showing .eth for normal ENS names in chat
  src/app_service/common/message.nim
  src/app_service/common/utils.nim
  src/app_service/service/ens/utils.nim
Labels: tested

#4762 fix(@desktop/chat): enable transactions over chat
  src/app/boot/app_controller.nim
  src/app/modules/main/activity_center/module.nim
  src/app/modules/main/chat_section/chat_content/controller.nim
  src/app/modules/main/chat_section/chat_content/controller_interface.nim
  src/app/modules/main/chat_section/chat_content/messages/controller.nim
  src/app/modules/main/chat_section/chat_content/messages/controller_interface.nim
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/main/chat_section/chat_content/module.nim
  src/app/modules/main/wallet_section/accounts/model.nim
  src/app/modules/main/wallet_section/accounts/view.nim
  src/app/modules/main/wallet_section/transactions/controller.nim
  src/app/modules/main/wallet_section/transactions/io_interface.nim
  src/app/modules/main/wallet_section/transactions/module.nim
  src/app/modules/main/wallet_section/transactions/view.nim
  src/app/modules/shared_models/message_item.nim
  src/app/modules/shared_models/message_model.nim
  src/app/modules/shared_models/message_transaction_parameters_item.nim
  src/app_service/service/message/dto/message.nim
  src/app_service/service/message/service.nim
  src/app_service/service/transaction/service.nim
  ui/app/AppLayouts/Chat/popups/ChatCommandModal.qml
  ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml
  ui/app/AppLayouts/Chat/popups/SignTransactionModal.qml
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/ChatColumnView.qml
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/app/AppLayouts/stores/RootStore.qml
  ui/imports/shared/controls/ContactSelector.qml
  ui/imports/shared/popups/SignTransactionModal.qml
  ui/imports/shared/views/TransactionPreview.qml
  ui/imports/shared/views/chat/AcceptTransactionView.qml
  ui/imports/shared/views/chat/CompactMessageView.qml
  ui/imports/shared/views/chat/MessageView.qml
  ui/imports/shared/views/chat/TransactionBubbleView.qml
Labels: tested

#4811 feat(@settings): Add wallet settings with network
  src/app/boot/app_controller.nim
  src/app/modules/main/module.nim
  src/app/modules/main/profile_section/io_interface.nim
  src/app/modules/main/profile_section/module.nim
  src/app/modules/main/profile_section/wallet/io_interface.nim
  src/app/modules/main/profile_section/wallet/module.nim
  src/app/modules/main/profile_section/wallet/networks/controller.nim
  src/app/modules/main/profile_section/wallet/networks/controller_interface.nim
  src/app/modules/main/profile_section/wallet/networks/io_interface.nim
  src/app/modules/main/profile_section/wallet/networks/item.nim
  src/app/modules/main/profile_section/wallet/networks/model.nim
  src/app/modules/main/profile_section/wallet/networks/module.nim
  src/app/modules/main/profile_section/wallet/networks/view.nim
  src/app/modules/main/profile_section/wallet/private_interfaces/module_access_interface.nim
  src/app/modules/main/profile_section/wallet/private_interfaces/module_base_interface.nim
  ui/app/AppLayouts/Profile/ProfileLayout.qml
  ui/app/AppLayouts/Profile/panels/MenuPanel.qml
  ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml
  ui/app/AppLayouts/Profile/stores/WalletStore.qml
  ui/app/AppLayouts/Profile/views/LeftTabView.qml
  ui/app/AppLayouts/Profile/views/WalletView.qml
  ui/app/AppLayouts/Profile/views/wallet/MainView.qml
  ui/app/AppLayouts/Profile/views/wallet/NetworksView.qml
Labels: tested

#4790 fix(@desktop/chat): can't join to group chat by clicking [Join chat] or decline invitation with [Decline invitation]
  src/app/modules/main/chat_section/chat_content/messages/controller.nim
  src/app/modules/main/chat_section/chat_content/messages/controller_interface.nim
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_controller_delegate_interface.nim
  src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_view_delegate_interface.nim
  src/app/modules/main/chat_section/chat_content/messages/view.nim
  src/app/modules/shared_models/message_model.nim
  ui/app/AppLayouts/Chat/stores/MessageStore.qml
  ui/imports/shared/views/chat/ChannelIdentifierView.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: tested

#4818 fix: make mentions work with ensname, alias and nickname
  src/app/modules/main/chat_section/chat_content/users/controller.nim
  src/app/modules/main/chat_section/chat_content/users/controller_interface.nim
  src/app/modules/main/chat_section/chat_content/users/module.nim
  src/app/modules/main/communities/controller.nim
  src/app/modules/main/communities/controller_interface.nim
  src/app/modules/main/communities/module.nim
  src/app/modules/main/controller.nim
  src/app/modules/main/controller_interface.nim
  src/app/modules/main/module.nim
  src/app/modules/shared_models/active_section.nim
  src/app/modules/shared_models/section_item.nim
  src/app/modules/shared_models/user_item.nim
  src/app/modules/shared_models/user_model.nim
  ui/app/AppLayouts/Chat/panels/SuggestionFilterPanel.qml
  ui/imports/shared/status/StatusChatInput.qml
Labels: tested

#4833 chores(@wallet): remove wallet 2
  src/app/global/app_sections_config.nim
  src/app/global/local_account_sensitive_settings.nim
  src/app/modules/main/module.nim
  src/app/modules/shared_models/section_item.nim
  ui/app/AppLayouts/WalletV2/WalletV2Layout.qml
  ui/app/AppLayouts/WalletV2/controls/CollectibleDetailsHeader.qml
  ui/app/AppLayouts/WalletV2/controls/HeaderButton.qml
  ui/app/AppLayouts/WalletV2/controls/SavedAddressesError.qml
  ui/app/AppLayouts/WalletV2/controls/SeedAccountDetailsDelegate.qml
  ui/app/AppLayouts/WalletV2/controls/WalletButton.qml
  ui/app/AppLayouts/WalletV2/panels/AccountNotFoundPanel.qml
  ui/app/AppLayouts/WalletV2/panels/NetworkFilterPanel.qml
  ui/app/AppLayouts/WalletV2/panels/NetworkSelectPanel.qml
  ui/app/AppLayouts/WalletV2/panels/PKeyAccountDetailsPanel.qml
  ui/app/AppLayouts/WalletV2/panels/SeedPhraseBackupWarningPanel.qml
  ui/app/AppLayouts/WalletV2/panels/WalletFooterPanel.qml
  ui/app/AppLayouts/WalletV2/panels/WalletHeaderPanel.qml
  ui/app/AppLayouts/WalletV2/popups/AddAccountPopup.qml
  ui/app/AppLayouts/WalletV2/popups/AddEditSavedAddressPopup.qml
  ui/app/AppLayouts/WalletV2/popups/CryptoServicesModal.qml
  ui/app/AppLayouts/WalletV2/popups/NetworkSelectPopup.qml
  ui/app/AppLayouts/WalletV2/popups/ShareModal.qml
  ui/app/AppLayouts/WalletV2/popups/SignPhraseModal.qml
  ui/app/AppLayouts/WalletV2/stores/CollectiblesStore.qml
  ui/app/AppLayouts/WalletV2/stores/RootStore.qml
  ui/app/AppLayouts/WalletV2/views/ActivityView.qml
  ui/app/AppLayouts/WalletV2/views/AddAccountView.qml
  ui/app/AppLayouts/WalletV2/views/AssetsView.qml
  ui/app/AppLayouts/WalletV2/views/CollectiblesView.qml
  ui/app/AppLayouts/WalletV2/views/LeftTabView.qml
  ui/app/AppLayouts/WalletV2/views/PositionsView.qml
  ui/app/AppLayouts/WalletV2/views/SavedAddressesView.qml
  ui/app/AppLayouts/WalletV2/views/SeedAddAccountView.qml
  ui/app/AppLayouts/WalletV2/views/SettingsTabView.qml
  ui/app/AppLayouts/WalletV2/views/StackBaseView.qml
  ui/app/AppLayouts/WalletV2/views/StackDetailBase.qml
  ui/app/AppLayouts/WalletV2/views/assets/AssetDetailView.qml
  ui/app/AppLayouts/WalletV2/views/collectibles/CollectibleCollectionView.qml
  ui/app/AppLayouts/WalletV2/views/collectibles/CollectibleDetailView.qml
  ui/app/AppMain.qml
  ui/imports/utils/Constants.qml
Labels: tested

#4804 fix(links): fix editing a link and reflect what the new link shows
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/shared_models/message_item.nim
  src/app/modules/shared_models/message_model.nim
  ui/imports/shared/views/chat/CompactMessageView.qml
  ui/imports/shared/views/chat/LinksMessageView.qml
Labels: tested

#4755 fix: continue showing loading indicator when store fetching failed
  src/app/modules/main/chat_section/chat_content/messages/controller.nim
  src/app/modules/main/chat_section/chat_content/messages/controller_interface.nim
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_controller_delegate_interface.nim
  src/app/modules/main/chat_section/chat_content/messages/view.nim
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim
  src/app/modules/main/chat_section/view.nim
  ui/app/AppLayouts/Chat/stores/MessageStore.qml
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
Labels: tested

#4830 fix(communities): fix pending request to join when receiving new signals
  src/app_service/service/community/service.nim
Labels: tested

#4841 fix(Groups): block add members button for non-admin in group chat
  ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml
Labels: tested

#4839 fix(groups): Fix members count
  ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
Labels: tested

#4763 refactor(@desktop/browser): move provider logic to `status-go`
  src/app/boot/app_controller.nim
  src/app/global/utils.nim
  src/app/modules/main/browser_section/dapps/private_interfaces/module_controller_delegate_interface.nim
  src/app/modules/main/browser_section/dapps/private_interfaces/module_view_delegate_interface.nim
  src/app/modules/main/browser_section/provider/controller.nim
  src/app/modules/main/browser_section/provider/module.nim
  src/app_service/common/network_constants.nim
  src/app_service/service/provider/service.nim
  src/app_service/service/provider/service_interface.nim
  src/backend/provider.nim
  ui/app/AppLayouts/Browser/BrowserLayout.qml
  ui/app/AppLayouts/Browser/popups/BrowserConnectionModal.qml
  ui/app/AppLayouts/Browser/stores/RootStore.qml
  ui/app/AppLayouts/Browser/views/WebProviderObj.qml
Labels: tested

#4847 fix: fix self profile image not showing in the message and fix name
  src/app/modules/main/chat_section/chat_content/messages/controller.nim
  src/app_service/service/contacts/service.nim
  ui/imports/shared/controls/chat/UsernameLabel.qml
  ui/imports/shared/views/chat/CompactMessageView.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: tested

#4819 fix(communities): fix invite link enabling joining twice
  src/app_service/service/community/service.nim
Labels: tested

#4868 fix(@dekstop/chat): higher cpu usage after opening gif selector
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_view_delegate_interface.nim
  src/app/modules/main/chat_section/chat_content/messages/view.nim
  ui/app/AppLayouts/Chat/ChatLayout.qml
  ui/app/AppLayouts/Chat/stores/MessageStore.qml
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/imports/shared/panels/chat/ChatReplyPanel.qml
  ui/imports/shared/status/StatusChatImageLoader.qml
  ui/imports/shared/status/StatusChatInputReplyArea.qml
  ui/imports/shared/status/StatusGifPopup.qml
  ui/imports/shared/views/chat/CompactMessageView.qml
  ui/imports/shared/views/chat/LinksMessageView.qml
  ui/imports/shared/views/chat/MessageView.qml
  ui/imports/shared/views/chat/StatusUpdateView.qml
Labels: tested

#4846 fix(user-list): fix user list section labels
  ui/app/AppLayouts/Chat/ChatLayout.qml
  ui/app/AppLayouts/Chat/panels/UserListPanel.qml
  ui/app/AppLayouts/Chat/panels/communities/CommunityUserListPanel.qml
Labels: tested-issues

#4879 fix(@dekstop/chat): dogfooding_3 crash
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim
Labels: tested

#4876 fix(invitation): fix community invite not showing in 1-1 chats
  src/app/modules/main/activity_center/module.nim
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/main/chat_section/chat_content/module.nim
  src/app/modules/main/communities/controller.nim
  src/app/modules/shared_models/message_item.nim
  src/app/modules/shared_models/message_model.nim
  src/app_service/service/community/service.nim
  src/app_service/service/message/dto/message.nim
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/imports/shared/views/chat/CompactMessageView.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: tested

#4881 fix(@desktop/settings): Store pass to keychain does not validate entered password
  src/app/modules/main/profile_section/privacy/controller.nim
  src/app/modules/main/profile_section/privacy/controller_interface.nim
  src/app/modules/main/profile_section/privacy/io_interface.nim
  src/app/modules/main/profile_section/privacy/module.nim
  src/app/modules/main/profile_section/privacy/view.nim
  src/app_service/service/privacy/service.nim
  ui/app/AppLayouts/Onboarding/shared/CreatePasswordModal.qml
  ui/app/AppLayouts/Onboarding/views/LoginView.qml
  ui/app/AppLayouts/Profile/popups/StoreToKeychainSelectionModal.qml
  ui/app/AppLayouts/Profile/stores/PrivacyStore.qml
  ui/app/AppLayouts/Profile/views/PrivacyView.qml
Labels: tested

#4887 fix(@desktop/wallet): Sign transaction accepts incorrect password
  src/app_service/service/eth/dto/method_dto.nim
  src/app_service/service/transaction/service.nim
  ui/imports/shared/popups/SendModal.qml
  ui/imports/shared/popups/SignTransactionModal.qml
  ui/imports/shared/views/chat/AcceptTransactionView.qml
Labels: tested

#4892 fix(@dekstop/chat): timestamp for `Fetch messages` is wrong
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/shared_models/message_item.nim
  src/app/modules/shared_models/message_model.nim
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/imports/shared/controls/chat/GapComponent.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: tested

#4893 fix(@dekstop/chat): clicking on `enable in settings` redirects to network settings
  ui/app/AppLayouts/Browser/BrowserLayout.qml
  ui/app/AppLayouts/Chat/popups/ActivityCenterPopup.qml
  ui/app/AppLayouts/Chat/popups/PrivateChatPopup.qml
  ui/app/AppLayouts/Profile/ProfileLayout.qml
  ui/app/AppLayouts/Profile/panels/MenuPanel.qml
  ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml
  ui/app/AppLayouts/Profile/views/LeftTabView.qml
  ui/imports/shared/views/chat/LinksMessageView.qml
  ui/imports/utils/Constants.qml
  ui/imports/utils/Global.qml
Labels: tested
