Repository status-im/status-desktop, pull requests merged in 2022-05, with the labels that each got.

#5590 fix(@onboarding): align button with design
  ui/app/AppLayouts/Onboarding/views/WelcomeView.qml
Labels: tested

#5591 fix(@onboarding): asset for import seed phrase
  ui/app/AppLayouts/Onboarding/views/KeysMainView.qml
  ui/imports/assets/png/onboarding/seed-phrase.png
Labels: tested

#5512 fix(StatusEmojiPopup): remove unnecessary spacing
  ui/imports/shared/status/StatusEmojiPopup.qml
  ui/imports/shared/status/StatusEmojiSection.qml
Labels: tested

#5609 fix(@chat): press esc leave create chat view
  ui/app/AppLayouts/Chat/views/CreateChatView.qml
Labels: tested

#5550 fix(@desktop/onboarding): it's impossible to delete a profile image on the onboarding page
  ui/app/AppLayouts/Onboarding/popups/UploadProfilePicModal.qml
  ui/app/AppLayouts/Onboarding/stores/OnboardingStore.qml
  ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
Labels: tested

#5532 fix(InviteFriends): Fix width for names
  ui/app/AppLayouts/Chat/controls/Contact.qml
Labels: tested

#5517 fix(ChatContentView): make replying to messages work again
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
Labels: tested-issues

#5670 fix(@desktop/settings): content on the right side for all subsections need to have the same geometry
  ui/app/AppLayouts/Profile/ProfileLayout.qml
  ui/app/AppLayouts/Profile/controls/WalletNetworkDelegate.qml
  ui/app/AppLayouts/Profile/panels/ContactsListPanel.qml
  ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml
  ui/app/AppLayouts/Profile/views/AboutView.qml
  ui/app/AppLayouts/Profile/views/AdvancedView.qml
  ui/app/AppLayouts/Profile/views/AppearanceView.qml
  ui/app/AppLayouts/Profile/views/BrowserView.qml
  ui/app/AppLayouts/Profile/views/ContactsView.qml
  ui/app/AppLayouts/Profile/views/DevicesView.qml
  ui/app/AppLayouts/Profile/views/HelpView.qml
  ui/app/AppLayouts/Profile/views/LanguageView.qml
  ui/app/AppLayouts/Profile/views/MessagingView.qml
  ui/app/AppLayouts/Profile/views/MyProfileView.qml
  ui/app/AppLayouts/Profile/views/NotificationsView.qml
  ui/app/AppLayouts/Profile/views/PrivacyView.qml
  ui/app/AppLayouts/Profile/views/SettingsContentBase.qml
  ui/app/AppLayouts/Profile/views/SoundsView.qml
  ui/app/AppLayouts/Profile/views/WalletView.qml
  ui/app/AppLayouts/Profile/views/wallet/AccountView.qml
  ui/app/AppLayouts/Profile/views/wallet/DappPermissionsView.qml
  ui/app/AppLayouts/Profile/views/wallet/MainView.qml
  ui/app/AppLayouts/Profile/views/wallet/NetworksView.qml
  ui/app/AppLayouts/Profile/views/wallet/PermissionsListView.qml
  ui/imports/utils/Constants.qml
Labels: tested

#5504 feat(Password): Change minimum password length to 10
  ui/imports/shared/views/PasswordView.qml
Labels: security

#5672 fix(Onboarding/ConfirmationPassword): Remove validation error and enable button only when pw is the expected
  ui/app/AppLayouts/Onboarding/views/ConfirmPasswordView.qml
Labels: bug, onboarding, priority 2: medium, E:Bugfixes

#5391 fix(Messaging/Contacts): The titles of folders in Settings-Messaging are shown very close to the search field
  ui/app/AppLayouts/Profile/views/ContactsView.qml
Labels: bug, tested-issues, E:Bugfixes

#5543 feat(Language&Currency): Add Date & Time Format
  src/app/global/local_account_sensitive_settings.nim
  src/app/global/local_app_settings.nim
  src/app/modules/main/profile_section/language/controller.nim
  src/app/modules/main/profile_section/language/io_interface.nim
  src/app/modules/main/profile_section/language/module.nim
  src/app/modules/main/profile_section/language/view.nim
  ui/app/AppLayouts/Chat/panels/ChatTimePanel.qml
  ui/app/AppLayouts/Profile/stores/LanguageStore.qml
  ui/app/AppLayouts/Profile/views/LanguageView.qml
  ui/app/AppLayouts/Profile/views/SettingsContentBase.qml
  ui/app/mainui/AppSearch.qml
  ui/imports/shared/controls/TransactionDelegate.qml
  ui/imports/shared/controls/chat/FetchMoreMessagesButton.qml
  ui/imports/shared/panels/chat/ChatTimePanel.qml
  ui/imports/shared/views/chat/TransactionBubbleView.qml
  ui/imports/utils/Utils.qml
Labels: Profile, tested

#5491 fix(community): community would appear even if not activated
  src/app/modules/main/controller.nim
  src/app/modules/main/io_interface.nim
  src/app/modules/main/module.nim
  src/app_service/service/community/service.nim
Labels: testing

#5540 feat(@desktop/wallet): greying out already imported/derived addresses in address list and also choosing next available as default one
  src/app/modules/main/wallet_section/accounts/derived_address_item.nim
  src/app/modules/main/wallet_section/accounts/derived_address_model.nim
  src/app/modules/main/wallet_section/accounts/view.nim
  src/app_service/service/wallet_account/derived_address.nim
  ui/app/AppLayouts/Wallet/panels/DerivedAddressesPanel.qml
  ui/app/AppLayouts/Wallet/stores/RootStore.qml
Labels: tested

#5733 fix(@desktop/browser): Can't sign in to Cryptokitties (sing a message to dapp)
  ui/app/AppLayouts/Browser/views/WebProviderObj.qml
Labels: tested

#5752 fix(@desktop/activityCenter): Activity Centre's Activity tool tip is slightly off
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
Labels: tested

#5779 fix(Settings/Messaging/Contacts): Contacts label shows up twice
  ui/app/AppLayouts/Profile/views/ContactsView.qml
Labels: E:Bugfixes

#5777 fix(Onboarding/DisplayName): User is forced to use display name with first case uppercase
  ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
Labels: E:Bugfixes

#5737 fix(@desktop/chat): Show badge and message in activity center for reply elements
  src/app/modules/main/activity_center/controller.nim
  src/app/modules/main/activity_center/item.nim
  src/app/modules/main/activity_center/model.nim
  src/app/modules/main/activity_center/module.nim
  ui/app/AppLayouts/Chat/controls/activityCenter/ReplyComponent.qml
  ui/app/AppLayouts/Chat/panels/ActivityChannelBadgePanel.qml
  ui/app/AppLayouts/Chat/views/ActivityCenterMessageComponentView.qml
Labels: testing

#5727 fix(Chat/FetchMessage): Fetch date is empty in new chats with no messages
  ui/imports/utils/Utils.qml
Labels: bug, E:Bugfixes

#5784 fix(@chat): only show reaction to emoji right click
  ui/app/AppLayouts/stores/MessageStore.qml
  ui/imports/shared/panels/chat/ChatButtonsPanel.qml
  ui/imports/shared/panels/chat/ChatReplyPanel.qml
  ui/imports/shared/views/chat/CompactMessageView.qml
  ui/imports/shared/views/chat/MessageContextMenuView.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: tested

#5788 fix(ChatMessage): hide "edit" option when right click on sticker
  ui/imports/shared/views/chat/MessageContextMenuView.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: tested

#5694 feat(StatusSeedPhraseView): Update layout
  ui/app/AppLayouts/Onboarding/views/SeedPhraseInputView.qml
Labels: testing

#5695 feat(CommunitySettings): add checkbox to allow members to pin messages
  src/app/modules/main/chat_section/chat_content/messages/io_interface.nim
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/main/chat_section/chat_content/messages/view.nim
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/io_interface.nim
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/chat_section/view.nim
  src/app/modules/main/communities/controller.nim
  src/app/modules/main/communities/io_interface.nim
  src/app/modules/main/communities/module.nim
  src/app/modules/main/communities/view.nim
  src/app/modules/main/module.nim
  src/app/modules/shared_models/active_section.nim
  src/app/modules/shared_models/section_item.nim
  src/app/modules/shared_models/section_model.nim
  src/app_service/service/chat/dto/chat.nim
  src/app_service/service/community/dto/community.nim
  src/app_service/service/community/service.nim
  src/backend/communities.nim
  ui/app/AppLayouts/Chat/popups/community/CreateCommunityPopup.qml
  ui/app/AppLayouts/Chat/stores/MessageStore.qml
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/imports/shared/views/chat/CompactMessageView.qml
  ui/imports/shared/views/chat/MessageContextMenuView.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: needs-status-go

#5806 fix(@community): List channel/Add channel/Remove channel from category
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/module.nim
  src/app_service/service/chat/service.nim
  src/app_service/service/community/service.nim
Labels: tested

#5810 fix(@community): invite contact renamed to mutual contact
  ui/imports/shared/views/ExistingContacts.qml
Labels: tested

#5748 fix(@desktop): Persist application window state & geometry
  src/app/global/local_app_settings.nim
  ui/main.qml
Labels: tested

#5813 fix(CreatePassword): evaluation added on text changed
  ui/imports/shared/views/PasswordView.qml
Labels: tested

#5772 fix(gifs): Change `Image` to `AnimatedImage` in StatusImageModal
  ui/imports/shared/status/StatusImageModal.qml
Labels: tested

#5750 feat(@desktop/browser): wrong screen is shown when claiming tokens in simpledapp.eth
  ui/app/AppLayouts/Browser/BrowserLayout.qml
  ui/app/mainui/AppMain.qml
Labels: tested

#5785 fix(@desktop/profile): changing username is not immediately updating
  src/app/boot/app_controller.nim
  src/app/global/user_profile.nim
  src/app/modules/main/profile_section/profile/controller.nim
  src/app/modules/main/profile_section/profile/module.nim
  src/app_service/service/contacts/service.nim
  src/app_service/service/profile/service.nim
  src/app_service/service/settings/dto/settings.nim
  src/app_service/service/settings/service.nim
Labels: tested

#5755 fix(communities) validate privkey when importing a community
  ui/app/AppLayouts/Chat/popups/community/AccessExistingCommunityPopup.qml
Labels: tested

#5648 feat(@desktop/profile): add ephemeral notifications
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/controller.nim
  src/app/modules/main/ephemeral_notification_item.nim
  src/app/modules/main/ephemeral_notification_model.nim
  src/app/modules/main/io_interface.nim
  src/app/modules/main/module.nim
  src/app/modules/main/view.nim
  ui/app/AppLayouts/Browser/BrowserLayout.qml
  ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
  ui/app/AppLayouts/Profile/views/EnsView.qml
  ui/app/mainui/AppMain.qml
  ui/imports/shared/popups/SendModal.qml
  ui/imports/shared/popups/SignTransactionModal.qml
  ui/imports/shared/popups/qmldir
  ui/imports/utils/Constants.qml
  ui/imports/utils/Global.qml
Labels: tested

#5898 fix(Settings/Messaging): Spacing is wrong between “System Default Browser” and separator
  ui/app/AppLayouts/Profile/views/MessagingView.qml
Labels: tested, E:Bugfixes

#5863 fix(@desktop/wallet): show all tokens in wallet that have balance > 0
  src/app/modules/main/browser_section/current_account/module.nim
  src/app/modules/main/browser_section/current_account/view.nim
  src/app/modules/main/wallet_section/accounts/module.nim
  src/app/modules/main/wallet_section/current_account/module.nim
  src/app/modules/main/wallet_section/current_account/view.nim
  src/app_service/service/accounts/service.nim
  src/app_service/service/wallet_account/async_tasks.nim
  src/app_service/service/wallet_account/dto.nim
  src/app_service/service/wallet_account/service.nim
Labels: tested

#5895 feat(Community/Logo): use image crop approach for community Logo
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/io_interface.nim
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/chat_section/view.nim
  src/app_service/service/community/service.nim
  ui/app/AppLayouts/Chat/panels/communities/CommunityEditSettingsPanel.qml
  ui/app/AppLayouts/Chat/panels/communities/CommunityOverviewSettingsPanel.qml
  ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
  ui/imports/shared/popups/BannerCropperModal.qml
Labels: tested
