Repository status-im/status-desktop, pull requests merged in 2022-06, with the labels that each got.

#5963 fix(Communities): loading of new images for logo and banner
  ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
  ui/imports/shared/panels/EditCroppedImagePanel.qml
  ui/imports/shared/popups/ImageCropWorkflow.qml
  ui/imports/shared/popups/qmldir
Labels: tested

#5936 fix(@desktop/browser): need empty screen for “DApp Permissions” screen
  ui/app/AppLayouts/Profile/views/BrowserView.qml
Labels: tested

#5896 feat(settings): Adding new Backup Seed Phrase section & modal
  ui/app/AppLayouts/Profile/panels/MenuPanel.qml
  ui/app/AppLayouts/Profile/popups/BackupSeedModal.qml
  ui/app/AppLayouts/Profile/popups/backupseed/Acknowledgements.qml
  ui/app/AppLayouts/Profile/popups/backupseed/Backup.qml
  ui/app/AppLayouts/Profile/popups/backupseed/BackupSeedStepBase.qml
  ui/app/AppLayouts/Profile/popups/backupseed/ConfirmSeedPhrasePanel.qml
  ui/app/AppLayouts/Profile/popups/backupseed/ConfirmStoringSeedPhrasePanel.qml
  ui/app/AppLayouts/Profile/popups/backupseed/TabBarButton.qml
  ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml
  ui/app/AppLayouts/Profile/views/LeftTabView.qml
  ui/app/AppLayouts/Profile/views/PrivacyView.qml
  ui/app/mainui/AppMain.qml
  ui/imports/utils/Constants.qml
Labels: tested

#5889 fix(onboarding): fixing onboarding layout ctx positioning issues
  ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
  ui/app/AppLayouts/Onboarding/views/KeysMainView.qml
  ui/app/AppLayouts/Onboarding/views/WelcomeView.qml
Labels: tested

#5965 fix(Onboarding): Insert user details layout issues
  ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
  ui/imports/assets/icons/onboarding/chains.svg
  ui/imports/assets/png/onboarding/chains.png
Labels: tested

#5947 fix(ContactPanel): updated right button colors when hovered
  ui/app/AppLayouts/Profile/panels/ContactPanel.qml
Labels: tested

#5964 fix(ChatInput): Mentions have very bad color/contrast ratio in dark mode
  ui/imports/utils/Constants.qml
Labels: ui, Chat, tested, E:Bugfixes

#5948 fix(Profile/LeftTabView): menu should not scroll horizontally
  ui/app/AppLayouts/Profile/views/LeftTabView.qml
Labels: tested

#5943 fix(appmain): Fix multiple creations of mailservers-not-working popup
  ui/app/mainui/AppMain.qml
Labels: tested

#5916 feat(chat): Add crow to admins in group chat
  ui/app/AppLayouts/Chat/panels/UserListPanel.qml
Labels: tested

#6031 fix(Community/InvitationBubble): Community invitation doesn't look good
  ui/imports/shared/views/chat/InvitationBubbleView.qml
Labels: Communities, tested, E:Bugfixes

#6009 feat(CommunityOverview): Add Community Overview banners
  ui/app/AppLayouts/Chat/ChatLayout.qml
  ui/app/AppLayouts/Chat/panels/communities/CommunityBanner.qml
  ui/app/AppLayouts/Chat/panels/communities/CommunityOverviewSettingsPanel.qml
  ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
  ui/imports/assets/icons/communities/airdrop.svg
  ui/imports/assets/icons/communities/backup-community.svg
Labels: tested

#6014 fix(Chat): Messages with GIF not display the url
  ui/app/AppLayouts/Profile/views/EnsListView.qml
  ui/imports/shared/views/chat/ChatTextView.qml
  ui/imports/shared/views/chat/CompactMessageView.qml
  ui/imports/shared/views/chat/MessageView.qml
  ui/imports/utils/Utils.qml
Labels: tested

#6016 fix(StatusChatInput): Fix emoji button click arguments
  ui/imports/shared/status/StatusChatInput.qml
Labels: tested

#6045 fix(@desktop/wallet): Wallet balance is 0 when enabling multinetwork toggle
  src/app/modules/main/wallet_section/accounts/module.nim
  src/app/modules/main/wallet_section/module.nim
Labels: tested

#5918 fix(Communities): Fix import community without chats
  src/app_service/service/community/service.nim
Labels: tested, needs-status-go

#6087 fix(chat): Fix checking admin privilages
  src/app/modules/main/chat_section/module.nim
Labels: tested

#5905 fix(@desktop/profile): Contact requests should support a message
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/io_interface.nim
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/chat_section/view.nim
  src/app/modules/main/profile_section/contacts/controller.nim
  src/app/modules/main/profile_section/contacts/io_interface.nim
  src/app/modules/main/profile_section/contacts/module.nim
  src/app/modules/main/profile_section/contacts/view.nim
  src/app_service/service/activity_center/dto/notification.nim
  src/app_service/service/contacts/service.nim
  src/backend/contacts.nim
  ui/app/AppLayouts/Chat/popups/ContactRequestsPopup.qml
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Profile/popups/SendContactRequestModal.qml
  ui/app/AppLayouts/Profile/stores/ContactsStore.qml
  ui/app/AppLayouts/Profile/views/ContactsView.qml
  ui/imports/shared/popups/ProfilePopup.qml
Labels: tested-issues

#5993 fix: ensure sync community settings are handled
  src/app/core/signals/remote_signals/messages.nim
  src/app_service/service/community/service.nim
Labels: needs-status-go

#6008 fix(GroupChatPanel): drop down was showing empty entries
  ui/app/AppLayouts/Chat/panels/GroupChatPanel.qml
  ui/app/AppLayouts/Chat/views/CreateChatView.qml
Labels: tested

#6117 fix(settings): Fix visibility community settings view
  ui/app/AppLayouts/Profile/panels/MenuPanel.qml
  ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml
  ui/app/AppLayouts/Profile/views/LeftTabView.qml
Labels: tested

#6147 fix(Onboarding): User is able to bypass validation of username when using keyboard
  ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
Labels: bug, onboarding, tested, priority 1: high, E:Onboarding, E:Bugfixes

#6088 fix(@desktop/general): Fix application not responding on close
  src/app_service/service/wallet_account/service.nim
Labels: tested

#6148 fix(Onboarding): Centered onboarding layouts
  ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
  ui/app/AppLayouts/Onboarding/views/KeysMainView.qml
  ui/app/AppLayouts/Onboarding/views/WelcomeView.qml
Labels: tested, E:Testing

#5682 Replace plus button in community by adhoc btn and add buton at the bottom
  src/app/modules/main/chat_section/chat_content/controller.nim
  src/app/modules/main/chat_section/chat_content/users/controller.nim
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/profile_section/notifications/controller.nim
  src/app_service/service/activity_center/service.nim
  src/app_service/service/chat/service.nim
  ui/app/AppLayouts/Chat/views/ChatColumnView.qml
  ui/app/AppLayouts/Chat/views/ChatView.qml
  ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
  ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
  ui/app/AppLayouts/Chat/views/CreateChatView.qml
  ui/app/AppLayouts/Chat/views/qmldir
  ui/app/mainui/AppMain.qml
  ui/imports/utils/Global.qml
Labels: tested

#5980 fix(@desktop/wallet): estimated time for transaction is always Unknown
  src/app/modules/main/wallet_section/transactions/controller.nim
  src/app/modules/main/wallet_section/transactions/io_interface.nim
  src/app/modules/main/wallet_section/transactions/module.nim
  src/app/modules/main/wallet_section/transactions/view.nim
  src/app_service/service/transaction/service.nim
  src/backend/eth.nim
  ui/app/AppLayouts/stores/RootStore.qml
  ui/imports/shared/controls/GasSelector.qml
  ui/imports/shared/popups/SendModal.qml
  ui/imports/shared/views/SendModalFooter.qml
  ui/imports/utils/Constants.qml
  ui/imports/utils/Utils.qml
Labels: tested

#6153 fix(CommunitySettingsView): add missing membership request modal
  ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
Labels: tested

#6001 fix(Profile): ContactsView layout and scrolling issues
  ui/app/AppLayouts/Profile/ProfileLayout.qml
  ui/app/AppLayouts/Profile/panels/ContactsListPanel.qml
  ui/app/AppLayouts/Profile/views/ContactsView.qml
  ui/app/AppLayouts/Profile/views/SettingsContentBase.qml
Labels: tested

#6215 fix(ActivityCenter): Activity center button is not active when activity center is opened
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
Labels: bug, ui, tested, E:Bugfixes

#6214 fix(@wallet): address input keep loading
  src/app/modules/main/module.nim
  ui/imports/shared/controls/ContactsListAndSearch.qml
Labels: tested

#6208 feat(CommunitiesPortal): Enable Communities portal & update chat menu
  src/app/global/local_account_sensitive_settings.nim
  src/app/modules/main/module.nim
  ui/app/AppLayouts/Chat/popups/qmldir
  ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
  ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml
  ui/app/AppLayouts/CommunitiesPortal/popups/CreateCommunityPopup.qml
  ui/app/AppLayouts/CommunitiesPortal/stores/CommunitiesStore.qml
  ui/app/AppLayouts/Profile/views/AdvancedView.qml
  ui/app/AppLayouts/stores/RootStore.qml
  ui/imports/shared/stores/RootStore.qml
Labels: Communities, tested, feature, priority F2: important, E:Communities, S:1

#6233 fix(chat): Open chat when contact request was accepted
  src/app/modules/main/chat_section/module.nim
Labels: tested

#6227 fix(chat): fix switching back to chats is very slow
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/imports/shared/controls/chat/UserImage.qml
  ui/imports/utils/Utils.qml
Labels: tested
