Repository status-im/status-desktop, pull requests merged in 2023-09, with the labels that each got.

#12103 fix(Airdrop): Update owner and tmaster tokens visualization in airdrop's list
  ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
Labels: bug, E:Desktop Token Master

#12107 fix(Permissions): Tweak to Owner and TokenMaster permissions wording
  ui/app/AppLayouts/Communities/controls/PermissionTypes.qml
Labels: bug, E:Desktop Comm Perms and Minting MVP

#12139 feat(@desktop/wallet): Enable Collectibles tab before token is selected
  storybook/pages/TokenListViewPage.qml
  ui/app/AppLayouts/Wallet/WalletLayout.qml
  ui/app/AppLayouts/Wallet/stores/RootStore.qml
  ui/app/AppLayouts/Wallet/views/RightTabView.qml
  ui/app/mainui/AppMain.qml
  ui/imports/shared/controls/CollectibleBackButtonWithInfo.qml
  ui/imports/shared/controls/SearchBoxWithRightIcon.qml
  ui/imports/shared/panels/HoldingItemSelector.qml
  ui/imports/shared/panels/HoldingSelector.qml
  ui/imports/shared/popups/SendModal.qml
  ui/imports/shared/stores/TransactionStore.qml
  ui/imports/shared/views/TokenListView.qml
Labels: tested

#12137 fix(MintTokens): Network chosen locks in the network used for all future tokens minted for that community
  storybook/pages/NetworkFilterPage.qml
  storybook/src/Models/MintedTokensModel.qml
  ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
  ui/app/AppLayouts/Communities/views/EditCommunityTokenView.qml
  ui/app/AppLayouts/Communities/views/EditOwnerTokenView.qml
  ui/app/AppLayouts/Communities/views/MintedTokensView.qml
  ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml
  ui/app/AppLayouts/Wallet/helpers/NetworkModelHelpers.qml
  ui/app/AppLayouts/Wallet/helpers/qmldir
Labels: bug, E:Desktop Comm Perms and Minting MVP

#11995 Feat/token permissions pending state
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/communities/module.nim
  src/app/modules/shared_models/token_permission_item.nim
  src/app/modules/shared_models/token_permissions_model.nim
  src/app_service/service/community/dto/community.nim
  src/app_service/service/community/service.nim
  storybook/pages/CommunityPermissionsSettingsPanelEditor.qml
  storybook/src/Models/PermissionsModel.qml
  ui/app/AppLayouts/Communities/controls/PermissionItem.qml
  ui/app/AppLayouts/Communities/controls/PermissionTypes.qml
Labels: tested-issues

#12191 release 0.14: update status-go
  VERSION
Labels: tested

#12158 refactor(section_details): simplify section_details to only contain needed props
  src/app/modules/main/communities/view.nim
  src/app/modules/main/controller.nim
  src/app/modules/main/io_interface.nim
  src/app/modules/main/module.nim
  src/app/modules/main/view.nim
  src/app/modules/shared_models/section_details.nim
  src/app/modules/shared_models/section_item.nim
Labels: refactor

#12212 feat(TransferOwnershipAlertPopup): Add information popups when owner token is not created yet
  storybook/figma.json
  storybook/pages/TransferOwnershipAlertPopupPage.qml
  ui/app/AppLayouts/Communities/panels/OverviewSettingsPanel.qml
  ui/app/AppLayouts/Communities/popups/TransferOwnershipAlertPopup.qml
  ui/app/AppLayouts/Communities/popups/qmldir
  ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
Labels: feature, E:Desktop Tokenized Ownership

#12144 fix(StatusChatInput): Sent message image attachment persists when changing chat types
  ui/imports/shared/status/StatusChatInput.qml
Labels: bug

#12223 feat(CommunityOwnership): Add transfer ownership popup flow from wallet collectible view
  ui/app/AppLayouts/Communities/popups/TransferOwnershipPopup.qml
  ui/app/AppLayouts/Wallet/WalletLayout.qml
  ui/app/AppLayouts/Wallet/panels/WalletFooter.qml
  ui/app/AppLayouts/Wallet/stores/RootStore.qml
  ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
  ui/app/AppLayouts/Wallet/views/collectibles/CollectibleDetailView.qml
  ui/app/mainui/AppMain.qml
  ui/imports/shared/popups/send/SendModal.qml
Labels: feature, E:Desktop Tokenized Ownership

#12273 fix(Wallet/Collectibles): Applied special collectible format only to community special collectibles
  src/app/modules/shared_models/collectible_details_entry.nim
  src/app/modules/shared_models/collectibles_utils.nim
  ui/app/AppLayouts/Wallet/WalletLayout.qml
  ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
  ui/app/AppLayouts/Wallet/views/collectibles/CollectibleDetailView.qml
  ui/app/AppLayouts/Wallet/views/collectibles/CollectibleView.qml
Labels: bug, E:Desktop Tokenized Ownership
