Repository status-im/status-desktop, pull requests merged in 2023-06, with the labels that each got.

#10775 Revert Chat model sorting in Nim and go back to SortFilterProxy because of performance issue
  src/app/modules/main/chat_section/model.nim
  ui/StatusQ/src/StatusQ/Components/StatusChatList.qml
  ui/StatusQ/src/StatusQ/Components/StatusChatListAndCategories.qml
Labels: tested

#10891 desktop(DOtherSide): Set env var before creating gui app
  src/nim_status_client.nim
  vendor/DOtherSide/lib/src/DOtherSide.cpp
Labels: bug, tested, priority F0: urgent

#10846 feat(@desktop/wallet): Added NFT preview
  ui/app/AppLayouts/Wallet/panels/WalletNftPreview.qml
  ui/app/AppLayouts/Wallet/panels/qmldir
  ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml
Labels: tested

#10896 makefile: fix MacOS builds, restore missing env vars
  Makefile
Labels: ci

#10832 feat(@desktop/wallet): Transactions values
  storybook/pages/TransactionDetailViewPage.qml
  storybook/stubs/shared/stores/RootStore.qml
  ui/app/AppLayouts/Wallet/popups/TransactionAddressMenu.qml
  ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml
  ui/imports/shared/controls/TransactionDataTile.qml
Labels: tested

#10921 fix: Wallet: Authentication popup is broken
  ui/imports/shared/popups/keycard/KeycardPopup.qml
  ui/imports/shared/popups/keycard/states/EnterPassword.qml
Labels: tested

#10085 refactor(communities): remove legacy pending membership indicator
  ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Labels: || stagnant ||

#10949 fix(@desktop/keycard/wallet): Small fixes
  ui/imports/shared/controls/TransactionDelegate.qml
  ui/imports/shared/popups/keycard/states/KeycardConfirmation.qml
Labels: bug

#10928 fix: Create only one instance of `StatusChatInput`
  src/app/modules/main/chat_section/chat_content/chat_details.nim
  src/app/modules/main/chat_section/chat_content/controller.nim
  src/app/modules/main/chat_section/chat_content/input_area/item.nim
  src/app/modules/main/chat_section/chat_content/input_area/model.nim
  src/app/modules/main/chat_section/chat_content/input_area/preserved_properties.nim
  src/app/modules/main/chat_section/chat_content/input_area/view.nim
  src/app/modules/main/chat_section/chat_content/module.nim
  src/app/modules/main/chat_section/chat_content/view.nim
  ui/StatusQ/src/StatusQ/Controls/StatusChatCommandButton.qml
  ui/app/AppLayouts/Chat/views/ChatColumnView.qml
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/app/AppLayouts/Chat/views/ChatView.qml
  ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
  ui/imports/shared/status/StatusChatInput.qml
  ui/imports/shared/status/StatusChatInputImageArea.qml
  ui/imports/shared/status/StatusGifPopup.qml
  ui/imports/shared/status/StatusStickerPackIconWithIndicator.qml
  ui/imports/shared/status/StatusStickersPopup.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: tested

#10942 fix(@wallet): hide watch only account
  src/app/modules/main/wallet_section/accounts/io_interface.nim
  src/app/modules/main/wallet_section/accounts/module.nim
  src/app/modules/main/wallet_section/filter.nim
  src/app/modules/main/wallet_section/module.nim
  src/app/modules/main/wallet_section/overview/io_interface.nim
  src/app/modules/main/wallet_section/overview/module.nim
  ui/app/AppLayouts/Wallet/views/LeftTabView.qml
Labels: tested

#10992 fix(MintToken): App crash when trying to create new token
  ui/app/AppLayouts/Chat/views/communities/CommunityNewTokenView.qml
Labels: E:Bugfixes

#11007 fix(@wallet): left bar selection
  src/app/modules/main/wallet_section/module.nim
  src/app/modules/main/wallet_section/view.nim
  ui/app/AppLayouts/Wallet/views/LeftTabView.qml
Labels: tested

#11055 fix(@desktop/wallet): return transaction list even if nft metadata fe…
  src/app_service/service/transaction/async_tasks.nim
Labels: tested

#11065 ci: upgrade to GCC 11 to match build outside Docker
  ci/Dockerfile
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.tests-nim
Labels: ci, linux, dependencies

#11068 fix(@wallet): send modal max link
  ui/imports/shared/popups/SendModal.qml
Labels: tested

#11101 feat(AirdropAssets): Enable assets tab in airdrop dropdown
  storybook/pages/CommunityAirdropsSettingsPanelPage.qml
  storybook/pages/CommunityNewAirdropViewPage.qml
  storybook/pages/HoldingsDropdownPage.qml
  storybook/src/Models/AssetsModel.qml
  ui/app/AppLayouts/Chat/controls/community/ExtendedDropdownContent.qml
  ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml
  ui/app/AppLayouts/Chat/controls/community/ListDropdownContent.qml
  ui/app/AppLayouts/Chat/panels/communities/CommunityAirdropsSettingsPanel.qml
  ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml
  ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
  ui/app/AppLayouts/Chat/views/communities/CommunityNewAirdropView.qml
Labels: Communities, feature, qml

#11111 fix(Storybook): reenable inspection tool for popup pages
  storybook/main.qml
Labels: tested

#11165 fix: InDropdown scrollable height
  ui/app/AppLayouts/Chat/controls/community/InDropdown.qml
Labels: tested

#11106 fix(StatusQ): Dynamic width calculation for StatusMenu
  ui/StatusQ/src/StatusQ/Popups/StatusMenu.qml
  ui/StatusQ/src/StatusQ/Popups/StatusMenuItem.qml
  ui/imports/shared/controls/chat/ProfileHeader.qml
  ui/imports/shared/panels/EditCroppedImagePanel.qml
  ui/imports/shared/popups/UserStatusContextMenu.qml
  ui/imports/shared/views/ProfileDialogView.qml
  ui/imports/shared/views/chat/ProfileContextMenu.qml
Labels: tested

#10940 ci: fix installation of windows build dependencies
  scripts/windows_build_setup.ps1
Labels: ci, windows, dependencies

#11195 fix: chat input preserved properties bugs
  ui/app/AppLayouts/Chat/views/ChatColumnView.qml
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/imports/shared/status/StatusChatInput.qml
Labels: tested

#11248 ci: retry nim_status_client build 3 times
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.tests-e2e
Labels: ci, linux

#11216 feat: use last know channelPermissionResponse data in UI
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/module.nim
  src/app_service/service/chat/async_tasks.nim
  src/app_service/service/chat/dto/chat.nim
  src/app_service/service/chat/service.nim
  src/app_service/service/community/async_tasks.nim
  src/app_service/service/community/dto/community.nim
  src/app_service/service/community/service.nim
  src/backend/communities.nim
Labels: needs-status-go

#11264 fix(@desktop/onboarding): Keycard -> Factory reset button is not calling any action
  ui/app/AppLayouts/Onboarding/OnboardingLayout.qml
Labels: tested

#8705 fleets.json: drop decomissioned eth.test fleet
  Makefile
  fleets.json
  libs/Onboarding/src/Onboarding/Accounts/AccountsService.cpp
  libs/Onboarding/src/Onboarding/Accounts/AccountsService.h
  libs/Onboarding/src/Onboarding/Common/Constants.h
  resources/CMakeLists.txt
  resources/fleets_cpp.json
  src/app/core/fleets/fleet_configuration.nim
  src/app_service/service/settings/dto/settings.nim
  src/app_service/service/settings/service.nim
  ui/app/AppLayouts/Profile/popups/FleetsModal.qml
  ui/imports/utils/Constants.qml
Labels: || stagnant ||

#11355 feat(Communities): Moved dropdown qml components from `controls` to `popups`
  storybook/pages/HoldingsDropdownPage.qml
  storybook/pages/InDropdownPage.qml
  storybook/pages/MembersDropdownPage.qml
  ui/app/AppLayouts/Communities/controls/qmldir
  ui/app/AppLayouts/Communities/popups/HoldingsDropdown.qml
  ui/app/AppLayouts/Communities/popups/InDropdown.qml
  ui/app/AppLayouts/Communities/popups/MembersDropdown.qml
  ui/app/AppLayouts/Communities/popups/PermissionsDropdown.qml
  ui/app/AppLayouts/Communities/popups/RecipientTypeSelectionDropdown.qml
  ui/app/AppLayouts/Communities/popups/qmldir
  ui/app/AppLayouts/Communities/views/EditPermissionView.qml
Labels: ui-team, refactor, feature, qml
