Repository status-im/status-desktop, pull requests merged in 2023-10, with the labels that each got.

#12319 fix(messenger_contacts): Add toast notification when removing a contact
  src/app/core/notifications/details.nim
  src/app/core/notifications/notifications_manager.nim
  src/app/global/global_events.nim
  src/app/modules/main/module.nim
  src/app_service/service/contacts/service.nim
Labels: bug

#12278 fix(messenger_contacts): Fix target name in confirm dialog for contact remove
  ui/imports/shared/views/ProfileDialogView.qml
Labels: bug

#12340 chore(ci): drop temporary Nim client build fix
  ci/Jenkinsfile.linux
Labels: ci, linux

#12390 fix(Onboarding): Recover from seed - Fetching data screen layout
  ui/app/AppLayouts/Onboarding/views/ProfileFetchingView.qml
Labels: bug

#12385 feat(Advanced): Add toggle to enable managing community on testnet
  ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
  ui/app/AppLayouts/Profile/views/AdvancedView.qml
  ui/app/mainui/AppMain.qml
Labels: feature

#12353 fix(JoinCommunity): Unable to join community
  ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
Labels: bug, do not merge

#12258 update status/wakuv2 fleets DNS discovery enrtree
  libs/Onboarding/src/Onboarding/Accounts/AccountsService.cpp
  src/app_service/service/accounts/service.nim
  src/app_service/service/node_configuration/service.nim
Labels: tested

#12531 fix(ci): use linux.bundle() to add credentials
  ci/Jenkinsfile.tests-e2e
Labels: ci, linux

#12527 feat(ci): trigger new E2E run after Linux build
  ci/Jenkinsfile.linux
Labels: ci, linux

#12482 feature: copy channel link menu action
  ui/imports/shared/views/chat/ChatContextMenuView.qml
  ui/imports/utils/Utils.qml
Labels: E:Desktop New Share URL Format

#12555 feat(ci): trigger E2E from meta build for releases
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.linux
Labels: ci

#12536 chore(ci): upgrade Jenkins library to 1.8.0
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.tests-e2e
  ci/Jenkinsfile.tests-nim
  ci/Jenkinsfile.tests-statusq
  ci/Jenkinsfile.tests-ui
  ci/Jenkinsfile.windows
  ci/cpp/Jenkinsfile.linux
  ci/cpp/Jenkinsfile.macos
  ci/cpp/Jenkinsfile.windows
Labels: ci
