Repository status-im/status-desktop, pull requests merged in 2023-03, with the labels that each got.

#9677 ci: remove submodule vendor folders to save space
  scripts/clean-git.sh
Labels: ci

#9749 ci(e2e): Updated squish version from 6.7.2 to 7.1-SNAPSHOT
  ci/Jenkinsfile.e2e
  test/ui-test/README.md
Labels: ci, squish

#9706 fix(@desktop/wallet): keypairs are displayed wrongly after account removal
  src/app/modules/main/wallet_section/accounts/item.nim
  src/app/modules/main/wallet_section/accounts/utils.nim
  src/app/modules/main/wallet_section/accounts/view.nim
  src/app/modules/main/wallet_section/current_account/module.nim
  src/app/modules/shared_modules/keycard_popup/module.nim
  src/app_service/service/wallet_account/service.nim
Labels: tested

#9477 refactor: load gifs asynchronously
  src/app/boot/app_controller.nim
  src/app/modules/main/chat_section/chat_content/input_area/controller.nim
  src/app/modules/main/chat_section/chat_content/input_area/io_interface.nim
  src/app/modules/main/chat_section/chat_content/input_area/module.nim
  src/app/modules/main/chat_section/chat_content/input_area/view.nim
  src/app/modules/main/chat_section/chat_content/module.nim
  src/app_service/service/gif/async_tasks.nim
  src/app_service/service/gif/service.nim
  src/backend/gifs.nim
Labels: tested

#9487 refactor: load recent stickers asynchronously
  src/app/modules/main/stickers/controller.nim
  src/app/modules/main/stickers/io_interface.nim
  src/app/modules/main/stickers/module.nim
  src/app/modules/main/stickers/view.nim
  src/app_service/service/stickers/async_tasks.nim
  src/app_service/service/stickers/service.nim
  ui/imports/shared/status/StatusStickersPopup.qml
Labels: tested

#9727 refactor(communities): refactor communities cache in service
  src/app/modules/main/chat_section/controller.nim
  src/app_service/service/community/service.nim
  src/backend/communities.nim
Labels: tested

#9808 refactor(community-service): merge curatedCommunities in communities
  src/app/modules/main/communities/controller.nim
  src/app/modules/main/communities/io_interface.nim
  src/app/modules/main/communities/module.nim
  src/app_service/service/community/async_tasks.nim
  src/app_service/service/community/dto/community.nim
  src/app_service/service/community/service.nim
  ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml
Labels: tested

#9954 refactor(gifs): lazy load tenor api key + make search async
  src/app/modules/main/chat_section/chat_content/input_area/controller.nim
  src/app/modules/main/chat_section/chat_content/input_area/io_interface.nim
  src/app/modules/main/chat_section/chat_content/input_area/module.nim
  src/app/modules/main/chat_section/chat_content/input_area/view.nim
  src/app_service/service/gif/async_tasks.nim
  src/app_service/service/gif/service.nim
  ui/imports/shared/status/StatusGifPopup.qml
  ui/imports/shared/status/StatusGifPopup/EmptyPlaceholder.qml
  ui/imports/shared/stores/RootStore.qml
Labels: tested

#9744 fix(chat): Sent images with text correctly
  src/app/modules/main/activity_center/module.nim
  src/app/modules/main/chat_section/chat_content/input_area/controller.nim
  src/app/modules/main/chat_section/chat_content/input_area/io_interface.nim
  src/app/modules/main/chat_section/chat_content/input_area/module.nim
  src/app/modules/main/chat_section/chat_content/input_area/view.nim
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/main/chat_section/chat_content/module.nim
  src/app/modules/shared_models/message_item.nim
  src/app/modules/shared_models/message_model.nim
  src/app_service/service/chat/service.nim
  src/app_service/service/message/dto/message.nim
  src/backend/chat.nim
  test/nim/message_model_test.nim
  ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
  ui/StatusQ/src/StatusQ/Components/StatusMessageDetails.qml
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: tested, needs-status-go

#10064 fix(unread): fix badge disappearing because of wrong calculation
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/io_interface.nim
  src/app/modules/main/chat_section/model.nim
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/io_interface.nim
  src/app/modules/main/module.nim
  src/app/modules/shared_models/section_model.nim
  src/app_service/service/chat/service.nim
  src/app_service/service/community/service.nim
  src/app_service/service/message/async_tasks.nim
Labels: tested
