Repository status-im/status-desktop, pull requests merged in 2023-01, with the labels that each got.

#8872 fix(improvements): remove console warnings pt1
  ui/StatusQ/src/StatusQ/Layout/StatusAppNavBar.qml
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
  ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml
  ui/app/AppLayouts/Wallet/popups/NetworkSelectPopup.qml
  ui/app/AppLayouts/Wallet/stores/RootStore.qml
  ui/app/AppLayouts/Wallet/views/RightTabView.qml
  ui/app/mainui/AppMain.qml
  ui/imports/assets/png/browser/compass.png
  ui/imports/shared/controls/InformationTag.qml
  ui/imports/shared/popups/PopupMenu.qml
Labels: E:Bugfixes

#9028 fix(SQ/StatusListItemTag): Text is not horizontally centered
  ui/StatusQ/src/StatusQ/Components/StatusListItemTag.qml
Labels: E:Bugfixes, ui-improvements

#9003 feat(ActivityCenter): Update ActivityNotificationMessage's text maximum width
  ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml
Labels: tested-issues

#9027 fix(Community): banners where overlapping
  ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Labels: ui

#9063 fix(Community Permissions): Remove (hide) minting and import option in assets dropdown
  ui/app/AppLayouts/Chat/controls/community/ExtendedDropdownContent.qml
Labels: ui

#8974 fix(StatusChatInput): fixed paste action doesn't work
  ui/imports/shared/status/StatusChatInput.qml
Labels: tested

#9074 fix(Community Permissions): Update `PermissionItem` according to the new design
  ui/app/AppLayouts/Chat/controls/community/PermissionItem.qml
Labels: ui, ui-improvements

#9059 fix(Community Permissions): Update change detected buttons labels according to the new design
  ui/app/AppLayouts/Chat/layouts/SettingsPageLayout.qml
  ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
  ui/imports/shared/popups/SettingsDirtyToastMessage.qml
Labels: ui, Communities, E:Bugfixes, E:Communities

#9081 fix(Community Permissions): Update `Who holds` add new item with always AND action
  storybook/pages/CommunityPermissionsSettingItemEditor.qml
  storybook/pages/CommunityPermissionsSettingsPanelEditor.qml
  storybook/pages/HoldingsDropdownPage.qml
  ui/StatusQ/src/StatusQ/Core/Utils/OperatorsUtils.qml
  ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml
  ui/app/AppLayouts/Chat/controls/community/OperatorsSelector.qml
  ui/app/AppLayouts/Chat/controls/community/PermissionItem.qml
  ui/app/AppLayouts/Chat/stores/CommunitiesStore.qml
  ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
Labels: ui, Communities, E:Communities

#9083 fix(Community Permissions): Update `tokens` names to `assets`
  storybook/pages/CommunityNewPermissionViewPage.qml
  storybook/pages/CommunityPermissionsSettingsPanelEditor.qml
  storybook/pages/CommunityPermissionsSettingsPanelPage.qml
  storybook/pages/HoldingsDropdownPage.qml
  storybook/src/Models/AssetsCollectiblesIconsModel.qml
  storybook/src/Models/AssetsModel.qml
  storybook/src/Models/ModelsData.qml
  storybook/src/Models/PermissionsModel.qml
  storybook/src/Models/qmldir
  ui/app/AppLayouts/Chat/controls/community/AssetsPanel.qml
  ui/app/AppLayouts/Chat/controls/community/ExtendedDropdownContent.qml
  ui/app/AppLayouts/Chat/controls/community/HoldingTypes.qml
  ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml
  ui/app/AppLayouts/Chat/helpers/CommunityPermissionsHelpers.qml
  ui/app/AppLayouts/Chat/stores/CommunitiesStore.qml
  ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
Labels: Communities, E:Communities

#9141 fix(@desktop/onboarding): recover account crash fixed
  src/app/modules/startup/models/fetching_data_item.nim
Labels: tested

#9123 feat(@desktop/onboarding): onboarding - recover account flow - UI adjustments
  src/app/modules/shared_modules/keycard_popup/module.nim
  src/app/modules/startup/internal/recover_old_user_state.nim
  src/app/modules/startup/internal/state.nim
  src/app/modules/startup/internal/state_factory.nim
  src/app/modules/startup/internal/welcome_state_old_user.nim
  src/app/modules/startup/module.nim
  ui/app/AppLayouts/Onboarding/OnboardingLayout.qml
  ui/app/AppLayouts/Onboarding/views/KeysMainView.qml
  ui/imports/utils/Constants.qml
Labels: tested

#9129 Fix message view quick actions regression
  ui/imports/shared/views/chat/MessageView.qml
Labels: tested

#9136 feat(@desktop/onboarding): weird menu order on app login
  src/app/global/app_translatable_constants.nim
  src/app/modules/startup/models/login_account_item.nim
  src/app/modules/startup/models/login_account_model.nim
  src/app/modules/startup/module.nim
  ui/app/AppLayouts/Onboarding/views/LoginView.qml
  ui/imports/utils/Constants.qml
Labels: tested

#8854 feat(chat): ignore not loaded messages
  src/app_service/service/message/message_cursor.nim
  src/app_service/service/message/service.nim
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
Labels: tested

#9175 fix(Chat): ensure message context menu operates on plaintext
  src/app/modules/main/activity_center/controller.nim
  src/app/modules/main/activity_center/module.nim
  src/app/modules/main/chat_section/chat_content/controller.nim
  src/app/modules/main/chat_section/chat_content/messages/controller.nim
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/main/chat_section/chat_content/module.nim
  src/app/modules/main/chat_section/view.nim
  src/app_service/common/message.nim
  src/app_service/service/message/service.nim
Labels: tested

#8837 fix(@desktop/chat): Do not change screen when showing profile window
  src/app/modules/main/module.nim
Labels: tested

#9229 test(suite_settings): Restore broken tests
  test/ui-test/testSuites/global_shared/steps/settingsSteps.py
  test/ui-test/testSuites/suite_wallet/shared/steps/walletInitSteps.py
Labels: bug, squish

#9224 chore(@desktop/onboarding): remove `Create a new profile with the same chatkey` screen from onboarding flow
  src/app/modules/startup/internal/profile_fetching_announcement_state.nim
Labels: tested

#9199 feat(Community Permissions): Hide `Who holds - Add` button when there are 5 items already added
  ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
Labels: ui, Communities, tested, feature, E:Communities

#9184 feat(Community Permissions): Update `Who holds` tokens dropdown design and flow according to the new design
  storybook/figma.json
  storybook/pages/HoldingsDropdownPage.qml
  ui/app/AppLayouts/Chat/controls/community/AssetsPanel.qml
  ui/app/AppLayouts/Chat/controls/community/CollectiblesPanel.qml
  ui/app/AppLayouts/Chat/controls/community/EnsPanel.qml
  ui/app/AppLayouts/Chat/controls/community/ExtendedDropdownContent.qml
  ui/app/AppLayouts/Chat/controls/community/HoldingTypes.qml
  ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml
  ui/app/AppLayouts/Chat/controls/community/HoldingsTabs.qml
  ui/app/AppLayouts/Chat/controls/community/ListDropdownContent.qml
  ui/app/AppLayouts/Chat/controls/community/ThumbnailsDropdownContent.qml
  ui/app/AppLayouts/Chat/controls/community/TokenItem.qml
  ui/app/AppLayouts/Chat/controls/community/TokenPanel.qml
  ui/app/AppLayouts/Chat/helpers/CommunityPermissionsHelpers.qml
  ui/app/AppLayouts/Chat/stores/CommunitiesStore.qml
  ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
  ui/app/AppLayouts/Chat/views/communities/CommunityPermissionsView.qml
Labels: ui, Communities, tested, feature, E:Communities

#9265 test: Skip broken/unstable tests
  test/ui-test/testSuites/suite_communities/tst_communityFlows/test.feature
  test/ui-test/testSuites/suite_onboarding/tst_signUpSeedPhraseNegativeCases/test.feature
  test/ui-test/testSuites/suite_onboarding/tst_statusLoginPassword/test.feature
  test/ui-test/testSuites/suite_onboarding/tst_statusSignUp/test.feature
  test/ui-test/testSuites/suite_settings/tst_contactsFlow/test.feature
  test/ui-test/testSuites/suite_settings/tst_mainSettingsSection/test.feature
  test/ui-test/testSuites/suite_wallet/tst_transaction/test.feature
Labels: ci, priority F2: important, squish

#9230 refactor(@desktop/channel): refactor members list to only have one list per community
  src/app/modules/main/chat_section/chat_content/module.nim
  src/app/modules/main/chat_section/chat_content/users/module.nim
  src/app/modules/main/chat_section/module.nim
Labels: tested, needs-status-go

#9330 fix: Fixed tokens initialization. Fixed SendModal for ENS.
  src/app/modules/shared_models/token_model.nim
  src/app_service/common/cache.nim
  src/app_service/service/token/service.nim
  ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml
  ui/imports/shared/popups/SendModal.qml
Labels: tested

#9338 feat(@desktop/keycard): `unlocking` screen for unlock flow
  src/app/modules/shared_modules/keycard_popup/internal/pin_set_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/repeat_pin_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/state.nim
  src/app/modules/shared_modules/keycard_popup/internal/state_factory.nim
  src/app/modules/shared_modules/keycard_popup/internal/state_factory_general_implementation.nim
  src/app/modules/shared_modules/keycard_popup/internal/unlock_keycard_failure_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/unlocking_keycard_state.nim
  src/app/modules/shared_modules/keycard_popup/internal/wrong_puk_state.nim
  ui/imports/shared/popups/keycard/KeycardPopupContent.qml
  ui/imports/shared/popups/keycard/KeycardPopupDetails.qml
  ui/imports/shared/popups/keycard/states/KeycardInit.qml
  ui/imports/utils/Constants.qml
Labels: tested

#9204 feat(@desktop/wallet): implement new collectibles view
  src/app/modules/main/wallet_section/collectibles/controller.nim
  src/app/modules/main/wallet_section/collectibles/models/collectibles_flat_proxy_model.nim
  src/app/modules/main/wallet_section/collectibles/models/collectibles_model.nim
  src/app/modules/main/wallet_section/collectibles/models/collectibles_utils.nim
  src/app/modules/main/wallet_section/collectibles/models/collections_item.nim
  src/app/modules/main/wallet_section/collectibles/models/collections_model.nim
  src/app/modules/main/wallet_section/collectibles/models/collections_utils.nim
  src/app/modules/main/wallet_section/collectibles/module.nim
  src/app/modules/main/wallet_section/collectibles/view.nim
  src/app_service/service/collectible/service.nim
  ui/app/AppLayouts/Wallet/stores/RootStore.qml
  ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
  ui/app/AppLayouts/Wallet/views/RightTabView.qml
  ui/app/AppLayouts/Wallet/views/collectibles/CollectibleCollectionView.qml
  ui/app/AppLayouts/Wallet/views/collectibles/CollectibleView.qml
Labels: tested

#9360 fix: "Cannot connect to store node" banner never disappears
  src/app/modules/main/controller.nim
Labels: tested

#9029 Feat/issue 7661
  src/app/modules/main/wallet_section/all_tokens/module.nim
  src/app/modules/main/wallet_section/all_tokens/view.nim
  src/app/modules/main/wallet_section/module.nim
  src/app/modules/main/wallet_section/view.nim
  ui/app/AppLayouts/Wallet/panels/WalletHeader.qml
  ui/app/AppLayouts/Wallet/stores/RootStore.qml
  ui/app/AppLayouts/Wallet/views/AssetsDetailView.qml
  ui/app/AppLayouts/Wallet/views/LeftTabView.qml
  ui/imports/assets/icons/mask/dummyLineGraph.svg
  ui/imports/shared/controls/LoadingTokenDelegate.qml
  ui/imports/shared/controls/StyledTextEditWithLoadingState.qml
  ui/imports/shared/controls/TokenDelegate.qml
  ui/imports/shared/controls/qmldir
  ui/imports/shared/stores/RootStore.qml
  ui/imports/shared/views/AssetsView.qml
  ui/imports/shared/views/LoadingGraphView.qml
  ui/imports/utils/Constants.qml
Labels: tested
