Repository status-im/status-desktop, pull requests merged in 2023-07, with the labels that each got.

#11390 ci: upgrade docker image to Ubuntu 20.04
  build-linux.sh
  ci/Dockerfile
  ci/Jenkinsfile.linux
  ci/README.md
Labels: ci, linux, dependencies

#11427 ci: fix read-only FS errors in AppImage
  Makefile
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.tests-e2e
Labels: bug, ci, linux

#11415 fix(@wallet): overview balance with symbol
  src/app/modules/main/wallet_section/activity/controller.nim
  src/app/modules/main/wallet_section/filter.nim
  src/app/modules/main/wallet_section/module.nim
  ui/app/AppLayouts/Wallet/panels/WalletHeader.qml
Labels: tested

#11425 fix(CommunitySettingsView): Add expected roles to assets/collectibles models
  ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
Labels: testing

#11430 feat: Implement Community Overview footer with mocked data
  storybook/PagesModel.qml
  storybook/figma.json
  storybook/pages/OverviewSettingsFooterPage.qml
  test/ui-test/src/screens/StatusCommunityScreen.py
  test/ui-test/testSuites/suite_communities/shared/scripts/community_names.py
  test/ui-test/testSuites/suite_communities/shared/steps/communitySteps.py
  test/ui-test/testSuites/suite_communities/tst_communityManageOverview/test.feature
  ui/StatusQ/src/assets.qrc
  ui/StatusQ/src/assets/img/icons/external-link.svg
  ui/app/AppLayouts/Communities/panels/JoinPermissionsOverlayPanel.qml
  ui/app/AppLayouts/Communities/panels/OverviewSettingsFooter.qml
  ui/app/AppLayouts/Communities/panels/OverviewSettingsPanel.qml
  ui/app/AppLayouts/Communities/panels/qmldir
  ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
  ui/imports/utils/Constants.qml
Labels: tested

#11470 feat(OwnerToken): Add Mint Owner token view
  storybook/PagesModel.qml
  storybook/figma.json
  storybook/pages/MintTokensSettingsPanelPage.qml
  storybook/pages/OwnerTokenWelcomeViewPage.qml
  ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
  ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
  ui/app/AppLayouts/Communities/views/OwnerTokenWelcomeView.qml
  ui/app/AppLayouts/Communities/views/qmldir
  ui/imports/shared/controls/DisabledTooltipButton.qml
Labels: Communities, feature, qml

#11436 feat(new-links-format): Adds new links to UI
  src/app/modules/main/communities/controller.nim
  src/app/modules/main/communities/io_interface.nim
  src/app/modules/main/communities/module.nim
  src/app/modules/main/communities/view.nim
  src/app/modules/main/profile_section/contacts/controller.nim
  src/app/modules/main/profile_section/contacts/io_interface.nim
  src/app/modules/main/profile_section/contacts/module.nim
  src/app/modules/main/profile_section/contacts/view.nim
  src/app_service/service/community/service.nim
  src/app_service/service/contacts/service.nim
  src/backend/communities.nim
  src/backend/contacts.nim
  ui/app/AppLayouts/Profile/stores/ContactsStore.qml
  ui/imports/shared/views/ProfileDialogView.qml
  ui/imports/utils/Utils.qml
Labels: tested

#11571 feat(OwnerToken): Create `EditTokenView.qml` for mint owner token flow
  storybook/PagesModel.qml
  storybook/figma.json
  storybook/pages/EditOwnerTokenViewPage.qml
  ui/app/AppLayouts/Communities/helpers/PermissionsHelpers.qml
  ui/app/AppLayouts/Communities/helpers/TokenObject.qml
  ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
  ui/app/AppLayouts/Communities/panels/PrivilegedTokenArtworkPanel.qml
  ui/app/AppLayouts/Communities/panels/TokenInfoPanel.qml
  ui/app/AppLayouts/Communities/panels/qmldir
  ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
  ui/app/AppLayouts/Communities/views/CommunityTokenView.qml
  ui/app/AppLayouts/Communities/views/EditOwnerTokenView.qml
  ui/app/AppLayouts/Communities/views/OwnerTokenWelcomeView.qml
  ui/app/AppLayouts/Communities/views/qmldir
  ui/imports/shared/stores/CommunityTokensStore.qml
Labels: feature, C2, E:DTokenMasterImplementation

#11511 feat(deeplinks): Open user profile or chat if user is contact
  src/app/modules/main/module.nim
Labels: tested

#11393 feat(@desktop/communities): Add burning state logic
  src/app/modules/main/communities/tokens/io_interface.nim
  src/app/modules/main/communities/tokens/models/token_item.nim
  src/app/modules/main/communities/tokens/models/token_model.nim
  src/app/modules/main/communities/tokens/module.nim
  src/app/modules/main/controller.nim
  src/app/modules/main/io_interface.nim
  src/app/modules/main/module.nim
  src/app/modules/shared_models/section_item.nim
  src/app_service/common/types.nim
  src/app_service/service/community_tokens/service.nim
  src/app_service/service/transaction/service.nim
  ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
Labels: tested, tested-issues, messenger-team

#11562 feat(@desktop/wallet): Account view - New Account view UI
  src/app/boot/app_controller.nim
  src/app/modules/main/profile_section/keycard/module.nim
  src/app/modules/main/profile_section/wallet/accounts/controller.nim
  src/app/modules/main/profile_section/wallet/accounts/module.nim
  src/app/modules/shared/keypairs.nim
  src/app/modules/shared_models/keypair_account_item.nim
  src/app/modules/shared_models/keypair_account_model.nim
  src/app/modules/shared_models/keypair_item.nim
  src/app/modules/shared_modules/keycard_popup/controller.nim
  src/app/modules/shared_modules/keycard_popup/module.nim
  src/app_service/service/wallet_account/service.nim
  storybook/PagesModel.qml
  storybook/pages/AccountViewPage.qml
  storybook/pages/ProfileAccountsPage.qml
  test/ui-test/src/screens/SettingsScreen.py
  test/ui-test/testSuites/global_shared/scripts/settings_names.py
  ui/app/AppLayouts/Profile/ProfileLayout.qml
  ui/app/AppLayouts/Profile/controls/WalletAccountDetailsKeypairItem.qml
  ui/app/AppLayouts/Profile/controls/WalletAccountDetailsListItem.qml
  ui/app/AppLayouts/Profile/controls/WalletKeyPairDelegate.qml
  ui/app/AppLayouts/Profile/stores/WalletStore.qml
  ui/app/AppLayouts/Profile/views/SettingsContentBase.qml
  ui/app/AppLayouts/Profile/views/WalletView.qml
  ui/app/AppLayouts/Profile/views/wallet/AccountView.qml
  ui/app/AppLayouts/Profile/views/wallet/MainView.qml
  ui/app/AppLayouts/Profile/views/wallet/qmldir
  ui/app/AppLayouts/Wallet/controls/AccountHeaderGradient.qml
  ui/imports/utils/Utils.qml
Labels: tested

#11614 feat(OwnerToken): Add all mint states views design details
  storybook/pages/AirdropsSettingsPanelPage.qml
  storybook/pages/MintTokensSettingsPanelPage.qml
  storybook/pages/MintedTokensViewPage.qml
  storybook/src/Models/MintedTokensModel.qml
  ui/app/AppLayouts/Communities/helpers/PermissionsHelpers.qml
  ui/app/AppLayouts/Communities/panels/AirdropsSettingsPanel.qml
  ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
  ui/app/AppLayouts/Communities/panels/PrivilegedTokenArtworkPanel.qml
  ui/app/AppLayouts/Communities/panels/TokenInfoPanel.qml
  ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
  ui/app/AppLayouts/Communities/views/EditOwnerTokenView.qml
  ui/app/AppLayouts/Communities/views/MintedTokensView.qml
  ui/app/AppLayouts/Communities/views/OwnerTokenWelcomeView.qml
  ui/app/AppLayouts/Wallet/views/collectibles/CollectibleView.qml
  ui/imports/shared/stores/CommunityTokensStore.qml
Labels: C2

#11579 chore(wallet) optimize fetching request by using metadata
  src/app/modules/main/wallet_section/activity/entry.nim
  src/backend/activity.nim
  ui/app/AppLayouts/Wallet/stores/RootStore.qml
Labels: tested

#11673 fix: Bind `linkPreviewModel` property
  ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
  ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: E:NewUnfurlingAPI

#11619 feat(new-links): Parse url data and display
  src/app/boot/app_controller.nim
  src/app/modules/main/module.nim
  src/app/modules/main/shared_urls/controller.nim
  src/app/modules/main/shared_urls/io_interface.nim
  src/app/modules/main/shared_urls/module.nim
  src/app/modules/main/shared_urls/view.nim
  src/app/modules/main/view.nim
  src/app_service/service/shared_urls/dto/url_data.nim
  src/app_service/service/shared_urls/service.nim
  src/backend/general.nim
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/MembersSelectorView.qml
  ui/app/mainui/Popups.qml
  ui/imports/shared/popups/SendContactRequestModal.qml
  ui/imports/shared/views/chat/InvitationBubbleView.qml
  ui/imports/shared/views/chat/LinksMessageView.qml
  ui/imports/utils/Global.qml
  ui/imports/utils/Utils.qml
Labels: tested

#11422 StatusScrollView usage docs
  storybook/pages/CommunityTokenViewPage.qml
  storybook/pages/IntroPanelPage.qml
  storybook/pages/StatusScrollViewPage.qml
  storybook/src/Models/ModelsData.qml
  ui/StatusQ/src/StatusQ/Core/StatusScrollView.qml
  ui/StatusQ/src/contributing.md
Labels: chore

#11620 feat(airdrop): make the airdrop member selector use the airdropAddress
  ui/app/AppLayouts/Communities/panels/AirdropsSettingsPanel.qml
  ui/app/AppLayouts/Communities/popups/MembersDropdown.qml
  ui/app/AppLayouts/Communities/views/EditAirdropView.qml
Labels: testing
