Repository status-im/status-desktop, pull requests merged in 2023-08, with the labels that each got.

#11720 fix(Minting): After minting completed 1 airdrop button is enabled and the other disabled
  storybook/pages/SortableTokenHoldersPanelPage.qml
  storybook/pages/StatusInfoBoxPanelPage.qml
  ui/StatusQ/src/StatusQ/Components/StatusInfoBoxPanel.qml
  ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
  ui/app/AppLayouts/Communities/panels/SortableTokenHoldersPanel.qml
  ui/app/AppLayouts/Communities/views/CommunityTokenView.qml
Labels: bug, C3

#11728 fix(wallet): fix activity time filter
  src/app/modules/main/wallet_section/activity/controller.nim
  src/backend/activity.nim
  ui/app/AppLayouts/Wallet/panels/ActivityFilterPanel.qml
  ui/app/AppLayouts/Wallet/stores/ActivityFiltersStore.qml
Labels: tested

#11732 ci: fix use of release Infura key for E2E runs
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.tests-e2e
  ci/Jenkinsfile.tests-imports
  ci/Jenkinsfile.tests-nim
  ci/Jenkinsfile.windows
  ci/cpp/Jenkinsfile.linux
  ci/cpp/Jenkinsfile.macos
  ci/cpp/Jenkinsfile.windows
Labels: ci

#11733 feat(OwnerToken): Add `Retry` button
  storybook/pages/MintTokensSettingsPanelPage.qml
  ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
  ui/app/AppLayouts/Communities/panels/PrivilegedTokenArtworkPanel.qml
  ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
  ui/app/AppLayouts/Communities/views/MintedTokensView.qml
Labels: feature, C3

#11756 chore(makefile): improve dotherside build
  Makefile
Labels: chore

#11760 fix(Mint): No redirect to Tokens screen when minting a token
  ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
Labels: bug

#11766 ci: pass RELEASE parameter to child jobs from parent
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.tests-e2e
  ci/Jenkinsfile.tests-imports
  ci/Jenkinsfile.tests-nim
  ci/Jenkinsfile.windows
  ci/cpp/Jenkinsfile.linux
  ci/cpp/Jenkinsfile.macos
  ci/cpp/Jenkinsfile.windows
Labels: ci

#11709 Feat/channels member list
  src/app/modules/main/chat_section/chat_content/module.nim
  src/app/modules/main/chat_section/chat_content/users/controller.nim
  src/app/modules/main/chat_section/chat_content/users/module.nim
  src/app/modules/main/chat_section/io_interface.nim
  src/app/modules/main/chat_section/module.nim
  src/app_service/service/chat/service.nim
  src/app_service/service/community/service.nim
  ui/app/AppLayouts/Chat/views/ChatView.qml
Labels: tested

#11608 11182 remote destruct state
  src/app/modules/main/communities/tokens/models/token_item.nim
  src/app/modules/main/communities/tokens/models/token_model.nim
  src/app/modules/main/communities/tokens/models/token_owners_item.nim
  src/app/modules/main/communities/tokens/models/token_owners_model.nim
  src/app/modules/main/controller.nim
  src/app/modules/main/io_interface.nim
  src/app/modules/main/module.nim
  src/app/modules/shared_models/section_item.nim
  src/app_service/service/community_tokens/service.nim
  src/backend/community_tokens.nim
  ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
Labels: tested

#11786 fix(@desktop/wallet): fix wrong model update when items are fetched
  src/app/modules/main/wallet_section/collectibles/controller.nim
  src/app/modules/main/wallet_section/collectibles/events_handler.nim
  src/app/modules/shared_models/collectibles_model.nim
  ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
Labels: tested

#11816 feat(BurnToken): Add fee box with network selector to Burn popup
  storybook/pages/BurnTokensPopupPage.qml
  ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
  ui/app/AppLayouts/Communities/popups/BurnTokensPopup.qml
  ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
  ui/imports/shared/stores/CommunityTokensStore.qml
Labels: feature

#11840 feat(Permissions): Adding, duplicating, editing and deleting permissions when control node is offline
  storybook/pages/CommunityPermissionsSettingsPanelEditor.qml
  storybook/pages/PermissionsSettingsPanelPage.qml
  storybook/src/Models/PermissionsModel.qml
  ui/app/AppLayouts/Communities/controls/PermissionItem.qml
  ui/app/AppLayouts/Communities/controls/PermissionTypes.qml
  ui/app/AppLayouts/Communities/views/EditPermissionView.qml
  ui/app/AppLayouts/Communities/views/PermissionsView.qml
Labels: feature, E:Desktop Comm Perms and Minting MVP

#11838 feat(@desktop/wallet): Update remove keypair popup to match the Figma
  src/app/modules/main/module.nim
  src/app/modules/main/profile_section/wallet/accounts/controller.nim
  src/app/modules/main/profile_section/wallet/accounts/module.nim
  src/app/modules/main/profile_section/wallet/accounts/view.nim
  src/app/modules/main/view.nim
  src/app/modules/shared_models/keypair_model.nim
  src/app_service/service/wallet_account/service_account.nim
  src/app_service/service/wallet_account/signals_and_payloads.nim
  storybook/pages/ProfileAccountsPage.qml
  ui/app/AppLayouts/Profile/controls/WalletAccountDelegate.qml
  ui/app/AppLayouts/Profile/popups/RemoveKeypairPopup.qml
  ui/app/AppLayouts/Profile/popups/qmldir
  ui/app/AppLayouts/Profile/views/WalletView.qml
  ui/app/mainui/AppMain.qml
  ui/imports/shared/controls/qmldir
Labels: tested

#11844 refactor(CommunitySettings): Add SFPM for wallet accounts model in a single place
  storybook/src/Models/WalletAccountsModel.qml
  ui/app/AppLayouts/Chat/ChatLayout.qml
  ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
  ui/app/AppLayouts/Communities/panels/SharedAddressesAccountSelector.qml
  ui/app/AppLayouts/Communities/panels/SharedAddressesPanel.qml
  ui/app/AppLayouts/Communities/popups/BurnTokensPopup.qml
  ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
  ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
  ui/app/AppLayouts/Communities/views/CommunityTokenView.qml
  ui/app/AppLayouts/Communities/views/EditCommunityTokenView.qml
  ui/app/AppLayouts/Communities/views/EditOwnerTokenView.qml
  ui/app/AppLayouts/Profile/views/CommunitiesView.qml
  ui/app/AppLayouts/Wallet/stores/RootStore.qml
  ui/app/AppLayouts/stores/RootStore.qml
  ui/imports/shared/popups/CommunityIntroDialog.qml
Labels: refactor

#11867 sign-macos-pkg.sh: move gatekeeper verification
  scripts/notarize-macos-pkg.sh
  scripts/sign-macos-pkg.sh
Labels: macos, ci

#11862 chore(Communities): Refactor amounts handling for displaying, minting, airdropping and burning
  src/app/modules/main/communities/tokens/io_interface.nim
  src/app/modules/main/communities/tokens/models/token_model.nim
  src/app/modules/main/communities/tokens/module.nim
  src/app/modules/main/communities/tokens/view.nim
  src/app_service/common/conversion.nim
  src/app_service/service/community_tokens/dto/community_token.nim
  storybook/pages/AirdropsSettingsPanelPage.qml
  storybook/pages/HoldingsDropdownPage.qml
  storybook/pages/InlineNetworksComboBoxPage.qml
  storybook/pages/TokenPanelPage.qml
  ui/StatusQ/src/StatusQ/Core/Utils/AmountsArithmetic.qml
  ui/app/AppLayouts/Communities/controls/InlineNetworksComboBox.qml
  ui/app/AppLayouts/Communities/controls/ListDropdownContent.qml
  ui/app/AppLayouts/Communities/controls/TokenPanel.qml
  ui/app/AppLayouts/Communities/helpers/PermissionsHelpers.qml
  ui/app/AppLayouts/Communities/helpers/TokenObject.qml
  ui/app/AppLayouts/Communities/panels/AirdropsSettingsPanel.qml
  ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
  ui/app/AppLayouts/Communities/panels/TokenInfoPanel.qml
  ui/app/AppLayouts/Communities/popups/BurnTokensPopup.qml
  ui/app/AppLayouts/Communities/popups/HoldingsDropdown.qml
  ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
  ui/app/AppLayouts/Communities/views/EditAirdropView.qml
  ui/app/AppLayouts/Communities/views/EditCommunityTokenView.qml
  ui/app/AppLayouts/Communities/views/EditOwnerTokenView.qml
  ui/app/AppLayouts/Communities/views/EditPermissionView.qml
  ui/app/AppLayouts/Communities/views/MintedTokensView.qml
  ui/imports/shared/controls/AmountInput.qml
  ui/imports/shared/stores/CommunityTokensStore.qml
Labels: tested-issues

#11937 fix(Airdrop): Use remaining supply to display and validate amounts
  ui/app/AppLayouts/Communities/controls/ListDropdownContent.qml
  ui/app/AppLayouts/Communities/helpers/PermissionsHelpers.qml
  ui/app/AppLayouts/Communities/popups/HoldingsDropdown.qml
  ui/app/AppLayouts/Communities/views/EditAirdropView.qml
Labels: tested

#12025 Add missing object id for QML object
  ui/imports/shared/views/chat/ChatContextMenuView.qml
Labels: chore
