Repository status-im/status-desktop, pull requests merged in 2023-11, with the labels that each got.

#12596 feature(ci): set build description even if it fails
  ci/Jenkinsfile.combined
Labels: ci

#12613 feature: live status link previews
  src/app/modules/main/chat_section/chat_content/messages/controller.nim
  src/app/modules/main/chat_section/chat_content/messages/io_interface.nim
  src/app/modules/main/chat_section/chat_content/messages/module.nim
  src/app/modules/main/chat_section/chat_content/messages/view.nim
  src/app/modules/shared_models/link_preview_item.nim
  src/app/modules/shared_models/link_preview_model.nim
  src/app/modules/shared_models/message_model.nim
  src/app_service/service/chat/dto/chat.nim
  src/app_service/service/community/async_tasks.nim
  src/app_service/service/community/service.nim
  src/app_service/service/message/dto/link_preview.nim
  src/app_service/service/message/dto/link_preview_thumbnail.nim
  src/app_service/service/message/dto/status_community_channel_link_preview.nim
  src/app_service/service/message/dto/status_community_link_preview.nim
  src/app_service/service/message/dto/status_contact_link_preview.nim
  src/backend/communities.nim
  ui/StatusQ/src/assets.qrc
  ui/app/mainui/AppMain.qml
  ui/imports/shared/controls/chat/LinkPreviewCard.qml
  ui/imports/shared/controls/chat/private/CommunityData.qml
  ui/imports/shared/controls/delegates/LinkPreviewCardDelegate.qml
  ui/imports/shared/views/chat/MessageView.qml
Labels: waiting-for-status-go-merge

#12645 feat(CommunityOwnership): UI toasts part
  src/app/modules/main/ephemeral_notification_item.nim
  src/app/modules/main/ephemeral_notification_model.nim
  src/app/modules/main/io_interface.nim
  src/app/modules/main/module.nim
  src/app/modules/main/view.nim
  ui/StatusQ/src/StatusQ/Components/StatusToastMessage.qml
  ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
  ui/app/mainui/AppMain.qml
  ui/app/mainui/Popups.qml
  ui/app/mainui/ToastsManager.qml
  ui/imports/shared/stores/CommunityTokensStore.qml
  ui/imports/utils/Global.qml
Labels: feature

#12721 fix: workaround to crash on startup with Qt 5.15.11
  ui/StatusQ/src/StatusQ/Components/StatusCard.qml
  ui/imports/shared/popups/send/views/NetworkSelector.qml
Labels: linux, crash

#12687 fix: avoid duplicating UnfurlURLs requests
  src/app/modules/main/chat_section/chat_content/input_area/controller.nim
  src/app/modules/main/chat_section/chat_content/input_area/link_preview_cache.nim
Labels: E:Desktop New Unfurling API
