Repository status-im/status-desktop, pull requests merged in 2023-04, with the labels that each got.

#10023 fix(Albums): Fix extra count of messages for image albums
  src/app/modules/shared_models/message_model.nim
Labels: do not merge, tested, needs-status-go

#10178 fix(@desktop/onboarding): if you fail your login once, it doesn't work after ever
  src/app/modules/startup/controller.nim
Labels: tested

#10193 fix(@desktop/channels): chat/channel messages loading state is not disappearing
  src/app_service/service/message/service.nim
Labels: cherry_picked

#10210 ci: allow running MacOS builds on M1 Macs
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.windows
  ci/cpp/Jenkinsfile.linux
  ci/cpp/Jenkinsfile.macos
  ci/cpp/Jenkinsfile.windows
Labels: macos, ci

#10225 fix(@desktop/activityCenter): jump to message by clicking on notification
  src/app/modules/main/activity_center/module.nim
Labels: cherry_picked

#10005 feat(@desktop/wallet): add support for more NFTs media types
  src/app/modules/main/wallet_section/collectibles/current_collectible/view.nim
  src/app/modules/main/wallet_section/collectibles/models/collectibles_item.nim
  src/app/modules/main/wallet_section/collectibles/models/collectibles_model.nim
  src/app/modules/main/wallet_section/collectibles/models/collectibles_utils.nim
  src/app_service/service/collectible/dto.nim
  ui/StatusQ/doc/src/statusqcomponents.qdoc
  ui/StatusQ/src/StatusQ/Components/StatusAnimatedImage.qml
  ui/StatusQ/src/StatusQ/Components/StatusImage.qml
  ui/StatusQ/src/StatusQ/Components/StatusRoundedComponent.qml
  ui/StatusQ/src/StatusQ/Components/StatusRoundedImage.qml
  ui/StatusQ/src/StatusQ/Components/StatusRoundedMedia.qml
  ui/StatusQ/src/StatusQ/Components/StatusVideo.qml
  ui/StatusQ/src/StatusQ/Components/qmldir
  ui/StatusQ/src/statusq.qrc
  ui/app/AppLayouts/Chat/views/communities/CommunityMintedTokensView.qml
  ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
  ui/app/AppLayouts/Wallet/views/collectibles/CollectibleDetailView.qml
  ui/app/AppLayouts/Wallet/views/collectibles/CollectibleView.qml
Labels: tested

#7151 chore: script for creating local test fleet
  scripts/localfleet/README.md
  scripts/localfleet/docker-compose-host.yml
  scripts/localfleet/fleet.go.template
  scripts/localfleet/fleets.json.template
  scripts/localfleet/gen-config.sh
  scripts/localfleet/main.go
Labels: 0.8.0, || stagnant ||

#10269 ci: fix handling of stdout in MacOS notarization
  scripts/notarize-macos-pkg.sh
Labels: macos, security

#10304 ci: add suite and tags parameters to e2e CI job
  ci/Jenkinsfile.tests-e2e
Labels: ci

#10300 fix(Mint/Airdrop tokens): Darkmode images
  ui/app/AppLayouts/Chat/views/communities/CommunityWelcomeSettingsView.qml
  ui/imports/assets/png/community/airdrops8_1.png
  ui/imports/assets/png/community/mint2_1.png
Labels: ui-team, Communities, qml, needs-design

#8337 fix(@desktop/cpp): Implement StatusGoQt::sendMessage() function
  libs/ChatSection/include/Status/ChatSection/ChatSectionController.h
  libs/ChatSection/qml/Status/ChatSection/ContentView.qml
  libs/ChatSection/qml/Status/ChatSection/MainView.qml
  libs/ChatSection/src/ChatSectionController.cpp
  libs/StatusGoQt/CMakeLists.txt
  libs/StatusGoQt/src/StatusGo/Messages/InputMessage.cpp
  libs/StatusGoQt/src/StatusGo/Messages/InputMessage.h
  libs/StatusGoQt/src/StatusGo/Messages/MessageDto.h
  libs/StatusGoQt/src/StatusGo/Messages/MessagesApi.cpp
  libs/StatusGoQt/src/StatusGo/Messages/MessagesApi.h
  test/libs/StatusGoQt/test_messaging.cpp
Labels: || stagnant ||

#10337 fix(StatusQ): Remove debug postfix
  ui/StatusQ/CMakeLists.txt
Labels: tested

#10223 feat(@desktop/wallet) reduce number of digits shown for large currenc…
  storybook/PagesModel.qml
  storybook/pages/AmountToSendViewPage.qml
  ui/StatusQ/src/StatusQ/Controls/StatusAccountSelector.qml
  ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml
  ui/imports/shared/views/AmountToSend.qml
  ui/imports/shared/views/qmldir
Labels: tested

#10351 fix(Makefile): Move StatusQ to order-only-dependencies of the app
  Makefile
Labels: tested

#10334 feat(Mint/Airdrop Collectible): Implement `Airdrop` footer option
  ui/app/AppLayouts/Chat/panels/communities/CommunityAirdropsSettingsPanel.qml
  ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml
  ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
  ui/app/AppLayouts/Chat/views/communities/CommunityNewAirdropView.qml
Labels: Communities, feature, qml

#10385 ci: add Alchemy credentials, update Infura
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  ci/Jenkinsfile.tests-e2e
  ci/Jenkinsfile.tests-imports
  ci/Jenkinsfile.tests-nim
  ci/Jenkinsfile.windows
Labels: ci, security

#10458 macos: bump notarization retry limit from 20 to 40
  Makefile
  ci/Jenkinsfile.macos
  scripts/notarize-macos-pkg.sh
Labels: macos, ci
