Repository status-im/status-desktop, pull requests merged in 2023-05, with the labels that each got.

#10416 feat(@desktop/wallet): New floating header as a drop down list
  src/app/modules/main/wallet_section/overview/item.nim
  src/app/modules/main/wallet_section/overview/module.nim
  src/app/modules/main/wallet_section/overview/view.nim
  ui/StatusQ/sandbox/controls/Popups.qml
  ui/StatusQ/src/StatusQ/Controls/StatusColorRadioButton.qml
  ui/StatusQ/src/StatusQ/Controls/StatusFloatingButtonsSelector.qml
  ui/StatusQ/src/StatusQ/Controls/qmldir
  ui/StatusQ/src/StatusQ/Core/Theme/StatusColors.qml
  ui/StatusQ/src/StatusQ/Core/Theme/ThemePalette.qml
  ui/StatusQ/src/statusq.qrc
  ui/app/AppLayouts/Wallet/panels/WalletFooter.qml
  ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml
  ui/app/AppLayouts/Wallet/stores/RootStore.qml
  ui/imports/shared/controls/SavedAddressListItem.qml
  ui/imports/shared/controls/TokenBalancePerChainDelegate.qml
  ui/imports/shared/controls/WalletAccountListItem.qml
  ui/imports/shared/panels/StatusAssetSelector.qml
  ui/imports/shared/popups/AccountsModalHeader.qml
  ui/imports/shared/popups/SendModal.qml
  ui/imports/shared/stores/TransactionStore.qml
  ui/imports/shared/views/NetworksSimpleRoutingView.qml
  ui/imports/shared/views/TabAddressSelectorView.qml
  ui/imports/utils/Constants.qml
Labels: tested

#10532 fix: ensure notification settings are cached from RPC
  src/app_service/service/settings/dto/settings.nim
  src/app_service/service/settings/service.nim
Labels: tested

#10551 ci: upgrade from Go 1.19.5 to 1.20.4
  ci/Dockerfile
  ci/Jenkinsfile.linux
  ci/Jenkinsfile.macos
  scripts/macos_build_setup.sh
  scripts/ubuntu_build_setup.sh
  scripts/windows_build_setup.ps1
Labels: macos, ci, linux, dependencies

#10260 test(suite_onboarding): mayfail tag removed for pass tests
  test/ui-test/src/drivers/elements/base_element.py
  test/ui-test/src/screens/StatusLoginScreen.py
  test/ui-test/src/screens/StatusWelcomeScreen.py
  test/ui-test/testSuites/global_shared/scripts/onboarding_names.py
  test/ui-test/testSuites/global_shared/scripts/settings_names.py
  test/ui-test/testSuites/suite_onboarding/shared/steps/loginSteps.py
  test/ui-test/testSuites/suite_onboarding/shared/steps/steps.py
  test/ui-test/testSuites/suite_onboarding/tst_signUpNegativeCases/test.feature
  test/ui-test/testSuites/suite_onboarding/tst_signUpSeedPhraseNegativeCases/test.feature
  test/ui-test/testSuites/suite_onboarding/tst_statusLoginPassword/test.feature
  test/ui-test/testSuites/suite_onboarding/tst_statusSignUp/test.feature
  ui/main.qml
Labels: don't merge yet

#10576 fix(@desktop/activity): Fixed section glitch
  ui/imports/shared/views/HistoryView.qml
Labels: bug

#10589 feat(MintToken): Remote self-destruct footer option hidden if the minted collectible doesn't have self-destruct property set
  ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml
  ui/app/AppLayouts/Chat/panels/communities/MintTokensFooterPanel.qml
Labels: ui-team, Communities, feature, qml

#10653 fix(MintTokens): Update welcome page strings
  ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml
Labels: Communities, qml

#10654 fix(MintTokens): Update Create new collectible page according to new design
  ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml
  ui/app/AppLayouts/Chat/views/communities/CommunityNewCollectibleView.qml
Labels: Communities, qml, ui-improvements

#10725 feat(MintTokens): Add mint failure flow
  storybook/pages/CommunityCollectibleViewPage.qml
  storybook/src/Models/MintedCollectiblesModel.qml
  ui/app/AppLayouts/Chat/views/communities/CommunityCollectibleView.qml
  ui/app/AppLayouts/Chat/views/communities/CommunityMintedTokensView.qml
  ui/app/AppLayouts/Wallet/views/collectibles/CollectibleView.qml
Labels: Communities, feature, qml

#10729 fix(MessageContextMenu): Cleanup. Separate menu for profile.
  storybook/CMakeLists.txt
  storybook/PagesModel.qml
  storybook/pages/MessageContextMenuPage.qml
  storybook/pages/UserListPanelPage.qml
  ui/StatusQ/src/StatusQ/Popups/StatusMenu.qml
  ui/app/AppLayouts/Chat/panels/UserListPanel.qml
  ui/app/AppLayouts/Chat/panels/communities/CommunityMembersSettingsPanel.qml
  ui/app/AppLayouts/Chat/panels/communities/CommunityMembersTabPanel.qml
  ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml
  ui/app/AppLayouts/Chat/stores/MessageStore.qml
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/ChatContentView.qml
  ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
  ui/app/AppLayouts/Chat/views/ChatView.qml
  ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
  ui/app/AppLayouts/Profile/views/ContactsView.qml
  ui/app/mainui/Popups.qml
  ui/imports/shared/controls/chat/MessageReactionsRow.qml
  ui/imports/shared/controls/chat/ProfileHeader.qml
  ui/imports/shared/controls/chat/qmldir
  ui/imports/shared/popups/DeleteMessageConfirmationPopup.qml
  ui/imports/shared/popups/qmldir
  ui/imports/shared/status/StatusChatInput.qml
  ui/imports/shared/status/StatusImageModal.qml
  ui/imports/shared/views/chat/ImageContextMenu.qml
  ui/imports/shared/views/chat/LinksMessageView.qml
  ui/imports/shared/views/chat/MessageAddReactionContextMenu.qml
  ui/imports/shared/views/chat/MessageContextMenuView.qml
  ui/imports/shared/views/chat/MessageView.qml
  ui/imports/shared/views/chat/ProfileContextMenu.qml
  ui/imports/shared/views/chat/qmldir
  ui/imports/utils/Global.qml
  ui/imports/utils/Utils.qml
Labels: tested

#10604 [onboarding]: fixed overall positioning
  ui/app/AppLayouts/Onboarding/views/KeycardInitView.qml
  ui/app/AppLayouts/Onboarding/views/KeycardPinView.qml
  ui/app/AppLayouts/Onboarding/views/KeycardPukView.qml
  ui/app/AppLayouts/Onboarding/views/KeycardStateView.qml
  ui/app/AppLayouts/Onboarding/views/KeysMainView.qml
  ui/app/AppLayouts/Onboarding/views/LoginView.qml
  ui/app/AppLayouts/Onboarding/views/ProfileFetchingView.qml
  ui/app/AppLayouts/Onboarding/views/SeedPhraseView.qml
  ui/app/AppLayouts/Onboarding/views/SeedPhraseWordsInputView.qml
  ui/imports/utils/Constants.qml
Labels: tested

#10794 fix(invitation-bubble): Adds loading state for unfurling links
  src/app/modules/main/communities/controller.nim
  src/app/modules/main/communities/io_interface.nim
  src/app/modules/main/communities/module.nim
  src/app/modules/main/communities/view.nim
  src/app_service/service/community/service.nim
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
  ui/imports/shared/views/chat/InvitationBubbleView.qml
  ui/imports/shared/views/chat/LinksMessageView.qml
Labels: testing

#10773 fix(@desktop/wallet): properly handle collectibles api call errors
  src/app_service/service/collectible/async_tasks.nim
  src/app_service/service/community_tokens/async_tasks.nim
  src/app_service/service/transaction/async_tasks.nim
Labels: tested

#10813 fix(@desktop/keycard): updated information for listed keypairs for migration to a keycard
  ui/StatusQ/src/StatusQ/Components/StatusListItem.qml
  ui/imports/shared/popups/keycard/helpers/KeyPairItem.qml
Labels: tested

#10828 test(tst_userIdentity): Skipped scenario `The user can change own display name in profile popup`
  test/ui-test/testSuites/suite_settings/tst_userIdentity/test.feature
Labels: bug, squish

#10779 test/start multiple app instances added
  test/ui-test/src/common/Common.py
  test/ui-test/src/configs/path.py
  test/ui-test/src/configs/squish.py
  test/ui-test/src/drivers/SquishDriver.py
  test/ui-test/src/drivers/aut.py
  test/ui-test/src/drivers/context.py
  test/ui-test/src/drivers/elements/__init__.py
  test/ui-test/src/drivers/elements/base_window.py
  test/ui-test/src/screens/StatusChatScreen.py
  test/ui-test/src/screens/StatusMainScreen.py
  test/ui-test/src/screens/main_window.py
  test/ui-test/src/utils/local_system.py
  test/ui-test/src/utils/system_path.py
  test/ui-test/testSuites/global_shared/scripts/bdd_hooks.py
  test/ui-test/testSuites/global_shared/steps/commonInitSteps.py
  test/ui-test/testSuites/global_shared/steps/steps.py
  test/ui-test/testSuites/suite_communities/tst_communityAdminFlows/test.py
  test/ui-test/testSuites/suite_communities/tst_communityFlows/test.py
  test/ui-test/testSuites/suite_communities/tst_communityManageAirdrops/test.py
  test/ui-test/testSuites/suite_communities/tst_communityManageCommunity/test.py
  test/ui-test/testSuites/suite_communities/tst_communityManageMintTokens/test.py
  test/ui-test/testSuites/suite_communities/tst_communityManagePermissions/test.py
  test/ui-test/testSuites/suite_communities/tst_communityMemberFlows/test.py
  test/ui-test/testSuites/suite_communities/tst_communityMessageFlows/test.py
  test/ui-test/testSuites/suite_communities/tst_communityNavigation/test.py
  test/ui-test/testSuites/suite_communities/tst_searchFlows/test.py
  test/ui-test/testSuites/suite_messaging/shared/steps/chatSteps.py
  test/ui-test/testSuites/suite_messaging/tst_OneToOneChatFlow/bdd_hooks.py
  test/ui-test/testSuites/suite_messaging/tst_OneToOneChatFlow/test.feature
  test/ui-test/testSuites/suite_messaging/tst_OneToOneChatFlow/test.py
  test/ui-test/testSuites/suite_messaging/tst_adminGroupChat/test.py
  test/ui-test/testSuites/suite_messaging/tst_groupChat/test.py
  test/ui-test/testSuites/suite_onboarding/shared/steps/signUpSteps.py
  test/ui-test/testSuites/suite_onboarding/tst_passwordStrength/test.py
  test/ui-test/testSuites/suite_onboarding/tst_signUpNegativeCases/test.py
  test/ui-test/testSuites/suite_onboarding/tst_signUpSeedPhraseNegativeCases/test.py
  test/ui-test/testSuites/suite_onboarding/tst_statusLoginPassword/test.py
  test/ui-test/testSuites/suite_onboarding/tst_statusSignUp/test.py
  test/ui-test/testSuites/suite_settings/tst_contactsFlow/test.py
  test/ui-test/testSuites/suite_settings/tst_languageSettings/test.py
  test/ui-test/testSuites/suite_settings/tst_mainSettingsSection/bdd_hooks.py
  test/ui-test/testSuites/suite_settings/tst_mainSettingsSection/test.feature
  test/ui-test/testSuites/suite_settings/tst_mainSettingsSection/test.py
  test/ui-test/testSuites/suite_settings/tst_signUpAndQuit/test.py
  test/ui-test/testSuites/suite_settings/tst_userIdentity/test.py
  test/ui-test/testSuites/suite_wallet/tst_transaction/test.py
  test/ui-test/testSuites/suite_wallet/tst_wallet/test.py
  test/ui-test/testSuites/suite_wallet/tst_wallet_section_accounts_management/bdd_hooks.py
  test/ui-test/testSuites/suite_wallet/tst_wallet_section_accounts_management/test.py
Labels: do not merge
