Repository status-im/status-desktop, pull requests merged in 2023-02, with the labels that each got.

#9036 ENS usernames depend on the network
  src/app/boot/app_controller.nim
  src/app/modules/main/profile_section/ens_usernames/controller.nim
  src/app/modules/main/profile_section/ens_usernames/io_interface.nim
  src/app/modules/main/profile_section/ens_usernames/model.nim
  src/app/modules/main/profile_section/ens_usernames/module.nim
  src/app/modules/main/profile_section/ens_usernames/view.nim
  src/app_service/service/ens/async_tasks.nim
  src/app_service/service/ens/dto/ens_username_dto.nim
  src/app_service/service/ens/service.nim
  src/app_service/service/network/service.nim
  src/app_service/service/settings/service.nim
  src/backend/ens.nim
  ui/app/AppLayouts/Profile/popups/ENSPopup.qml
  ui/app/AppLayouts/Profile/stores/EnsUsernamesStore.qml
  ui/app/AppLayouts/Profile/views/EnsDetailsView.qml
  ui/app/AppLayouts/Profile/views/EnsListView.qml
  ui/app/AppLayouts/Profile/views/EnsSearchView.qml
  ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml
  ui/app/AppLayouts/Profile/views/EnsView.qml
Labels: testing

#9386 ci: add missing qt labels for build hosts
  ci/Jenkinsfile.e2e
  ci/Jenkinsfile.macos
Labels: macos, ci, linux

#6780 feat: waku2 store
  src/app/core/fleets/fleet_configuration.nim
  src/app/modules/main/profile_section/advanced/controller.nim
  src/app/modules/main/profile_section/advanced/io_interface.nim
  src/app/modules/main/profile_section/advanced/module.nim
  src/app/modules/main/profile_section/advanced/view.nim
  src/app/modules/main/profile_section/io_interface.nim
  src/app/modules/main/profile_section/module.nim
  src/app/modules/main/profile_section/view.nim
  src/app/modules/main/profile_section/waku/controller.nim
  src/app/modules/main/profile_section/waku/io_interface.nim
  src/app/modules/main/profile_section/waku/item.nim
  src/app/modules/main/profile_section/waku/model.nim
  src/app/modules/main/profile_section/waku/module.nim
  src/app/modules/main/profile_section/waku/view.nim
  src/app_service/service/node_configuration/dto/node_config.nim
  src/app_service/service/node_configuration/service.nim
  ui/app/AppLayouts/Chat/stores/RootStore.qml
  ui/app/AppLayouts/Profile/popups/AddWakuNodeModal.qml
  ui/app/AppLayouts/Profile/popups/AddWakuStoreModal.qml
  ui/app/AppLayouts/Profile/popups/WakuNodesModal.qml
  ui/app/AppLayouts/Profile/popups/WakuStoreModal.qml
  ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
  ui/app/AppLayouts/Profile/stores/MessagingStore.qml
  ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml
  ui/app/AppLayouts/Profile/views/AdvancedView.qml
  ui/app/AppLayouts/Profile/views/MessagingView.qml
Labels: tested

#9387 ci: update build setup scripts to Qt 5.15.2
  ci/Jenkinsfile.e2e
  ci/Jenkinsfile.macos
  scripts/macos_build_setup.sh
  scripts/ubuntu_build_setup.sh
Labels: macos, ci, linux, dependencies, squish

#9321 feat(Community Permissions): Integrate In section with permission creation/editing
  storybook/pages/CommunityPermissionsSettingItemEditor.qml
  storybook/pages/CommunityPermissionsSettingsPanelEditor.qml
  storybook/pages/CommunityPermissionsSettingsPanelPage.qml
  storybook/pages/CommunityPermissionsViewPage.qml
  storybook/src/Models/ChannelsModel.qml
  storybook/src/Models/PermissionsModel.qml
  ui/app/AppLayouts/Chat/controls/community/PermissionItem.qml
  ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
  ui/app/AppLayouts/Chat/stores/CommunitiesStore.qml
  ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
  ui/app/AppLayouts/Chat/views/communities/CommunityPermissionsView.qml
Labels: tested

#9371 feat(@desktop/wallet): Implement loading state for collectibles
  ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
  ui/app/AppLayouts/Wallet/views/collectibles/CollectibleView.qml
  ui/imports/utils/Constants.qml
Labels: tested

#9333 feat(@desktop/wallet): Implement loading state for Send/Bridge Modal
  ui/StatusQ/sandbox/pages/StatusCardPage.qml
  ui/StatusQ/src/StatusQ/Components/StatusCard.qml
  ui/imports/shared/controls/BalanceExceeded.qml
  ui/imports/shared/controls/GasValidator.qml
  ui/imports/shared/popups/SendModal.qml
  ui/imports/shared/stores/TransactionStore.qml
  ui/imports/shared/views/FeesView.qml
  ui/imports/shared/views/NetworkCardsComponent.qml
  ui/imports/shared/views/NetworksSimpleRoutingView.qml
Labels: tested

#9363 refactor(chat): make getChats async to speed up start time
  src/app/boot/app_controller.nim
  src/app/modules/main/controller.nim
  src/app/modules/main/io_interface.nim
  src/app/modules/main/module.nim
  src/app/modules/main/view.nim
  src/app_service/service/chat/async_tasks.nim
  src/app_service/service/chat/service.nim
  ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
  ui/app/mainui/AppMain.qml
  ui/imports/utils/Constants.qml
Labels: tested

#9368 fix(community): ensure chats are reordered when cateories have changed
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/io_interface.nim
  src/app/modules/main/chat_section/model.nim
  src/app/modules/main/chat_section/module.nim
  src/app_service/service/community/service.nim
Labels: tested-issues

#9522 ci(e2e): Changed UNSTABLE state to be considered as a failure
  ci/Jenkinsfile.e2e
Labels: ci, squish

#9372 feat(@desktop/wallet): adding wallet derivation path updates
  src/app/modules/main/wallet_section/accounts/controller.nim
  src/app/modules/main/wallet_section/accounts/io_interface.nim
  src/app/modules/main/wallet_section/accounts/module.nim
  src/app/modules/main/wallet_section/accounts/view.nim
  src/app/modules/shared_modules/keycard_popup/models/key_pair_account_model.nim
  src/app/modules/shared_modules/keycard_popup/models/key_pair_item.nim
  src/app_service/service/wallet_account/async_tasks.nim
  src/app_service/service/wallet_account/service.nim
  src/backend/accounts.nim
  ui/app/AppLayouts/Wallet/panels/DerivationPathsPanel.qml
  ui/app/AppLayouts/Wallet/panels/DerivedAddressesPanel.qml
  ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml
  ui/app/AppLayouts/Wallet/stores/RootStore.qml
  ui/app/AppLayouts/Wallet/views/AdvancedAddAccountView.qml
  ui/imports/shared/popups/keycard/helpers/KeyPairItem.qml
  ui/imports/shared/popups/keycard/helpers/KeyPairList.qml
Labels: tested

#9525 fix(main): replace the frozen splash screen with an Animator
  app/qml/Status/Application/Decorators/SplashScreen.qml
  ui/app/mainui/AppMain.qml
  ui/app/mainui/SplashScreen.qml
  ui/imports/assets/CMakeLists.txt
  ui/imports/assets/gif/status_splash_128_dark.gif
  ui/imports/assets/gif/status_splash_128_light.gif
  ui/imports/assets/gif/status_splash_dark.gif
  ui/imports/assets/gif/status_splash_light.gif
  ui/imports/assets/lottie/status_splash.json
Labels: Design-QA

#9546 fix(statusChatInput): do not replace text with emojis on links
  ui/imports/shared/status/StatusChatInput.qml
Labels: tested-issues

#9559 fix: App crashes on uploading an image containing "+" in its name
  src/app/global/utils.nim
  ui/imports/shared/status/StatusChatImageSizeValidator.qml
Labels: tested

#9550 feat(TokensPermissionsPoupup): Created new popup
  storybook/PagesModel.qml
  storybook/pages/CommunityTokenPermissionsPopupPage.qml
  storybook/pages/JoinCommunityPermissionsEditor.qml
  storybook/pages/JoinCommunityViewPage.qml
  storybook/pages/JoinPermissionsOverlayPanelPage.qml
  ui/app/AppLayouts/Chat/panels/communities/JoinPermissionsOverlayPanel.qml
  ui/app/AppLayouts/Chat/popups/community/CommunityTokenPermissionsPopup.qml
  ui/app/AppLayouts/Chat/popups/community/qmldir
  ui/app/AppLayouts/Chat/stores/CommunitiesStore.qml
  ui/app/AppLayouts/Chat/views/communities/JoinCommunityView.qml
Labels: ui, Communities, tested, feature, qml, E:Communities

#9511 fix(main): create loading item for activeSection on start
  src/app/global/app_sections_config.nim
  src/app/modules/main/controller.nim
  src/app/modules/main/io_interface.nim
  src/app/modules/main/module.nim
  src/app/modules/shared_models/section_item.nim
Labels: tested

#9580 fix(@desktop/keycard): some pictures are not modified for dark mode
  ui/imports/assets/png/keycard/card-empty.png
  ui/imports/assets/png/keycard/card_insert/img-0.png
  ui/imports/assets/png/keycard/card_insert/img-1.png
  ui/imports/assets/png/keycard/card_insert/img-10.png
  ui/imports/assets/png/keycard/card_insert/img-11.png
  ui/imports/assets/png/keycard/card_insert/img-12.png
  ui/imports/assets/png/keycard/card_insert/img-13.png
  ui/imports/assets/png/keycard/card_insert/img-14.png
  ui/imports/assets/png/keycard/card_insert/img-15.png
  ui/imports/assets/png/keycard/card_insert/img-16.png
  ui/imports/assets/png/keycard/card_insert/img-2.png
  ui/imports/assets/png/keycard/card_insert/img-3.png
  ui/imports/assets/png/keycard/card_insert/img-4.png
  ui/imports/assets/png/keycard/card_insert/img-5.png
  ui/imports/assets/png/keycard/card_insert/img-6.png
  ui/imports/assets/png/keycard/card_insert/img-7.png
  ui/imports/assets/png/keycard/card_insert/img-8.png
  ui/imports/assets/png/keycard/card_insert/img-9.png
  ui/imports/assets/png/keycard/empty-reader.png
  ui/imports/assets/png/keycard/enter-pin-0.png
  ui/imports/assets/png/keycard/enter-pin-1.png
  ui/imports/assets/png/keycard/enter-pin-2.png
  ui/imports/assets/png/keycard/enter-pin-3.png
  ui/imports/assets/png/keycard/enter-pin-4.png
  ui/imports/assets/png/keycard/enter-pin-5.png
  ui/imports/assets/png/keycard/enter-pin-6.png
  ui/imports/assets/png/keycard/keycard-new.png
  ui/imports/utils/Constants.qml
Labels: tested

#9586 fix(CommunityPermissions): Update initial page dark mode image
  ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
  ui/imports/assets/png/community/permissions21_3_1.png
  ui/imports/assets/png/community/permissions2_3.png
Labels: ui, Communities, qml, E:Communities

#9098 fix(@desktop/wallet): Remove the 'Load More' button from the Activity view
  src/app/modules/main/wallet_section/transactions/controller.nim
  src/app/modules/main/wallet_section/transactions/io_interface.nim
  src/app/modules/main/wallet_section/transactions/item.nim
  src/app/modules/main/wallet_section/transactions/model.nim
  src/app/modules/main/wallet_section/transactions/module.nim
  src/app/modules/main/wallet_section/transactions/view.nim
  src/app_service/service/transaction/async_tasks.nim
  src/app_service/service/transaction/service.nim
  ui/StatusQ/src/StatusQ/Components/StatusListItem.qml
  ui/app/AppLayouts/Wallet/views/AssetsDetailView.qml
  ui/imports/shared/controls/InformationTag.qml
  ui/imports/shared/controls/TransactionDelegate.qml
  ui/imports/shared/views/HistoryView.qml
Labels: tested

#9641 fix(Chats): Drag/drop image files is only available for community channels
  ui/app/mainui/AppMain.qml
  ui/app/mainui/panels/DropAreaPanel.qml
Labels: ui, qml, E:Bugfixes

#9634 feat(keycard): remove balance from factory reset flow if user is not logged in
  ui/imports/shared/popups/keycard/helpers/KeyPairUnknownItem.qml
Labels: tested

#9518 refactor(chat-model): simplify chat model and put category as an Item
  src/app/modules/main/chat_section/io_interface.nim
  src/app/modules/main/chat_section/item.nim
  src/app/modules/main/chat_section/model.nim
  src/app/modules/main/chat_section/module.nim
  src/app/modules/main/chat_section/view.nim
  src/app_service/service/community/service.nim
  ui/StatusQ/src/StatusQ/Components/StatusChatList.qml
  ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Labels: tested

#9442 refactor: make sure we only set active the active chat of active section
  src/app/modules/main/chat_section/controller.nim
  src/app/modules/main/chat_section/module.nim
Labels: tested
