Repository status-im/status-desktop, pull requests merged in 2024-07, with the labels that each got.

#15674 feat(ci): add Nix Linux build to nightly and release builds
  ci/Jenkinsfile.combined
Labels: ci, linux

#15727 fix(@desktop/wallet): Fix for notification showing from to token symbol and to token amount
  src/app/modules/main/module.nim
  src/app_service/service/transaction/service.nim
Labels: E:D Swap M1, swap-team

#15692 feat(connector)_: turn feature flag on
  src/app/global/feature_flags.nim
Labels: backend-team

#15760 fix missing required param to fix sign request popup display
  ui/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml
Labels: backend-team

#15787 fix(@desktop/wallet): Enabled unit tests previously marked as flaky and skipped
  storybook/qmlTests/tests/tst_SwapModal.qml
  ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml
  ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml
Labels: bug, E:D Swap M1, swap-team, 2-30-bug-bash
