Repository status-im/status-desktop, pull requests merged in 2024-06, with the labels that each got.

#15089 fix(ci): prefix PATH with correct Go compiler path
  ci/Jenkinsfile.macos
Labels: macos, ci, dependencies, go

#15093 feat(ci): use same commit as PR for e2e tests
  ci/Jenkinsfile.linux
Labels: ci

#14930 Save only the settings that are changed
  src/app/modules/main/node_section/controller.nim
  src/app/modules/main/node_section/io_interface.nim
  src/app/modules/main/node_section/module.nim
  src/app/modules/main/node_section/view.nim
  src/app/modules/main/profile_section/advanced/controller.nim
  src/app/modules/main/profile_section/waku/controller.nim
  src/app/modules/main/profile_section/waku/module.nim
  src/app_service/service/node_configuration/service.nim
  src/app_service/service/settings/service.nim
  src/backend/node_config.nim
Labels: waiting-for-status-go-merge

#15100 fix(wallet): properly marshall multiTxCommand type
  src/backend/transactions.nim
Labels: swap-team, E:D:Wallet Bugfixes
