Repository status-im/status-desktop, pull requests merged in 2024-02, with the labels that each got.

#13470 fix(ci): run only critical path of new e2e for releases
  ci/Jenkinsfile.combined
Labels: ci, testing

#13489 feat(ProfileShowcase): Assets panel navigation button
  storybook/pages/ProfileShowcaseAssetsPanelPage.qml
  ui/app/AppLayouts/Profile/panels/ProfileShowcaseAssetsPanel.qml
  ui/app/AppLayouts/Profile/panels/ProfileShowcasePanel.qml
  ui/app/AppLayouts/Profile/views/MyProfileView.qml
Labels: feature

#13493 feat(ShowcaseDelegate): Added community badge
  storybook/pages/ProfileShowcaseCollectiblesPanelPage.qml
  ui/app/AppLayouts/Profile/controls/ShowcaseDelegate.qml
Labels: feature

#13525 chore(ci): drop old E2E tests in favor of new ones
  ci/Jenkinsfile.combined
  ci/Jenkinsfile.tests-e2e
Labels: ci, testing

#13529 feat(ProfileShowcase): Save changes tooltip when disabled
  ui/app/AppLayouts/Profile/views/MyProfileView.qml
  ui/imports/shared/popups/SettingsDirtyToastMessage.qml
Labels: feature

#13541 fix(SettingsDirtyToastMessage): Save changes always disabled
  ui/imports/shared/popups/SettingsDirtyToastMessage.qml
Labels: bug

#13530 feat(ProfileShowcase): Collectibles panel navigation button
  storybook/pages/ProfileShowcaseAssetsPanelPage.qml
  storybook/pages/ProfileShowcaseCollectiblesPanelPage.qml
  ui/app/AppLayouts/Profile/controls/AddMoreAccountsLink.qml
  ui/app/AppLayouts/Profile/controls/qmldir
  ui/app/AppLayouts/Profile/panels/ProfileShowcaseAssetsPanel.qml
  ui/app/AppLayouts/Profile/panels/ProfileShowcaseCollectiblesPanel.qml
  ui/app/AppLayouts/Profile/views/MyProfileView.qml
Labels: feature

#13227 Nimbus desktop toggle setting
  src/app/modules/main/profile_section/advanced/controller.nim
  src/app/modules/main/profile_section/advanced/io_interface.nim
  src/app/modules/main/profile_section/advanced/module.nim
  src/app/modules/main/profile_section/advanced/view.nim
  src/app_service/service/node_configuration/dto/node_config.nim
  src/app_service/service/node_configuration/service.nim
  ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
  ui/app/AppLayouts/Profile/views/AdvancedView.qml
Labels: waiting-for-status-go-merge

#13664 feat(ProfileShowcase): Enable add more accounts component
  ui/app/AppLayouts/Profile/panels/ProfileShowcaseAssetsPanel.qml
  ui/app/AppLayouts/Profile/panels/ProfileShowcaseCollectiblesPanel.qml
  ui/app/AppLayouts/Profile/panels/ProfileShowcasePanel.qml
  ui/imports/shared/controls/EmptyShapeRectangleFooterListView.qml
Labels: feature

#13703 feat(ProfileShowcase): Add blur delegate state while dragging
  ui/app/AppLayouts/Profile/controls/ShowcaseDelegate.qml
  ui/app/AppLayouts/Profile/panels/ProfileShowcasePanel.qml
Labels: feature

#13477 feat(ProfileShowcase): Created first info popup
  src/app/global/local_account_settings.nim
  src/app/modules/main/profile_section/profile/io_interface.nim
  src/app/modules/main/profile_section/profile/module.nim
  src/app/modules/main/profile_section/profile/view.nim
  storybook/pages/ProfileShowcaseInfoPopupPage.qml
  ui/app/AppLayouts/Communities/panels/IntroPanel.qml
  ui/app/AppLayouts/Profile/popups/ProfileShowcaseInfoPopup.qml
  ui/app/AppLayouts/Profile/popups/qmldir
  ui/app/AppLayouts/Profile/stores/ProfileStore.qml
  ui/app/AppLayouts/Profile/views/MyProfileView.qml
Labels: feature

#13722 feat(ProfileShowcase): Adds drop area in collapsed headers
  ui/app/AppLayouts/Profile/panels/ProfileShowcasePanel.qml
  ui/imports/shared/controls/FoldableHeader.qml
Labels: feature
