Repository status-im/status-desktop, pull requests merged in 2024-01, with the labels that each got.

#11235 Update StatusWindowsTitleBar.qml
  ui/StatusQ/src/StatusQ/Platform/StatusWindowsTitleBar.qml
Labels: || stagnant ||

#13214 fix(OwnerToken): Change owner token subtitle depending on user profile
  ui/app/AppLayouts/Communities/views/MintedTokensView.qml
Labels: bug, E:Desktop Tokenized Ownership

#13294 feat(FirstTokenReceivedPopup): Created new popup `FirstTokenReceived`
  storybook/pages/FirstTokenReceivedPopupPage.qml
  ui/app/AppLayouts/Communities/popups/FirstTokenReceivedPopup.qml
  ui/app/AppLayouts/Communities/popups/qmldir
  ui/app/mainui/Popups.qml
  ui/app/mainui/ToastsManager.qml
  ui/imports/shared/stores/CommunityTokensStore.qml
  ui/imports/utils/Global.qml
Labels: ui-team, feature

#13349 feat(AC-CommunityTokenReceived): Added UI for community tokens received
  ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml
  ui/app/mainui/activitycenter/stores/ActivityCenterStore.qml
  ui/app/mainui/activitycenter/views/ActivityNotificationCommunityTokenReceived.qml
Labels: feature
