Repository status-im/status-desktop, pull requests merged in 2024-03, with the labels that each got.

#13818 feat(ProfileShowcase) Web tab visual updates according to new design
  src/app_service/common/social_links.nim
  ui/StatusQ/src/StatusQ/Components/StatusDraggableListItem.qml
  ui/StatusQ/src/assets.qrc
  ui/StatusQ/src/assets/img/icons/xtwitter.svg
  ui/app/AppLayouts/Profile/panels/ProfileSocialLinksPanel.qml
  ui/app/AppLayouts/Profile/popups/AddSocialLinkModal.qml
  ui/app/AppLayouts/Profile/popups/ModifySocialLinkModal.qml
  ui/app/AppLayouts/Profile/views/MyProfileView.qml
  ui/imports/utils/ProfileUtils.qml
Labels: feature

#13816 feat(ProfileShowcase): Display counter in `In showcase` section header a… …nd elements limit
  storybook/pages/ProfileShowcaseAccountsPanelPage.qml
  storybook/pages/ProfileShowcaseAssetsPanelPage.qml
  storybook/pages/ProfileShowcaseCollectiblesPanelPage.qml
  storybook/pages/ProfileShowcaseCommunitiesPanelPage.qml
  storybook/pages/ProfileShowcasePanelPage.qml
  ui/app/AppLayouts/Profile/controls/ShowcaseDelegate.qml
  ui/app/AppLayouts/Profile/panels/ProfileShowcasePanel.qml
  ui/imports/shared/controls/DisabledTooltipButton.qml
  ui/imports/utils/ProfileUtils.qml
Labels: feature

#13819 feat(ProfileShowcase): Add search input in all tabs
  storybook/pages/ProfileShowcasePanelPage.qml
  ui/app/AppLayouts/Profile/helpers/ProfileShowcaseDirtyState.qml
  ui/app/AppLayouts/Profile/helpers/ProfileShowcaseModels.qml
  ui/app/AppLayouts/Profile/panels/ProfileShowcaseAccountsPanel.qml
  ui/app/AppLayouts/Profile/panels/ProfileShowcaseAssetsPanel.qml
  ui/app/AppLayouts/Profile/panels/ProfileShowcaseCollectiblesPanel.qml
  ui/app/AppLayouts/Profile/panels/ProfileShowcaseCommunitiesPanel.qml
  ui/app/AppLayouts/Profile/panels/ProfileShowcasePanel.qml
  ui/app/AppLayouts/Profile/views/MyProfileView.qml
  ui/imports/utils/Constants.qml
  ui/imports/utils/ProfileUtils.qml
Labels: feature

#13910 chore(ci): do full Windows workspace cleanup
  ci/Jenkinsfile.windows
Labels: ci, windows

#13920 fix(PasswordView): Dark mode background fix
  ui/imports/shared/views/PasswordView.qml
Labels: bug

#13939 feat(ProfileShowcase): Add network prefixes and filter watch only accounts
  src/app/modules/main/profile_section/wallet/accounts/model.nim
  ui/app/AppLayouts/Profile/helpers/ProfileShowcaseModels.qml
  ui/app/AppLayouts/Profile/panels/ProfileShowcaseAccountsPanel.qml
  ui/app/AppLayouts/Profile/stores/WalletStore.qml
  ui/app/AppLayouts/Profile/views/MyProfileView.qml
Labels: feature

#14141 fix(JoinCommunity): Join CTA labelling: Change text and remove existing icon
  storybook/pages/JoinCommunityViewPage.qml
  storybook/pages/JoinPermissionsOverlayPanelPage.qml
  ui/app/AppLayouts/Chat/ChatLayout.qml
  ui/app/AppLayouts/Chat/views/ChatView.qml
  ui/app/AppLayouts/Communities/panels/JoinCommunityCenterPanel.qml
  ui/app/AppLayouts/Communities/panels/JoinPermissionsOverlayPanel.qml
  ui/app/AppLayouts/Communities/views/JoinCommunityView.qml
Labels: bug, ui-team

#14201 fix(CancelCommunityMembership): Added popup instead of directly cancelling request
  ui/app/AppLayouts/Chat/ChatLayout.qml
  ui/imports/shared/popups/CommunityMembershipSetupDialog.qml
Labels: bug
